### ISSUE TITLE
fs.copy/copySync when filter is return false, it will break copy

### ISSUE THREAD

**Issue by haozi** [jprichardson/node-fs-extra#1007]
```javascript
fs.copy(path.join(__dirname, 'src'), path.join(__dirname, 'dist'), {
   filter: (src: string) => {
       return path.extname(src) !== '.js'
   }
})
```
when I copying a folder, I wish skip file it is not *.js ，but if I return false, it will break copy, the desired purpose is to copy all non-.js files

- **Operating System:**
- **Node.js version:**
- **`fs-extra` version:**

**Comment by RyanZim** [comment]
`filter` is passed all paths, including directories. You'll have to add logic to only run your `.js` check on files, and return `true` for directories (note that this will copy empty directories if they do not contain JS files).

**Comment by haozi** [comment]
> Honestly, the filter probably isn't the best tool for the job here, you'd be better off using something like https://www.npmjs.com/package/globby to get a list of JS files, then copying each of them individually.

Could you consider adding support for glob matching in the first parameter?
Like:
```javascript
fs.copy('src/**/*.png', dest)
```

**Comment by RyanZim** [comment]
Glob support adds another entire layer of complexity and edge cases to deal with, it's unlikely we'll add it.
