### ISSUE TITLE
fs-extra promisified

### ISSUE THREAD

**Issue by overlookmotel** [jprichardson/node-fs-extra#101]
Just to let you know, I've published a module [fs-extra-promise](https://www.npmjs.com/package/fs-extra-promise) which promisifies fs-extra using bluebird.

For the most part you could just use `bluebird.promisify()`, but there are a few oddities which don't promisify properly. For example, `fs.exists()` doesn't use the usual node callback signature - it just returns `(result)` rather than `(err, result)` - so that breaks promisification.

**Comment by jprichardson** [comment]
Cool, I'll add it to the readme! I like your addition of `isDirectory()`...
I'll probably add that :)

On Sun, Jan 4, 2015 at 11:08 AM, overlookmotel <notifications@github.com>
wrote:

> Just to let you know, I've published a module fs-extra-promise
> <https://www.npmjs.com/package/fs-extra-promise> which promisifies
> fs-extra using bluebird.
>
> For the most part you could just use bluebird.promisify(), but there are
> a few oddities which don't promisify properly. For example, fs.exists()
> doesn't use the usual node callback signature - it just returns (result)
> rather than (err, result) - so that breaks promisification.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/node-fs-extra/issues/101>.
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow me on Twitter: http://twitter.com/jprichardson

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-fs-extra/commit/4729391768c20a6a39b67135694d8597bb9e628a#diff-04c6e90faac2675aa89e2176d2eec7d8
