### ISSUE TITLE
Error while writing large JSON. `RangeError: Invalid string length.`

### ISSUE THREAD

**Issue by sagarpanchal** [jprichardson/node-fs-extra#1014]
- **Operating System: macOS 13.4.1**
- **Node.js version: v18.16.0**
- **`fs-extra` version: 11.1.1**

**Comment by RyanZim** [comment]
If you're getting that error, that means the JSON you're trying to write is hitting the memory limit. Running with the [`--max-old-space-size`](https://nodejs.org/dist/latest/docs/api/cli.html#--max-old-space-sizesize-in-megabytes) CLI option may help.
