### ISSUE TITLE
touch / touchSync was removed ?

### ISSUE THREAD

**Issue by maboiteaspam** [jprichardson/node-fs-extra#102]
hi,

i don t really get why touch / touchSync methods was removed.

I was looking for this, and found out, the change log says it was recently removed.
https://github.com/jprichardson/node-fs-extra/search?q=touch&type=Code&utf8=%E2%9C%93

I ll fallback to https://github.com/isaacs/node-touch but seems weird we don t have it in fs-extra as it s kind of common usage.

Besides that, Thanks for this package !

**Comment by maboiteaspam** [comment]
Hi,

ok i ll check this. I needed to touch existing file. Not sure yet methods ensureFile will fill the job.

Thanks again!

**Comment by jprichardson** [comment]
`touch()` was renamed to `createFile()` and an alias to `createFile()` was setup as `ensureFile()`. So if `touch()` did what you wanted then `ensureFile()/createFile()` would as well since they are exactly the same.

**Comment by maboiteaspam** [comment]
can t be more clear and straightforward, thanks a lot ! sorry for the doubts : )
