### ISSUE TITLE
[Proposal] Refactor the entire code base to Promise-based

### ISSUE THREAD

**Issue by SukkaW** [jprichardson/node-fs-extra#1020]
We can use `async` and `await` to organize the codebase and `universalify.fromPromise` to create Node.js-callback style APIs from the promise-based APIs.

**Comment by RyanZim** [comment]
Yeah; that'd be great. It's a ton of work, but if you want to take a stab at it, you're more than welcome to! Just please make granular PRs; not one gigantic PR that takes hours to review.

**Comment by SukkaW** [comment]
> Yeah; that'd be great. It's a ton of work, but if you want to take a stab at it, you're more than welcome to! Just please make granular PRs; not one gigantic PR that takes hours to review.

Sure! Let's do this one API migration per PR.

I will list the roadmap here for progress tracking:

- [ ] `copy` #1021
- [ ] `fs` (add `lib/fs/promise.js` to include the promisfied version of `graceful-fs` API)
- [ ] `empty`
- [ ] `ensure`
- [ ] `json`
- [ ] `mkdirs`
- [ ] `move`
- [ ] `output-file`
- [ ] `path-exists`
- [ ] `remove`
