### ISSUE TITLE
support `file://` url string path

### ISSUE THREAD

**Issue by jimmywarting** [jprichardson/node-fs-extra#1022]
NodeJS dose not really support `file://<path>` url strings, they need to be converted into URL instances first and formost to be supported. 

in the lights of new ESM modules, ppl turn more towards the help of `import.meta.url` and also the new `import.meta.resolve('./worker.js')` but this two dose only return file-url-string, 

not a url instance.
the lack of `file://` strings support in NodeJS is problematic and annoying for many developers.

it leads to unconventional inovation that makes the NodeJS creator inventing even more non standard `import.meta` properties 
that i do not think should be added. 

> Pushing for a import.meta property that is specific to modules loaded from disk is bad, because it discourages and prevents portability in cases where that is not warranted.

https://github.com/wintercg/proposal-common-minimum-api/issues/50

Here is a quick and dirty solution that i propose: [fsURL](https://togithub.com/LiviaMedeiros/fsURL)

**Comment by jimmywarting** [comment]
Yes

**Comment by RyanZim** [comment]
Also cc @jprichardson @manidlou @JPeer264 for thoughts here.

**Comment by manidlou** [comment]
I agree with @RyanZim, I don't see an absolute necessity for it right now.
