### ISSUE TITLE
Error: EMFILE with copy

### ISSUE THREAD

**Issue by zg2013** [jprichardson/node-fs-extra#103]
On the windows8 every error.
Copy a 200M 10000 file folders,File no small problem
code：
![qq 20150108230501](https://cloud.githubusercontent.com/assets/5134292/5664382/ff829530-978a-11e4-9000-818d7e1cc384.png)

error：
![qq 20150108230602](https://cloud.githubusercontent.com/assets/5134292/5664483/c00d2950-978b-11e4-8055-1c097c534f72.png)

Thank you for your offer solutions or fixes BUG！
Copy files:
![qq 20150108231402](https://cloud.githubusercontent.com/assets/5134292/5664555/1c2a3b2e-978c-11e4-9ce5-d77a298072d0.png)

**Comment by jprichardson** [comment]
This is because the copy module (https://www.npmjs.com/package/ncp) doesn't use the module (https://www.npmjs.com/package/graceful-fs). There's an issue filed: https://github.com/AvianFlu/ncp/pull/70 But they've been unresponsive unfortunately. I plan to rewrite `copy` using `graceful-fs`.

**Comment by jprichardson** [comment]
Try it now. https://github.com/jprichardson/node-fs-extra/releases/tag/0.15.0 Please reopen if the issue still happens.
