### ISSUE TITLE
fse.move deletes folders

### ISSUE THREAD

**Issue by dustin-H** [jprichardson/node-fs-extra#104]
Hi,

I noticed when I'm moving a folder into itself like 
    fse.move('/Users/dustin/fstest/test', '/Users/dustin/fstest/test/test'
the folder gets deleted.
I expected an error or something but not this. Is this a bug?

Best regards

Dustin

**Comment by jprichardson** [comment]
Yeah, this is definitely a bug...

**Comment by jprichardson** [comment]
Thanks for reporting :)

**Comment by dustin-H** [comment]
You're Welcome!
