### ISSUE TITLE
 module not found: fs/promises

### ISSUE THREAD

**Issue by yknn** [jprichardson/node-fs-extra#1041]
I encountered two problems, the first problem is that the "fs-extra/esm" module cannot be imported in the preload.js script in electron, vite, vue3 projects. The second problem is that after removing the item 'fs-extra/esm' module entry, the message "module not found: fs/promises" is displayed.

![image](https://github.com/jprichardson/node-fs-extra/assets/24401371/43ea1a91-7c92-4d3e-bdee-8d063c933184)
![image](https://github.com/jprichardson/node-fs-extra/assets/24401371/4f7c151a-c106-4823-84e3-f1ebcdec1368)

**Comment by RyanZim** [comment]
Do you have `nodeIntegration` turned on? What version of `fs-extra` do you have installed?

**Comment by RyanZim** [comment]
Closing for lack of response.
