### ISSUE TITLE
fs.copy hangs on iojs

### ISSUE THREAD

**Issue by mzgol** [jprichardson/node-fs-extra#105]
Steps to reproduce:

1. `git clone git@github.com:mzgol/check-dependencies.git`
2. `cd check-dependencies`
3. Create a file `test.js` with contents:
    ```js

    var fs = require('fs-extra');

    var npmFixturesDir = __dirname + '/npm-fixtures',
        generatedDir = __dirname + '/bower-fixtures/generated';

    fs.copy(npmFixturesDir, generatedDir, function (error) {
        if (error) {
            throw error;
        } else {
            console.log('Success!');
        }
    });
    ```
4. Run the following command in terminal:
    ```sh

    rm -rf test/bower-fixtures/generated && node test/spec.js 
    ```

It works fine on Node 0.10.35 & 0.11.14, it gets stuck indefinitely in io.js 1.0.2.

This is making the tests fail on io.js in my `check-dependencies` module.

fs-extra `0.14.0`, OS X 10.10.1. I use Node & io.js via [nvm](https://github.com/creationix/nvm/).

**Comment by jprichardson** [comment]
It's because of `ncp`. I think there are some other issues related:
https://github.com/avianflu/ncp I'll look into it more. Thanks for
reporting.

On Mon, Jan 19, 2015 at 8:33 AM, Michał Gołębiowski <
notifications@github.com> wrote:

> Steps to reproduce:
>
>    1. git clone git@github.com:mzgol/check-dependencies.git
>    2. cd check-dependencies
>    3.
>
>    Create a file test.js with contents:
>
>    var fs = require('fs-extra');
>    var npmFixturesDir = __dirname + '/npm-fixtures',
>    generatedDir = __dirname + '/bower-fixtures/generated';
>
>    fs.copy(npmFixturesDir, generatedDir, function (error) {if (error) {
>        throw error;
>    } else {
>        console.log('Success!');
>    }
>    });
>
>     4.
>
>    Run the following command in terminal:
>
>    rm -rf test/bower-fixtures/generated && node test/spec.js
>
>
> It works fine on Node 0.10.35 & 0.11.14, it gets stuck indefinitely in
> io.js 1.0.2.
>
> This is making the tests fail on io.js in my check-dependencies module.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/node-fs-extra/issues/105>.
>



-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow me on Twitter: http://twitter.com/jprichardson

**Comment by jprichardson** [comment]
Awaiting on this https://github.com/creationix/nvm/pull/616 When it gets pulled, I'll be able to download and test.

**Comment by mzgol** [comment]
nvm 0.23.0 with io.js support is out :)

**Comment by jprichardson** [comment]
Should be fixed now. https://github.com/jprichardson/node-fs-extra/releases/tag/0.15.0

**Comment by mzgol** [comment]
It works now, thanks!
