### ISSUE TITLE
fse.copySync crashes while copying across devices D:

### ISSUE THREAD

**Issue by ct-js** [jprichardson/node-fs-extra#106]
If I try to use `fs.copySync` for copying across different disk drives, my app crashes T_T Copying across one drive works well.

**Comment by jprichardson** [comment]
Platform (Windows, Linux)? Node version? Snippet code to reproduce?

**Comment by ct-js** [comment]
Windows 8.1, used in nw.js 0.11.5 https://github.com/nwjs/nw.js (actually it shouldn't affect node module), node.js `0.11.13-pre`.

    fs.copySync('C:\Users\Cosmo\Desktop\waves.jpg','D:\ct\blahblah\img\i10.jpg');
    // crash! It doesn't even throws exceptions.

**Comment by jprichardson** [comment]
Ok, thanks. Does it work by chance if `'D:\ct\blahblah\img\` exists?

**Comment by ct-js** [comment]
All the needed directories with the source file exist.
I encountered similar problem while using `fs.link` (?) function long ago, and solved that with streams. But it is an asynchronous technique ._.

**Comment by jprichardson** [comment]
But does it work if the destination directory already exists?

**Comment by ct-js** [comment]
No :(

**Comment by RyanZim** [comment]
@jprichardson Can you reproduce?

**Comment by jprichardson** [comment]
Nope, can't produce on Windows 10 and Node v6. Please reopen @ct-js if still an issue.
