### ISSUE TITLE
fse.move directories across multiple devices doesn't work

### ISSUE THREAD

**Issue by nicks** [jprichardson/node-fs-extra#108]
Create a dir on another device:
```sh
mkdir -p /path/to/my/dir
```

Then try to move it:
```js
var fs = require('fs-extra')
fs.move('/path/to/my/dir', './nick', function (err) {
  if (err) throw err
})
```

fs.move reports success, and deletes the old directory, but does not actually create the new directory. It just creates an empty 0-length file.

Tested on Linux ip-10-37-137-70 3.10.42-52.145.amzn1.x86_64 #1 SMP Tue Jun 10 23:46:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jprichardson** [comment]
Awesome, thanks! Looking into it..

**Comment by jprichardson** [comment]
Got VM setup, mounted an external device, verified problem. Working on a fix...

**Comment by jprichardson** [comment]
Fixed. Relevant test here: https://github.com/jprichardson/node-fs-extra/blob/master/test/move.test.js#L171 I'm looking over some `fs.copy` stuff before I publish the new version. New version should be published soon.

**Comment by jprichardson** [comment]
Published. Changelog: https://github.com/jprichardson/node-fs-extra/releases/tag/0.16.0

**Comment by nicks** [comment]
thanks!
