### ISSUE TITLE
Thoughts on including a file walker?

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#11]
I really like this one: https://github.com/daaku/nodejs-walker

**Comment by jprichardson** [comment]
Closing this in favor of discussion in https://github.com/jprichardson/node-fs-extra/issues/63

**Comment by TechQuery** [comment]
@jprichardson I wrote a Folder Walker based on **Async Iteration** syntax: https://tech-query.me/fs-match/modules/core.html#traverse
