### ISSUE TITLE
fs.copy seems to callback early if the destination file already exists

### ISSUE THREAD

**Issue by iantocristian** [jprichardson/node-fs-extra#113]

**Comment by jprichardson** [comment]
Presumably using the latest `fs-extra` version, right? This should have been solved in https://github.com/jprichardson/node-fs-extra/issues/98. Any way you can reproduce it or have a snippet of code? Thanks

**Comment by jprichardson** [comment]
Closing since I believe this be solved with #98. Please reopen if this is still occurring with the latest version.
