### ISSUE TITLE
mkdirs and ensureDir never invoke callback and consume CPU indefinitely if provided a path with invalid characters on Windows

### ISSUE THREAD

**Issue by jacob-adams** [jprichardson/node-fs-extra#119]
The following code will never call the provided callback when executed on a windows machine:

    fs.ensureDir('C:\\temp\\a?b', function(err){console.log(err)})

It also makes the node process consume a lot of CPU indefinitely.  For reference, the built-in node function 'fs.mkdir' calls the callback with an error if it is called with a path that has invalid characters.  The following is an example of the error reported by node's fs.mkdir function:

    > fs.mkdir('C:\\temp\\a?b', function(err){console.log(err)})
    > { [Error: ENOENT, mkdir 'C:\temp\a?b'] errno: -4058, code: 'ENOENT', path: 'C:\\temp\\a?b' }

It appears that the problem occurs because calling mkdir throws the same error for a path with invalid characters as it does for a path with a parent directory that does not exist.

**Comment by jprichardson** [comment]
Thanks for the report! I'm going to have to get `fs-extra` setup on AppVeyor to be able to test these Windows specific bugs...

**Comment by jprichardson** [comment]
Related #209, #237. Fixed.
