### ISSUE TITLE
usage bug caused by shallow cloning methods of 'graceful-fs'

### ISSUE THREAD

**Issue by futagoza** [jprichardson/node-fs-extra#120]
*fs-extra* shallow clones the methods from *graceful-fs*, but this seems to cause a usage bug in newer Node.js and IO.js builds, because newer non-method properties from the native *fs* module are ignored, for example 'fs.F_OK' used by 'fs.access(Sync)' cannot be accessed.

I did a simple [workaround by shallow cloning first *fs* and then *fs-extra*](https://github.com/futagoza/efe/commit/73d420a1d4c74ca16cf68eb7fa01d974db8a228e) in [efe](https://www.npmjs.com/package/efe)

**Comment by jprichardson** [comment]
awesome, thanks for pointing out :)
