### ISSUE TITLE
 TypeError: Object #<Object> has no method 'access'

### ISSUE THREAD

**Issue by mike-aungsan** [jprichardson/node-fs-extra#126]
TypeError: Object #<Object> has no method 'access'

all fs function should be available rt?

**Comment by mike-aungsan** [comment]
This seem to be node issue. I tested with fs module.

**Comment by jprichardson** [comment]
Presumably you're using node 0.10.x? If so, those methods aren't available.

On Monday, April 13, 2015, mike <notifications@github.com> wrote:

> This seem to be node issue. I tested with fs module.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jprichardson/node-fs-extra/issues/126#issuecomment-92554749>
> .
>


-- 
Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson
