### ISSUE TITLE
copySync is not working iojs 1.8.4 on linux

### ISSUE THREAD

**Issue by Alex0007** [jprichardson/node-fs-extra#131]
```javascript
fse.copySync('mobile/dist/assets/www/assets/', 'mobile/dev/assets/www/assets/')
```
Async version of this -- works, but sync is not

**Comment by jprichardson** [comment]
I'm not able to reproduce. Is this still happening? What are the contents of the files in `assets`?

**Comment by eddflrs** [comment]
I just ran into this one. Same as @Alex0007, as soon as I switched the call from `copySync` to `copy` it worked. So the async version seems to work, but not sync.

**Comment by jprichardson** [comment]
@eddflrs can you provide any code or organization of the directory structure so that I'm able to reproduce? Thanks.

**Comment by jprichardson** [comment]
I need more information to reproduce. Thanks.
