### ISSUE TITLE
emptyDir throws Error if no callback is provided

### ISSUE THREAD

**Issue by deyhle** [jprichardson/node-fs-extra#135]
I use `emptyDir(…)` in a mocha `after` hook to delete files generated by my test cases:

``` js
  after('remove compiled files', function() {
    fs.emptyDir('./build');
  });
```

This throws the following error in node's `fs` (?) if no `callback` argument is provided:

```
TypeError: undefined is not a function
    at FSReqWrap.oncomplete (fs.js:95:15)
```

If I provide an empty function as callback, all is fine:

``` js
  after('remove compiled files', function() {
    fs.emptyDir('./build', function(){});
  });
```

I'm on Node v0.12.2.

**Comment by jprichardson** [comment]
This definitely shouldn't throw an error if no callback is provided, but why don't you just do this in meantime?

```js
after('remove compiled files', function(done) {
    fs.emptyDir('./build', done);
  });
```

**Comment by RyanZim** [comment]
@deyhle I can't reproduce, perhaps this has been fixed?

**Comment by RyanZim** [comment]
Going to assume this is fixed. Closing.
