### ISSUE TITLE
outputFile/outputJson: Unexpected end of input

### ISSUE THREAD

**Issue by kevinohara80** [jprichardson/node-fs-extra#137]
I have a simple script that reads a JSON file using `readJson`, sets some properties on it, then writes it back to the file system. I've tried writing using both `outputJson` and `outputFile` and both throw a JSON parse error inside of jsonfile.

```
Unhandled rejection SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/kevinohara/dev/node/dmc/node_modules/fs-extra/node_modules/jsonfile/lib/jsonfile.js:18:18
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Note: I am wrapping all functions in fs-extra in promises using bluebird and `Promise.promisifyAll(require('fs-extra'))`. This has been working fine until this point. It seems as if there is an exception being bubbled up to the surface by the promise chain.

I've reverted back to plain-ole fs reads/writes and everything is working fine.

Any ideas?

**Comment by jprichardson** [comment]
> Any ideas?

It's tough to say without any snippets of code.

>  I've tried writing using both outputJson and outputFile and both throw a JSON parse error inside of jsonfile.

`outputFile` doesn't do anything with JSON. If you would post a snippet to reproduce the problem, that'd be helpful.

**Comment by jprichardson** [comment]
> This has been working fine until this point. 

Also, what does this mean? Did you upgrade to another version of `fs-extra` and now it broke? Does it mean that you changed some of your code? Does it mean that the data changed?

**Comment by kevinohara80** [comment]
> Also, what does this mean? Did you upgrade to another version of fs-extra and now it broke? Does it mean that you changed some of your code? Does it mean that the data changed?

Wrapping all of fs-extra in promises has worked fine until this point. Now I'm writing a JSON file back to the file system and getting this exception somewhere inside of jsonfile. This happens when I use both outputJson and outputFile. 

> It's tough to say without any snippets of code.

I'm going to have to work up repro code as there's too much going on in the project I'm working on. I'll see if I can get something simple that demonstrates the issue.

**Comment by klarkent** [comment]
Having same issue using session-file-store
```
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/salvo/.local/src/km3net/platform/www/webapp/node_modules/session-file-store/node_modules/fs-extra/node_modules/jsonfile/index.js:14:18
    at fs.js:334:14
    at /home/salvo/.local/src/km3net/platform/www/webapp/node_modules/session-file-store/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by brunobottazzini** [comment]
Hello there, 

I am having the same issue with session-file-store. 

Has anyone found out how to fix it?

    SyntaxError: Unexpected end of input
         at Object.parse (native)
         at /soletta-dev-app/node_modules/session-file-store/node_modules/fs-extra/node_modules/jsonfile/index.js:14:18
         at fs.js:334:14
         at /soletta-dev-app/node_modules/session-file-store/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
         at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by jprichardson** [comment]
It would be immensely helpful if someone would provide a snippet replicating this issue. A stack trace with no context won't help me to help solve the problem.

**Comment by mbrk** [comment]
Same problem when using ensureFileAsync from promisified fs-extra. I want to append contents from one file to another. To ensure that the 'target' is existing i use ensureFile().

Code:
```
var Promise = require('bluebird');
var fs = Promise.promisifyAll(require('fs-extra'));

var src = './path/to/existing/file.json';
var target = './path/to/not/existing/file.json';

var appendToFile = function(srcFile, tgtFile){

	// this works as expected and creates the file if it is not there
	fs.ensureFileAsync(tgtFile)
		.then(function(){
			var p = [];
			p.push(fs.readJsonAsync(srcFile));
			// without the following line no errors occur
			p.push(fs.readJsonAsync(tgtFile));
			return Promise.all(p);
		})
		.then(function(r){
			console.log(r);
		})
		.catch(function(e){
			throw new Error(e);
		});
};

appendToFile(src, target);

```

Stacktrace:
````
Unhandled rejection Error: SyntaxError: ./path/to/not/existing/file.json: Unexpected end of input
    at /path/to/project/scripts/test.js:21:10
    at tryCatcher (/path/to/project/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/path/to/project/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/path/to/project/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/path/to/project/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/path/to/project/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/path/to/project/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/path/to/project/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

```

Something from inside bluebird but it seems to origin somewhere in fs-extra. Hope this helps.

**Comment by mbrk** [comment]
this happens even when the ensureFile() is done without promisified fs-extra. Doesn't matter if ensureFile() with callback or ensureFileSync(). The created file is empty (as expected) but it is not working with readJsonAsync)() in the following code.

**Comment by eschwartz** [comment]
Has anyone been able to figure out what's going on here? I'm having the same issue, also using a promisified version of fs-extra (using [`when.liftAll`](https://github.com/cujojs/when/blob/master/docs/api.md#nodeliftall)). I have a bunch of processes reading and writing to a json files, though all the writes are locked using [node-proper-lock](https://github.com/IndigoUnited/node-proper-lockfile).

The script I'm running will work fine for days at a time, and then for whatever reason, a json file ends up empty. I've tried reproducing the issue, without success. In fact, there are no arguments I can pass to `fs.writeJson` which result in an empty file.

Any ideas would be greatly appreciated.

**Comment by RyanZim** [comment]
@jprichardson Can you look into this?

**Comment by jprichardson** [comment]
I think we need more info here that isolates a reproducible case to just `fs-extra`. Every single case is using a promisified version.

**Comment by RyanZim** [comment]
I'm going to close this; if this resurfaces, please open a new issue.
