### ISSUE TITLE
Preserve timestamps on copying files

### ISSUE THREAD

**Issue by goloroden** [jprichardson/node-fs-extra#138]
On Unix it is possible to copy a file with the `-p` flag to preserve timestamps. It would be awesome if this option could be supported by fs-extra.

Basically I think that this should be quite easy to implement since Node.js already has the [`fs.utimes`](https://nodejs.org/api/fs.html#fs_fs_utimes_path_atime_mtime_callback) function that should have you covered.

There may be two options on how to use this:

- Either only on demand, i.e. if the user explicitly requests it,
- or implicitly, i.e. always when copying files.

What do you think about this?

**Comment by jprichardson** [comment]
I'd definitely support this. The behavior to mimic is whatever Windows/POSIX `copy`/`cp` does.

**Comment by goloroden** [comment]
Thanks for your fast reply :-). We figured out how to do it.

We'll send a pull request in a few minutes :-)

**Comment by goloroden** [comment]
Awesome, thanks :-)))
