### ISSUE TITLE
update graceful-fs

### ISSUE THREAD

**Issue by futagoza** [jprichardson/node-fs-extra#143]
Can you update [graceful-fs](https://www.npmjs.com/package/graceful-fs) from `3.0.2` to `4.1.2`?

It seems that [mock-fs](https://www.npmjs.com/package/mock-fs) and my module ([efe](https://www.npmjs.com/package/efe)) were having trouble overwriting the native fs
because graceful-fs used to bootstrap the built-in `fs` via the `vm` module.

With the latest version (graceful-fs@4.1.2), mock-fs works as expected.

**Comment by jprichardson** [comment]
Done. I won't release just yet... I'm hoping that https://github.com/nodejs/io.js/issues/2069 has some resolution soon.

**Comment by jmls** [comment]
did you eventually release this ? I'm having some problems with jasmine, fs-extra and mock-fs and was wondering  if this could be the cause.

If I use 

```javascript
var fs = require('fs)
```
then the tests work fine.

replace with 

```javascript
var fs = require('fs-extra') 
```

then the tests start failing

**Comment by jmls** [comment]
and now I see that you did indeed push it into .21 .. I'm on .22 , so should be there. Which now means that I need tro figure out why my tests are failing just by swapping out fs with fs-extra

**Comment by jprichardson** [comment]
@jmls It would really be helpful to know more about the errors that you're having so that I could help diagnose the issue and possibly fix it.
