### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by futagoza** [jprichardson/node-fs-extra#144]
# Implementation
Your new implementation of running the tests is okay if the module being tested isn't under some folder called `node_modules` some where in its pathname, but if it is, 0 tests are found.
It runs fine with this code: https://shrib.com/fs-extra-test.js-fix?v=pr

# Copy, move and ncp
I'm not sure these other errors are related to me running on Windows 8.1 x64, but thought I should put them up: https://shrib.com/GsntR4KJ?v=pr

**Comment by jprichardson** [comment]
Your first point about the tests not running, I'm not clear about the case where they're not?

Regarding the tests failing, that's because you pulled the master branch (development). There's one issue that I believe to be a bug in io.js. More details here: https://github.com/jprichardson/node-fs-extra/pull/141.

**Comment by futagoza** [comment]
Your `tests.js` file works if its located in `C:/dev/node-fs-extra`, finding 60+ tests, but fails with your code if the file is located in `C:/dev/efe/node_modules/fs-extra`, finding 0 tests.

In [my edited `file.js`](https://shrib.com/fs-extra-test.js-fix?v=pr) I have removed the line that looks for node_modules in the file path, also setting the walk method to look in `./lib` only. This works fine and ensures that it wont look inside the modules own `node_modules` directory.

If its really required to search multiple folders to add tests to mocha, then you should wrap the walker ([see example: https://shrib.com/fs-extra-test.js-modified?v=pr](https://shrib.com/fs-extra-test.js-modified?v=pr)). This should avoid looking in folders that are in `node_modules`, unless of course there's a reason to scan 5000+ file names ;)

**Comment by futagoza** [comment]
@jprichardson any update on this? Right now I've got a edited cloned repo with the changes I've mentioned above so that I can optionally run the fs-extra tests (correctly, see above note about 'node_modules') along with mine

**Comment by jprichardson** [comment]
Sure, please submit a PR and I'll accept it. But note, it should find > 100 tests in either scenario.

**Comment by futagoza** [comment]
Ok, I'll do that later on today when I get home

**Comment by futagoza** [comment]
Sorry for the delay, I got wrapped up in a problem.

I cloned from [#ff2d36](https://github.com/jprichardson/node-fs-extra/commit/ff2d362f059d4f28c0b866cfaef675816ad4b9c2), which is 5 commits ago as of now.

The modified `test.js` is only finding 43 tests, I can't find the other 50+
Are you sure there are 100+ tests?

**Comment by jprichardson** [comment]
> The modified test.js is only finding 43 tests, I can't find the other 50+ Are you sure there are 100+ tests?

Yes :) https://travis-ci.org/jprichardson/node-fs-extra/jobs/69456709 Results from your pull request. I'm really curious to as why on your system there's only 43. If it's helpful I could attach an output from either `spec` or `json` and you could do a diff and see which ones aren't coming up...

**Comment by futagoza** [comment]
oh lol, your talking about the individual registered tests aren't you? All this time I though you were talking about the files that contain the tests, which are only 43 files :D

**Comment by jprichardson** [comment]
Oh haha... that makes sense!

**Comment by jprichardson** [comment]
Closing as https://github.com/jprichardson/node-fs-extra/pull/146 fixes this. Thanks!
