### ISSUE TITLE
Adding rmdirIfEmpty

### ISSUE THREAD

**Issue by paroga** [jprichardson/node-fs-extra#147]
Would you accept an PR (with tests and documentation) for a function which deletes an directly if it is empty?

```JavaScript
function removeEmptyDirSync (dir) {
  try {
    fs.rmdirSync(dir)
  } catch (err) {
    if (err.code !== 'ENOTEMPTY')
      throw err
  }
}

function removeEmptyDir (dir, callback) {
  fs.rmdir(path, function(err) {
    if (!callback)
      return

    if (err && err.code !== 'ENOTEMPTY')
      return callback(err)

    callback(null)
  })
}
```

**Comment by jprichardson** [comment]
What's the use case?

**Comment by paroga** [comment]
Cleanup to get rid of useless directories.
Imagine a folder structure like in the ".git/objects" folder, where the filename is split up in the first two characters and all other. When a file is removed the parent folder should be removed too, if there are no files remaining.

**Comment by jprichardson** [comment]
While I can see the utility in it, I'm going to reject the idea for now. I'm trying to keep the API surface area as minimal as possible for the time being. My main priority is getting to 1.0. Thanks for your interest though.

**Comment by paroga** [comment]
thx anyway. good luck for 1.0! :-)
