### ISSUE TITLE
split out `Sync` methods in documentation

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#148]
Currently `*Sync` methods aren't documented on their own. They should be for the followings reasons:
1. New users to Node.js think that a callback needs to be passed to the sync methods.
2. Certain nuances may exist that deserve to be documented.

**Comment by RyanZim** [comment]
@jprichardson I don't see this happening for v1.0.0, perhaps v1.0.1?

**Comment by manidlou** [comment]
Closes via #382.
