### ISSUE TITLE
/tmp/millis-test-sync

### ISSUE THREAD

**Issue by barocsi** [jprichardson/node-fs-extra#149]
When multiple nodejs instances are running they all want to access this same file thus permission denied Error: EACCES, permission denied '/tmp/millis-test-sync'

**Comment by jprichardson** [comment]
You're running multiple fs-extra tests or what?

**Comment by barocsi** [comment]
just multiple nodejs worker instances on the same host

**Comment by jprichardson** [comment]
Ahh, I figured out the problem: https://github.com/jprichardson/node-fs-extra/blob/5b8470815c7fcae0f62a5830ae8de097d6a5df3f/lib/util/utimes.js#L10 Fixing...

**Comment by jprichardson** [comment]
Ok, pending all tests pass on Travis/Appveyor, I'll publish. Should be shortly.

**Comment by jprichardson** [comment]
Published fix in `0.22.1`.

**Comment by jprichardson** [comment]
Thanks for reporting :)
