### ISSUE TITLE
TOC does not work correctly on npm

### ISSUE THREAD

**Issue by joepie91** [jprichardson/node-fs-extra#151]
In the [Table of Contents on npm](https://www.npmjs.com/package/fs-extra#methods) (named 'Methods'), at least one link - that for `remove` - does not work. This seems to be due to a difference in anchor generation between GitHub and npm (`removedir-callback` vs. `remove-dir-callback`).

I'm not sure who would be responsible for patching this (npm, perhaps?), but I figured I'd make note of it, as it is currently breaking the TOC on npm.

**Comment by jprichardson** [comment]
Thanks for notifying me, I'll just change the signatures so that they match :)

**Comment by RyanZim** [comment]
Apparently this has been fixed somewhere along the line; can't reproduce.
