### ISSUE TITLE
/tmp/millis-test-sync

### ISSUE THREAD

**Issue by khemer** [jprichardson/node-fs-extra#154]
I'm having problem after I update ember-cli to the latest version 1.13.1.

When multiple users access different ember project, all ember instance access the same file(/tmp/millis-test-sync), thus I'm having permission error.
ex:
user1
cd ~/project1/
ember -v
result: display the ember version 1.13.1

user2
cd ~/project2/
ember -v 
result: permission denied in /tmp/millis-test-sync

I follow this issue <a href='https://github.com/jprichardson/node-fs-extra/issues/149'>#149</a> and update the fs-extra globally and to all ember project locally:
sudo npm install -g fs-extra@0.22.1
npm install fs-extra@0.22.1

But the problem persist. Maybe I'm doing it wrong?
kindly guide me, thanks. 

Here are some info you may need:
OS: Ubuntu server
node: 0.12.4
npm: 2.12.1
ember: 1.13.1
fs-extra: 0.22.1
error log:
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EACCES, permission denied '/tmp/millis-test-sync'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.writeFileSync (fs.js:1099:15)
    at hasMillisResSync (/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra/lib/util/utimes.js:11:6)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra/lib/util/utimes.js:4:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by jprichardson** [comment]
`fs-extra@0.22.1` doesn't access `'/tmp/millis-test-sync'` so you must be using an old version of `fs-extra` somewhere. My advice would be to delete any `fs-extra` instances locally and globally and the same for `ember-cli`.

```
npm rm -g fs-extra
npm rm fs-extra

npm rm -g embler-cli
npm rm ember-cli
```

and then reinstall `ember-cli`.

**Comment by khemer** [comment]
I found out the problem.

- As you say I did uninstall fs-extra and ember-cli globally and locally
- After that, I reinstall ember-cli
- next I try to test it again

<i>&emsp; user1
&emsp; cd ~/project1/
&emsp; ember -v
&emsp; result: display the ember version 1.13.1

&emsp; user2
&emsp; cd ~/project2/
&emsp; ember -v 
&emsp; result: permission denied in /tmp/millis-test-sync</i>

- The problem persist, because fs-extra is being access inside ember-cli(*path = /usr/local/lib/node_modules/ember-cli/node_modules/fs-extra) which is outdated version
- I update to the latest version fs-extra(sudo npm install -g fs-extra@0.22.1)
- Instead of updating fs-extra inside ember-cli, it create a module in this path /usr/local/lib/node_modules/, but the strange thing is ember does not access the latest fs-extra(/usr/local/lib/node_modules/fs-extra), instead it access the outdated fs-extra(/usr/local/lib/node_modules/ember-cli/node_modules/fs-extra). That is why the problem occur.
- I copy  /usr/local/lib/node_modules/fs-extra to /usr/local/lib/node_modules/ember-cli/node_modules/fs-extra and that fix the problem

Strange why did this happen? :), nonetheless thanks for the reply....

**Comment by jprichardson** [comment]
Try this:

    rm -rf (/usr/local/lib/node_modules/ember-cli/

then:

    npm cache clean
    npm i -g ember-cli@latest

and then try your test again.

**Comment by jprichardson** [comment]
I'm guessing it was just picking up an old stale version? Not sure... but it is weird.

**Comment by khemer** [comment]
the problem still persist, ember-cli@latest v1.13.1 is using the old version fs-extra.
installing fs-extra@latest will not update fs-extra in this directory <code>node_module/ember-cli/node_modules/fs-extra</code> instead will install it in this directory <code>node_module/fs-extra</code>.

by manually moving node_module/fs-extra to node_module/ember-cli/node_modules/fs-extra solve my problem.

Yeah this is too weird or maybe there is a proper way to update fs-extra instead of using this command line <code>sudo npm install -g fs-extra@0.22.1</code>, btw, I'm a newbie on ember and nodejs.

Ultimately the problem was not fs-extra itself so I will close this issue.

Again thank you for your time...

**Comment by jprichardson** [comment]
> Again thank you for your time...

No problem :)
