### ISSUE TITLE
Issues using writeJson with Babel

### ISSUE THREAD

**Issue by donaldpipowitch** [jprichardson/node-fs-extra#157]
If I `writeJson` my output isn't formatted. I think this is a problem with `jsonfile`? I use the most recent version.

````
console.log(fs.jsonfile); // {}
fs.jsonfile.spaces = 2;
console.log(fs.jsonfile); // {} ... I think this should be { spaces: 2 }
````

**Comment by jprichardson** [comment]
What is the output that you get from this snippet?

```js
var fs = require('fs-extra')

var data = { name: 'jp' }
fs.jsonfile.spaces = 4
fs.writeJson('/tmp/test.json', data, function (err) {
  if (err) console.error(err)
  var text = fs.readFileSync('/tmp/test.json', 'utf8')
  console.log(text)
})
```

**Comment by donaldpipowitch** [comment]
Well... the output is correct:

````
{
    "name": "jp"
}
````

To be honest, I really use `fs-extra-promise` not vanilla `fs-extra`. So I changed your example after the first test to this:

````
var fs = require('fs-extra-promise')

var data = { name: 'jp' }
fs.jsonfile.spaces = 4
fs.writeJsonAync('/tmp/test.json', data).then(function () {
  var text = fs.readFileSync('/tmp/test.json', 'utf8')
  console.log(text)
})
````

And... the output is still correct:

````
{
    "name": "jp"
}
````

Now I was really confused... why doesn't it work for me outside of this small test case?  I use `fs-extra-promise` instead of `fs-extra`, because I use Babel. So I made a third test:

````
import fs, { writeJsonAsync, readFileSync} from 'fs-extra-promise';

var data = { name: 'jp' }
fs.jsonfile.spaces = 4
writeJsonAync('/tmp/test.json', data).then(function () {
  var text = freadFileSync('/tmp/test.json', 'utf8')
  console.log(text)
})
````

And... _BAM_... this is the error:

````
{"name":"jp"}
````

The same happens if I use `writeJson` with `fs-extra` instead of the promisified version.

So... if Babel got the spec right (cc @sebmck) and doesn't have a bug, I'd say this is a bug on `fs-extra`s side. As ES6 modules are now standardized (just not implemented yet in native Node) I'd expect `import { writeJson } from 'fs-extra';` to work like `var writeJson = require('fs-extra').writeJson`.

**Comment by RyanZim** [comment]
@jprichardson Any ideas? I've got other more pressing things ATM.

**Comment by jprichardson** [comment]
This is over a year old. If there is still some issue with the latest versions and Babel6, feel free to reopen @donaldpipowitch.
