### ISSUE TITLE
Feature Request: ensureLink and ensureSymlink methods

### ISSUE THREAD

**Issue by reggi** [jprichardson/node-fs-extra#158]
I'd really love support for `fse.ensureLink` and `fse.ensureSymlink`. How can we make this happen?

I have really crappy examples right now :(

**Note**: They're Promises.

fsEnsureLink

```javascript
var R = require("ramda")
var path = require("path")
var Promise = require("bluebird")
var fs = Promise.promisifyAll(require("fs"))
var fse = Promise.promisifyAll(require("fs-extra"))
var fsExists = require("./fs-exists")

/**
 * Ensures a Link or "hard link" to a file.
 * @param  {String} srcpath - Source of the link
 * @param  {String} dstpath - Destination of the new link
 * @return {Promise.<True, Error>}
 */
function fsEnsureLink(srcpath, dstpath){
  return Promise.all([
    fsExists(srcpath).then(function(exists){
      if(!exists) throw new Error("source path does not exist")
      return false
    }),
    fsExists(dstpath).then(function(exists){
      if(exists) throw new Error("destination path already exists")
      return false
    })
  ]).then(function(){
    return fse.mkdirs(path.dirname(dstpath))
  }).then(function(){
    return fs.linkAsync(srcpath, dstpath)
  }).then(R.T)
}

module.exports = fsEnsureLink
```

fsEnsureSymlink

```javascript
var Promise = require("bluebird")
var fs = Promise.promisifyAll(require("fs"))

function CreateSymlink(message) {
  this.name = "createSymlink"
  this.message = (message || "")
}
CreateSymlink.prototype = Object.create(Error.prototype);

function ensureSymlink(srcpath, dstpath, type){
  return fs.lstatAsync(dstpath).catch(function(e){
    // file doesn't exist create it
    throw new CreateSymlink()
  }).then(function(stats){
    // if is symbolic link unlink
    if(stats.isSymbolicLink()) return fs.unlinkAsync(dstpath).throw(new CreateSymlink())
    // if other file throw
    throw new Error("file index.js exists and isn't a symbolic link")
  }).catch(CreateSymlink, function(){
    // create file
    return fs.symlinkAsync(srcpath, dstpath, type)
  })
}

module.exports = ensureSymlink

```

**Comment by jprichardson** [comment]
I definitely see the utility in these functions. I'd accept a PR. Here's what's required:

1. Implement without promises.
2. Implement corresponding sync version.
3. Create some tests. At minimum, one for sync and one for async. More is always better.
4. Update documentation with new version.

If you're up for the task, please just start with one. Thanks.

**Comment by reggi** [comment]
@jprichardson I'm on it `ensureSymlink()` is almost done I copied the [`index.js` for ensure](https://github.com/jprichardson/node-fs-extra/tree/master/lib/ensure) and I'm following that as a template. . How should I organize the files? Rename the current `index.js` to `file.js` and have something like this:

```
/ensure
  /file.js
  /symlink.js
  /link.js
  /index.js
```

Or should they all be in that one `index.js` file?

**Comment by jprichardson** [comment]
Yeah, `symlink.js` and `link.js` is fine.

**Comment by reggi** [comment]
For node's native `symlink` there's three arguments, `srcpath`, `dstpath`, and `type`. The way I wrote it is that `fs.lstat` is ran on the `srcpath` and then I can determine the type of the file with the returns `stats.isDirectory()` an `stats.isFile()` this can supply the default type. From there we can either allow an optional type to override this, or not include it at all as an argument. What do you think @jprichardson Should we add this functionality, add it in optionally, or follow the node spec?

**Comment by reggi** [comment]
Also should the `mkdirs` be created if the `symlink` operation itself throws an error. In worst case scenario `dirs get made` and the `symlink` doesn't because either the source is missing or the destination exists. Should I check both cases before making dirs? Or is it not that important?

**Comment by reggi** [comment]
One last question is should the paths or at least srcpath be automatically `path.resolve`d? Symlinks aren't created property if a relative srcpath is used.

http://stackoverflow.com/questions/31717180/creating-broken-symlink/31717329#31717329

**Comment by jprichardson** [comment]
> For node's native symlink there's three arguments, srcpath, dstpath, and type. The way I wrote it is that fs.lstat is ran on the srcpath and then I can determine the type of the file with the returns stats.isDirectory() an stats.isFile() if not it throws (source path is not file or directory) this can supply the default type which in node's native case is just file. From there we can either allow an optional type to override this, or not include it at all as an argument. What do you think @jprichardson Should we add this functionality, add it in optionally, or follow the node spec?

Excellent question. I really like the idea of detection and with added option to override. I'd love this, but that does mean more tests. For the sake of simplicity and just getting it shipped and done, it may be best to just have the option (node spec). It depends how much work you want to do :)

> Also should the mkdirs be created if the symlink operation itself throws an error. In worst case scenario dirs get made and the symlink doesn't because either the source is missing or the destination exists. Should I check both cases before making dirs? Or is it not that important?

The function should have minimal side effects has possible. So, if the there's a symlink error, the directories should not be created. Should be a test for this :)

> One last question is should the paths or at least srcpath be automatically resolved (made into an absolute path) with path.resolve? Symlinks aren't created property if a relative srcpath is used.

I definitely think that the paths should be resolved. People that intentionally want to create broken symlinks (maybe for testing) wouldn't use this method.

Ouch, all of this adds a lot of tests :) Better we be comprehensive with as many tests as possible. Thanks for your help on this!

**Comment by reggi** [comment]
Thanks for all this @jprichardson, last question is what are your thoughts on adding deps to the project? I want to use [argx](https://github.com/okunishinishi/node-argx), and [async](https://github.com/caolan/async). Are you against this?

**Comment by jprichardson** [comment]
> Thanks for all this @jprichardson, last question is what are your thoughts on adding deps to the project? I want to use argx, and async. Are you against this?

I'm against it at the moment for this library. I'm sure long-term, I'll break this library up. But at the moment, my major focus is getting to `1.0` with the dependencies that already exist. What's your use case for `async` in this specific situation?

**Comment by reggi** [comment]
No need to use them, I can manage without. Thanks for expressing your concerns.

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-fs-extra/tree/0.23.0
