### ISSUE TITLE
ouputJson not formatted out of the box

### ISSUE THREAD

**Issue by charlierudolph** [jprichardson/node-fs-extra#163]
With the latest version of `fs-extra` ~~writeJson~~ outputJson and ~~writeJsonSync~~ outputJsonSync write json with no spaces by default.

**Comment by charlierudolph** [comment]
Previously the default had been 2 spaces and looking at the code it appears that was still the intent

**Comment by jprichardson** [comment]
Run this code:

```js
var fs = require('fs-extra')
fs.writeJsonSync('./blah.json', {msg: 'hello'})
console.log(fs.readFileSync('./blah.json', 'utf8'))
```

What's the output that you get?

**Comment by charlierudolph** [comment]
Auhh sorry the problem is actually only `outputJson` and `outputJsonSync`.

**Comment by donaldpipowitch** [comment]
I can confirm this. `writeJson` will be formatted, `outputJson` not.

**Comment by jprichardson** [comment]
Thanks for the report. Sorry it took so long to fix.
