### ISSUE TITLE
Feature Request: ensureFile to take optional argument for file content

### ISSUE THREAD

**Issue by reggi** [jprichardson/node-fs-extra#164]
What are thoughts on `ensureFile` also being able to take the string argument for file content. So if I run this:

```
fse.ensureFileSync("./tmp/paths/do/not/exist/readme.md", "#document)
```

The file `readme.md` is created with ensured dirs `/tmp/paths/do/not/exist/` with the content `#document`.

**Comment by reggi** [comment]
It's only a couple of lines to add this functionality. Keeping this here for safe keeping:

```javascript
var path = require('path')
var fs = require('graceful-fs')
var mkdir = require('../mkdirs')

function createFile (file, content, callback) {
  callback = (typeof content === 'function') ? content : callback
  content = (typeof content === 'function') ? '' : content

  function makeFile () {
    fs.writeFile(file, content, function (err) {
      if (err) return callback(err)
      callback()
    })
  }

  fs.exists(file, function (fileExists) {
    if (fileExists) return callback()
    var dir = path.dirname(file)
    fs.exists(dir, function (dirExists) {
      if (dirExists) return makeFile()
      mkdir.mkdirs(dir, function (err) {
        if (err) return callback(err)
        makeFile()
      })
    })
  })
}

function createFileSync (file, content) {
  content = (typeof content === 'function') ? '' : content

  if (fs.existsSync(file)) return

  var dir = path.dirname(file)
  if (!fs.existsSync(dir)) {
    mkdir.mkdirsSync(dir)
  }

  fs.writeFileSync(file, content)
}

module.exports = {
  createFile: createFile,
  createFileSync: createFileSync,
  // alias
  ensureFile: createFile,
  ensureFileSync: createFileSync
}
```

**Comment by jprichardson** [comment]
I'd support it. But I'd like the second parameter to be an object and the object parameter `contents` would be used to denote the contents.

Behavior:

1. If `contents` is not specified, the method just verifies that the file exists. If not, it creates it.
2. If `contents` is specified, it verifies that the file exists, and overwrites the existing content with `contents`. If file does not exist, just create file with new contents.
3. `contents` should allow either `string` or `buffer`.

Thoughts?

**Comment by reggi** [comment]
This is great feedback @jprichardson thanks! Here are some of my thoughts.

The current behavior of ensure should "ensure that the file exists" and do all it can to abide by the `If the file, dir, symlink, link already exists, it is NOT MODIFIED.` motto.

What you propose in adding an argument object endangers this motto. In order for people to feel secure using these functions (with past, present, and future use they) should never turn back on the motto.

My reasons against a object with contents argument are as follows:

1. It contradicts the motto of `ensure` to "ensure that the file exists"
2. It breaks the argument nodejs spec that we abide by and that every knows. Meaning the arguments for the function you created above break on the complimentary native node function, which makes it less drop-inable.

I've been thinking about about overwriting when it comes to `ensureLink` and `ensureSymlink` as they do not overwrite existing `links` and `symlinks`. Errors are thrown if they already exist. I created these functions with the `ensure` motto in mind, even though I probably should ensure that the symlinks and links are to the files that I want.

I'd like to see a new set of functions with their own motto. My proposal is the new keyword `affirm`, as in "affirm that the file exists, and content is as supplied" with the label `If the file, dir, symlink, link already exists, it is MODIFIED.`

With my approach it would lessen the chances that someone would accidentally overwrite something when they didn't intend to because it would not depend on variable arguments.

I'm flexable on the keyword for `affirm`, I think it's good because it sounds more menacing then `ensure`.

```
| existing files         | function           | arguments                      | current code expected                                                        | comments                                                                                                  |
|------------------------|--------------------|--------------------------------|------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------|
|                        | fs.writeFileSync   | ["missing-dir/foo.txt", "foo"] | err.message -> ENOENT: no such file or directory, open 'missing-dir/foo.txt' |                                                                                                           |
|                        | fs.writeFileSync   | ["foo.txt", "foo"]             | created file: ["foo.txt", "foo"]                                             |                                                                                                           |
| [["foo.txt", "start"]] | fs.writeFileSync   | ["foo.txt", "foo"]             | overwritten file: ["foo.txt", "foo"]                                         |                                                                                                           |
|                        | fs.writeFileSync   | ["missing-dir/foo.txt"]        | err.message -> ENOENT: no such file or directory, open 'missing-dir/foo.txt' |                                                                                                           |
|                        | fs.writeFileSync   | ["foo.txt"]                    | created file: ["foo.txt", "undefined"]                                       |                                                                                                           |
| [["foo.txt", "start"]] | fs.writeFileSync   | ["foo.txt"]                    | overwritten file: ["foo.txt", "undefined"]                                   |                                                                                                           |
|                        | fse.ensureFileSync | ["missing-dir/foo.txt", "foo"] | created file: ["missing-dir/foo.txt", ""]                                    | doesn't fit node spec beacuse doesn't create file with contents "foo" (and because it creates dirs)       |
|                        | fse.ensureFileSync | ["foo.txt", "foo"]             | created file: ["foo.txt", ""]                                                | doesn't fit node spec beacuse doesn't create file with contents "foo"                                     |
| [["foo.txt", "start"]] | fse.ensureFileSync | ["foo.txt", "foo"]             | null                                                                         | doesn't fit node spec beacuse doesn't update existing contents with "foo"                                 |
|                        | fse.ensureFileSync | ["missing-dir/foo.txt"]        | created file: ["missing-dir/foo.txt": ""]                                    | doesn't fit node spec beacuse doesn't create file with contents "undefined" (and because it creates dirs) |
|                        | fse.ensureFileSync | ["foo.txt"]                    | created file: ["foo.txt", ""]                                                | doesn't fit node spec beacuse doesn't create file with contents "undefined"                               |
| [["foo.txt", "start"]] | fse.ensureFileSync | ["foo.txt"]                    | overwritten file: ["foo.txt", ""]                                            | doesn't fit node spec beacuse doesn't update existing contents with "undefined"                           |
|                        | fse.affirmFileSync | ["missing-dir/foo.txt", "foo"] | created file: ["missing-dir/foo.txt", "foo"]                                 |                                                                                                           |
|                        | fse.affirmFileSync | ["foo.txt", "foo"]             | created file: ["foo.txt", "foo"]                                             |                                                                                                           |
| [["foo.txt", "start"]] | fse.affirmFileSync | ["foo.txt", "foo"]             | overwritten file: ["foo.txt", "foo"]                                         |                                                                                                           |
|                        | fse.affirmFileSync | ["missing-dir/foo.txt"]        | created file: ["missing-dir/foo.txt": ""]                                    |                                                                                                           |
|                        | fse.affirmFileSync | ["foo.txt"]                    | created file: ["foo.txt", ""]                                                |                                                                                                           |
| [["foo.txt", "start"]] | fse.affirmFileSync | ["foo.txt"]                    | overwritten file: ["foo.txt", ""]                                            |                                                                                                           |
```

> This table is easier to view wrapped in a code block.

As you can see the proposed `affirmFile` function is akin to the behavior of `fs.writeFile`.

Thoughts?

**Comment by reggi** [comment]
With this said, there's no reason why we can't add the non-object parameter for `ensureFIle` content for, so that if the file doesn't exist it is created with that content.

**Comment by reggi** [comment]
One easy way to do this on our end is have a function factory where the internal function has the `overwrite` argument, and we build out the `affirm` / ensure overwrite function from within the same codebase when exporting the module functions.

**Comment by reggi** [comment]
I'm just realizing that `ensure` never throws an error if the destination file exists. I need to take this into account for `ensureLink` and `ensureSymlink`, which is against the native behavior.

**Comment by reggi** [comment]
When it comes to using `ensure` I like the ability to control flow & know success failure. Especially because it's all so easy when I wrap `fs-extra` in bluebird's `promisifyAll()`. I'm thinking that ensure should always throw an error if no action is taken. That way the user has some idea if the file was created for the first time or not. Meaning lines `09`, `12`, and `20` for `ensureFile` should all throw instead of doing nothing. Perhaps this is another keyword.

**Comment by reggi** [comment]
I'm breaking all of these operations down to these three rules.

`ensure` -> ensures a file exists, doesn't overwrite destination or throw if destination exists
`???` or `ensureWarning` -> ensures a file exists, doesn't overwrite destination, throws if dest exists
`affirm` or `ensureOverwrite` -> ensures a file exists, with specific contents, overwrites

**Comment by reggi** [comment]
Here's some behavior for each.

```javascript
fs.writeFileSync("foo.txt", "original")
fse.ensureFileSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // -> "original"
```

```javascript
fs.writeFileSync("foo.txt", "original")
fse.ensureOverwriteFileSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // -> "foo"
```

```javascript
fs.writeFileSync("foo.txt", "original")
fse.ensureWarnSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // throws -> File already exists
```

```javascript
fse.ensureFileSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // -> "foo"
```

```javascript
fse.ensureOverwriteFileSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // -> "foo"
```

```javascript
fse.ensureWarnSync("foo.txt", "foo")
fs.readFileSync("foo.txt", "utf8") // -> "foo"
```

**Comment by jprichardson** [comment]
A lot of great thoughts here...

> The current behavior of ensure should "ensure that the file exists" and do all it can to abide by the If the file, dir, symlink, link already exists, it is NOT MODIFIED. motto.

I'm not sure that I agree with this if a `contents` parameter is added. The reason that thought that a `contents` field to an options object was a good idea, is because I wanted to add `mode` and `owner` eventually. I was thinking then that `ensureFile()` would then take on idempotency. 

That is, the first parameter is verifying that the file exists (this is required), if the second parameter is passed (options object), then the method ensures that the file has these properties. 

Does this change your perspective at all?

Maybe a parameter `force` (or maybe named `overwrite`) should be added.... but then should `overwrite` be the default?

Maybe it could work like this, assuming maintaining existing behavior:

1. File does not exist, create it, set mode, and contents:

```js
fs.ensureFileSync('/this/file/does/not/exist.txt', { contents: 'hello', mode: '0666' })
```

2. File does exist, do nothing:

```js
fs.ensureFileSync('/this/file/does/exist.txt', { contents: 'hello', mode: '0666' })
```

3. File does exist, overwrite is true, set mode and contents:

```js
fs.ensureFileSync('/this/file/does/exist.txt', { contents: 'hello', mode: '0666', overwrite: true })
```

Thoughts?

**Comment by reggi** [comment]
I'm not 100% sold on the object argument, because it's not something that I need. What I do need is writing a file and creating recursive dirs, and I need to set the file content. 

What I recommend is adding string / buffer support for compatibility with native node and down the line adding support by checking if the second arg is an object supporting all the features you're talking about.

**Comment by RyanZim** [comment]
@jprichardson Hang on, how is this different from [outputFile()](https://github.com/jprichardson/node-fs-extra#outputfilefile-data-options-callback)?

**Comment by jprichardson** [comment]
> @jprichardson Hang on, how is this different from outputFile()?

I don't think that it is, other than semantics? Not sure. Thoughts @reggi?

**Comment by RyanZim** [comment]
Closing for lack of action.
