### ISSUE TITLE
rename `clobber` flags to `overwrite`

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#172]

**Comment by RyanZim** [comment]
@jprichardson Is this still in the sights for v1.0.0?

**Comment by jprichardson** [comment]
`overwrite` seems more intuitive as a name. But we can push this off to 2.0.

**Comment by RyanZim** [comment]
I have this done on a branch, will rebase & open a PR when https://github.com/jprichardson/node-fs-extra/pull/330 is merged.

**Comment by jprichardson** [comment]
Thanks! Does `clobber` still work? If not, do you think we should? If so, do you think we should show a deprecation message?

**Comment by RyanZim** [comment]
@jprichardson Currently `clobber` works without a deprecation message. Personally, I wouldn't add a deprecation message yet. Maybe later?

**Comment by jprichardson** [comment]
> Currently clobber works without a deprecation message. 

"Currently' as defined by after 2.0 released with `clobber` renamed to `overwrite`? I'm just trying to limit people's code breaking prematurely if we don't have to.

**Comment by RyanZim** [comment]
> "Currently' as defined by after 2.0 released with clobber renamed to overwrite?

Correct! :100: I should have said "as Currently implemented in my branch".

**Comment by RyanZim** [comment]
Fixed by https://github.com/jprichardson/node-fs-extra/pull/333, will be released in v2.
