### ISSUE TITLE
Feature Request: writeJson should mkdirs

### ISSUE THREAD

**Issue by reggi** [jprichardson/node-fs-extra#173]
Pretty self explanatory, I think the `writeJson` functions show mkdirs if they don't exist.

**Comment by jprichardson** [comment]
`outputJson()` takes care of this.

https://github.com/jprichardson/node-fs-extra#outputjsonfile-data-options-callback 

But maybe I should axe `outputFile()` and `outputJson()`... and merge in `outputFile()` with `ensureFile()`.... hmm.

**Comment by jprichardson** [comment]
Closing as `outputJson()` takes care of this. Please let me know if I missed something.
