### ISSUE TITLE
[Feature Request].moveSync support

### ISSUE THREAD

**Issue by Jayin** [jprichardson/node-fs-extra#175]

**Comment by jprichardson** [comment]
Would love this. Due to other priorities in this project (see other issues), it almost certainly won't happen pre-1.0 unless someone submits a PR.

**Comment by jprichardson** [comment]
I'd really like to see this, but it's not going to happen pre-1.0. Like I said, I'd love to see a PR for this. Tagged with `future` to revisit this later.

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/381
