### ISSUE TITLE
createOutputStream doesn't emit 'end' event

### ISSUE THREAD

**Issue by ORESoftware** [jprichardson/node-fs-extra#176]
how can I listen for an 'end' or 'completion' event with

```javascript
fse.createOutputStream
```

something like so:

```javascript
  .pipe(fse.createOutputStream(fullPathOutput)).on('end', function (msg) {
            cb(null, msg);
      });
```

I need to be able to listen to such an event, thanks

**Comment by ORESoftware** [comment]
nevermind, it emits a 'close' event instead of 'end', great, that works for me

**Comment by jprichardson** [comment]
It's important to remember that `createOutputStream` returns the same result as `fs.createWriteStream()` i.e. they both return a `WriteStream`. There's just some hackery involved on the creation.
