### ISSUE TITLE
fix `remove()` & `move()` wildcards (introduced by rimraf)

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#177]

**Comment by jprichardson** [comment]
Also on `move`.

**Comment by jprichardson** [comment]
https://github.com/isaacs/rimraf/commit/04f1a13a72d69f010e59e6e04e66e226102e7d4b

**Comment by FredyC** [comment]
@jprichardson Just little side node here, please mention in docs that those methods are actually a wrapper around `rimraf`. I was just looking if I can use globbing pattern there and had to dive into code to find out about this. Thanks for the module either way, I like to have things tucked together like this.

**Comment by siyb** [comment]
Somehow, this does not seem to work any more (using Version 1.0.0):

 fs.remove(storagePath, err => {
  if(err)...;
  console.log('REMOVED', storagePath)
});

output:

REMOVED /tmp/myproject/test/unit/*

$ ls -l /tmp/myproject/test/unit/|wc -l
10

**Comment by RyanZim** [comment]
This issue should be closed, it is fixed.

@siyb fs-extra does not support globbing. It did support it for `remove` and `move`, but this was inconsistent with the rest of the API, so we removed it in v1.0.0. https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#100--2016-11-01

**Comment by jprichardson** [comment]
@siyb what happened is that `fs-extra` never supported globbing nor was it ever documented. `rimraf` came along and introduced globbing. `fs-extra` will support globbing at some point, but we need it to be consistent across the entire API.

If this is something you'd be willing to help us with, we'd love to have your help.

**Comment by jacobq** [comment]
> `fs-extra` will support globbing at some point, ...

Is it available? Where can one track the status of this?

**Comment by RyanZim** [comment]
Yes.
