### ISSUE TITLE
Include opendir

### ISSUE THREAD

**Issue by piranna** [jprichardson/node-fs-extra#179]
Implement [opendir()](http://man7.org/linux/man-pages/man3/opendir.3.html) the same way that it's include `open()``on the fs module. This allow to have a fixed reference to the directory.

**Comment by jprichardson** [comment]
Why? It's not clear to me what sort of benefit this provides.

**Comment by piranna** [comment]
Calling `open()` left the file open and return a file descriptor that can be used as reference, but there's no way to do the same with directories since `fs` API only allow to read their content, releasing it after that. I need this to have a reference to the underlying directory on an overlay filesystem when mounting it directly over the directory of the lower layer. Obviously, not only would be needed `opendir()` but also `closedir()` and `readdir()` methods...

**Comment by saghul** [comment]
It's used for listing large directories in a streaming fashion. Support for it is pending review in libuv https://github.com/libuv/libuv/pull/416

**Comment by jprichardson** [comment]
Wouldn't this require native Node modules?

**Comment by piranna** [comment]
> Wouldn't this require native Node modules?

If as @saghul says this is being considered on libuv, no.

**Comment by jprichardson** [comment]
> If as @saghul says this is being considered on libuv, no.

Even if it's in libuv, it would still have to be exposed in Node.js. 

I'm closing this for now. It's out of scope pre-1.0 and my top priority is to get `fs-extra` to 1.0 - I have a long way to go yet.
