### ISSUE TITLE
CLI equivalent for fs-extra

### ISSUE THREAD

**Issue by Deele** [jprichardson/node-fs-extra#184]
Is there an CLI equivalent for fs-extra?

I would like to create npm build scripts that are platform independent, and fs-extra seems to have very nice set of methods, but I would like to use them from CLI.

It could be like a single script:
```
node fs-cli copy source/dir target/dir
```
multiple scripts
```
node fs-copy source/dir target/dir
```
or even multiple binaries
```
fs-copy source/dir target/dir
```

**Comment by jprichardson** [comment]
I don't know of any. But it'd be cool to see someone make it. If you do, please let me know :)

**Comment by Deele** [comment]
@jprichardson Have a look on my first implementation of copy command and please, share your thoughts https://github.com/Deele/node-fs-extra-cli

**Comment by jprichardson** [comment]
Nice :) One thing to note, the option `clobber` will be renamed to `overwrite`. So you may want to change that on your end. When you implement both move and delete, feel free to make a PR and update this section: https://github.com/jprichardson/node-fs-extra#misc
