### ISSUE TITLE
Doesn't work on NodeJS v4.x

### ISSUE THREAD

**Issue by cheahkhing** [jprichardson/node-fs-extra#185]
After i upgrade my node to latest version: v4.2.x
This module will not work properly. I used the copy, it doesn't copy the files properly. all files are empty with zero byte.

**Comment by jprichardson** [comment]
Which operating system are you using?

**Comment by cheahkhing** [comment]
it's windows8.1

**Comment by jprichardson** [comment]
I'm unable to reproduce. Do you have any code that can reliably reproduce the error?

**Comment by DavidBabel** [comment]
Same issue on debian jessie

**Comment by jprichardson** [comment]
I'm gonna need more information to reproduce. Please reopen when you can post more info. Thanks.
