### ISSUE TITLE
move.test failing on windows platform

### ISSUE THREAD

**Issue by bartland** [jprichardson/node-fs-extra#188]
There are 7 tests which fail on windows but work on Linux.
This is because when git fetches the test data files it converts the line endings from \n to \r\n (since core.autocrlf is typically true with git on windows).

This fails on Windows but succeeds elsewhere:
```
        assert.ifError(err)
        assert.strictEqual(contents, 'sonic the hedgehog\n')
```
I believe the best way to fix this is to use regex:
```
        var expected = /^sonic the hedgehog\r?\n$/
        assert.ifError(err)
        assert.ok(contents.match(expected), contents + ' match ' + expected)
```

**Comment by jprichardson** [comment]
Interesting. It's not failing on the Windows Appveyor tests: https://ci.appveyor.com/project/jprichardson/node-fs-extra/branch/master Why do you think that is? Either way, I'm fine with changing it. Really, could just trim the line ending, as it's not that important for that particular test.

**Comment by bartland** [comment]
Probably because Appveyor is preserving the repository line endings. I think regex is a bit cleaner as it doesn't modify data. I'll submit a PR for this shortly.
