### ISSUE TITLE
How to copy symlinks to target as normal folders

### ISSUE THREAD

**Issue by screendriver** [jprichardson/node-fs-extra#191]
Can I set the `-L` option like in the unix command `cp`?

From the man page:

> ‘-L’ ,‘--dereference’ - Follow symbolic links when copying from them. With this option, cp
> cannot create a symbolic link. For example, a symlink (to regular file) in the source tree will be
> copied to a regular file in the destination tree. 

See also here at [superuser](http://superuser.com/questions/216919/how-to-copy-symlinks-to-target-as-normal-folders)

**Comment by jprichardson** [comment]
Try setting `deference` to `true`:

```js
fs.copy(src, dest, { dereference: true }, callback)
```

Let me know if that works. I'm gonna leave this open, as that should be documented.

**Comment by screendriver** [comment]
Thank you, it's working :+1:

**Comment by jhnns** [comment]
Thx @jprichardson. Just being curious: why is this option not listed in the README?

**Comment by jprichardson** [comment]
@jhnns it's because it doesn't exist in `copySync`. It should be implemented in `copySync` as well.

**Comment by jhnns** [comment]
Sounds reasonable :+1:

**Comment by jprichardson** [comment]
Implemented in https://github.com/jprichardson/node-fs-extra/pull/235
