### ISSUE TITLE
Remove fs.createOutputStream()

### ISSUE THREAD

**Issue by jprichardson** [jprichardson/node-fs-extra#192]
Recently I was using `fs.createOutputStream()` in https://github.com/jprichardson/node-cfs/blob/0.5.0/index.js#L30 and I was getting some weird errors. The problem is that `fs.createOutputStream` is a hack that is NOT heavily tested. It doesn't seem to belong in this library. 

I will almost certainly create a separate module for it and remove it entirely from `fs-extra`.

**Comment by donaldpipowitch** [comment]
Was the only reason for this removal, because it was not heavily tested? :( Sad to see this go.

**Comment by jprichardson** [comment]
@donaldpipowitch sorry :( Yeah, I felt that because it has weird edge cases on different Node versions, that it may hold the entire library back. So I thought it was best to remove it. Rest assured though, it's still alive, just in a separate module: https://github.com/jprichardson/create-output-stream
