### ISSUE TITLE
`fs.copy` fails silently if source file is /dev/null

### ISSUE THREAD

**Issue by raybellis** [jprichardson/node-fs-extra#193]
Using bluebird with `fs.copyAsync`, my program finished with no error despite a `.catch(console.error)` when I tried to copy `/dev/null` onto a file.

**Comment by jprichardson** [comment]
Do you get the same problem with just `fs.copy`?

**Comment by raybellis** [comment]
Let me try that and see...

**Comment by raybellis** [comment]
It appears to fail, silently, without creating the file:

    var fs = require('fs-extra');

    fs.copy('/dev/null', '/tmp/foo', function(err) {
        console.log(err);
    });

**Comment by jprichardson** [comment]
Thanks. Verified. Just hangs on OS X 10.11 / Node 4.2.1. 

Surely this is the offending line: https://github.com/jprichardson/node-fs-extra/blob/0.26.2/lib/copy/copy.js#L15

Ideas on a practical solution? I'd hate as something could be symlinked to /dev/null right? Surely others have experienced this... a cursory Google search didn't return much.

Thanks for your help.

**Comment by jprichardson** [comment]
Nope, this is the offending line:

https://github.com/jprichardson/node-fs-extra/blob/0.26.2/lib/copy/copy.js#L24

Is there something about the `stats` of `/dev/null` that I could use to reliably detect it?

**Comment by raybellis** [comment]
No, it's not there, either - it's the `getStats()` function in `lib/copy/ncp.js` which doesn't have a branch to take if the given file isn't either a directory, a plain file, or a symlink.

**Comment by raybellis** [comment]
I think the check in that function for `stats.isFile()` needs the addition of:

    || stats.isBlockDevice() || stats.isCharacterDevice()

**Comment by jprichardson** [comment]
I would love a pull request :) I have a test here: https://github.com/jprichardson/node-fs-extra/commit/631ed20f7bd8a817346073efa59f93f19c77da48

**Comment by jprichardson** [comment]
Updated test. Thanks again for your help, it's much appreciated!
