### ISSUE TITLE
How to override with outputFile?

### ISSUE THREAD

**Issue by brunano21** [jprichardson/node-fs-extra#195]
I'm using the `outputFile` function but I would like to override the file if it already exists. However, seems it is not possible to pass an `option` to the function.
How to accomplish that thus?

Edit: Even if it should override an existing file, this doesnt happen.

**Comment by triccardi-systran** [comment]
By default `outputFile` does overwrite the file.
What is missing is documentation on the 3rd parameter: `options`, which seems to be forwarded down to nodejs native `fs`, where we can pass a flag, to *not* override (ie append):
`fs.outputFile('/tmp/foo', 'bar', {flag: 'a'})` will append to the `/tmp/foo` file, instead of override.

See #197.

**Comment by jprichardson** [comment]
@brunano21 as @triccardi-systran stated, the whole point of `outputFile` is to behave exactly like `writeFile` except that it creates the directory if it doesn't exist. Can you paste a snippet of what you're trying to do along with your expectations? Thanks.

**Comment by brunano21** [comment]
@jprichardson 
Hi,
my snippet is the following:
    
    function _takeScreenshot (object, action) {
        var self = this;
        var remote = self._remote;
        var path = null;
        var filename = null;

        path = "./tests-screenshots/" + self._testName + "/ref";
        filename = ("000" + (self._totalSteps - self._testSteps.length - 1)).slice(-3) + ".png";

        return remote
            .takeScreenshot()
            .then(function (data) {

                fse.ensureDirSync(path);

                fse.outputFile(path + "/" + filename, data);
                return remote;
            });
    };

Unfortunately the screenshot is saved only if the file does not exist. If it does, it's not overwritten.

**Comment by jprichardson** [comment]
If you want this snippet that you have to work, you must either do the following:

1. Use the sync version of `fse.outputFileSync()`.
2. Wrap the async version of `fse.outputFile()` into a promise.
3. Use `fs-extra-promise`: https://github.com/overlookmotel/fs-extra-promise

Demonstrating 1:

```js
...

return remote
  .takeScreenshot()
  .then(function (data) {
    fse.outputFileSync(path + "/" + filename, data)
      return remote;
    });
```

Demonstrating 2:

```js
...

return remote
  .takeScreenshot()
  .then(function (data) {
    return new Promise(function (resolve, reject) {
      fse.outputFile(path + "/" + filename, data, function(err) {
         if (err) return reject(err)
         else resolve(remote)
      })
    })
```

Demonstrating 3:

```js
...

return remote
  .takeScreenshot()
  .then(function (data) {
      return fse.outputFileAsync(path + "/" + filename, data)
    })
```

Hope that helps.
