### ISSUE TITLE
Missing documentation for `outputFile` `options` 3rd parameter

### ISSUE THREAD

**Issue by triccardi-systran** [jprichardson/node-fs-extra#197]
The 3rd parameter of `outputFile` seems to be forwarded down to nodejs native `fs` `options`: this is not documented.
It could be used to append instead of overwrite for example.

Maybe other similar functions have the same issue.

(Also, the code makes as default value for option a string: 'utf-8', instead of an object: this usage is not documented for nodejs 0.10 & 0.12).

**Comment by jprichardson** [comment]
Thanks for stopping by and letting me know! I'm sorry that it took so long for me to address this.
