### ISSUE TITLE
handle copying between identical files

### ISSUE THREAD

**Issue by chinesedfan** [jprichardson/node-fs-extra#198]
I hope this module can be as clever as `cp`. It should recognize copying between identical files and do nothing.

Now, v0.26.2, neither `copy` nor `copySync` can handle these cases correctly.
- If `src` and `dst` are the same file
  - It opens a read stream first, and then a write stream, which results in the file becomes empty.
- If `src` is symbolic link and points to `dst`
  - By default, option `clobber` is `true`, so that `dst` will be removed, which means the real file is removed. If `clobber` is `false`, the file becomes empty.
- If `dst` is symbolic link and points to `src`
  - Similar to the previous case, `dst` is removed and a new file is created, then the link is not existed any more. Or the file becomes empty.

I have added corresponding test cases in [my branch](https://github.com/chinesedfan/node-fs-extra/tree/copy_identical).

**Comment by jprichardson** [comment]
Thanks for your interest. These are great suggestions. Would you be willing to look at the `cp` code and implement these changes? It would be of a huge help and really add a lot of value to the module. Even if we take one case at a time, that would be a wonderful addition.

Thank you!

**Comment by chinesedfan** [comment]
OK. I will try to find some time to implement this feature.

**Comment by jprichardson** [comment]
I think if you start with just one, that'd be a big win. You could pick the one that is the most important to you and we could start with that?

**Comment by RyanZim** [comment]
Fixed in 5.0.0 :tada:
