### ISSUE TITLE
'copySync' doesn't work in sync

### ISSUE THREAD

**Issue by yanyu0517** [jprichardson/node-fs-extra#200]
My file directory like this:
```
/config
  -mockConfig.json
```

My code is 
```
var src = path.join(__dirname, '../config'),
        destPath = dest || process.cwd();
// copy folder
fse.copySync(src, destPath + '/config');
console.log('copy ' + src + ' to ' + destPath + '/config')
```

And console.log will be triggered before <config>folder copy

**Comment by jprichardson** [comment]
Please rewrite your snippet in a reproducible manner. Could you use absolute directory paths and a temp folder like `/tmp`? This way I can reproduce the issue on my end. Thanks :)

**Comment by yanyu0517** [comment]
I have fixed it, it was a mistake!
