### ISSUE TITLE
clobber for directories

### ISSUE THREAD

**Issue by piranna** [jprichardson/node-fs-extra#201]
Reading the code I've found `copy` (and `move`) merge the content of the directories if the destination (and any of its subfolders) exists. That's just the feature I was looking for :-D But I've noticed that there's no option to delete destination (sub-)folders to only have the files we are copying and none of the old ones, the same way the `clobber` option overwrite destination files when enabled...

**Comment by jprichardson** [comment]
This feels like maybe it'd be doing too much though. Copying shouldn't read the destination unless there is a conflict with what is being copied, right? Maybe a better solution would be that if a destination directory exists, an event is emitted allow the user to read the directory and then take action. IDK.

**Comment by piranna** [comment]
> Copying shouldn't read the destination unless there is a conflict with what is being copied, right? Maybe a better solution would be that if a destination directory exists, an event is emitted allow the user to read the directory and then take action

Why no both? :-) If a conflict on destination arises, call a `onConflict` callback so user can return what to do with it, like `overwrite`, `ignore`, `ignoreAndDelete` (source) or `abort` (and also the callback could be set to one of these values instead a function so it will be done always that way). There could be also independent callbacks for directories and files to have fine-grain control, so also the `clobber` option would be deprecated at all :-D

```Javascript
{
  onConflictDir: 'merge',
  onConflictFile: 'overwrite'
}
```

Nice, eh? :-)

**Comment by jprichardson** [comment]
It's not a bad idea, but my priority is to get to 1.0 first. We can then revisit it then :) Tagged as `future`.

**Comment by piranna** [comment]
I agree :-)
