### ISSUE TITLE
why there is not a walkSync method?

### ISSUE THREAD

**Issue by zaaack** [jprichardson/node-fs-extra#202]
Is there anyway to implement synchronized walk method?  I want to get all files in the directory and sub directories synchronized.

**Comment by jprichardson** [comment]
When you say `synchronized`, in this context it can mean different things. Are you asking a `walkSync` that calls the underlying fs.readdirSync/fs.lstatSync methods?

**Comment by zaaack** [comment]
@jprichardson  yes, that's what I mean

**Comment by jprichardson** [comment]
Sync in this case would not typically a desirable thing to do. But it should be pretty easy to implement on your end. You could use the fs-extra walk algorithm as a reference: https://github.com/jprichardson/node-klaw/blob/master/index.js
