### ISSUE TITLE
fix documents about copy/copySync

### ISSUE THREAD

**Issue by chinesedfan** [jprichardson/node-fs-extra#205]
I think these 2 methods should share the same options. But:

1. By default, `preserveTimestamps` is `false` in `copy` as the document describes, while it is `true` in `copySync.`
2. For `copy`, options `transform/dereference/limit/errs/stopOnError` are undocumented. Maybe we can refer to `ncp` in somewhere.
3. For `copySync`, options `recursive` is also undocumented.

By the way, I was addicted to something else and sorry for leaving issue #198 still open. XD.

**Comment by jprichardson** [comment]
Thanks for pointing these out.

1. That definitely needs to be fixed.
2. I purposely left some of these out of the documentation as I wasn't sure if I was willing to support them long-term or if I'd change/rename them.
3. Same here.

Thanks for bringing this issue up though, as it needs to be fixed.

**Comment by jprichardson** [comment]
Reopened as #208 doesn't solve `2.` and `3.`.

**Comment by chinesedfan** [comment]
What's your plan about 2&3?
How about just adding some words mention those options? And warn users they are not stable.

**Comment by jprichardson** [comment]
> What's your plan about 2&3?
How about just adding some words mention those options? And warn users they are not stable.

The problem is that if they're documented, despite my warnings, people will use them.

**Comment by RyanZim** [comment]
> The problem is that if they're documented, despite my warnings, people will use them. 

Good point. `copy` is long due an overhaul, and those options may change then. We'll fix the docs then.
