### ISSUE TITLE
Add `compare` suite of functions

### ISSUE THREAD

**Issue by kellyselden** [jprichardson/node-fs-extra#207]
I'm about to write a test helper that compares generated files to a fixtures folder. I already am using fs-extra, so I wondered would it be nice to have compare functions included?

Something like:
```js
compareDirsSync('tmp/my-folder', 'test/fixtures/my-folder');
```

**Comment by jprichardson** [comment]
It may be nice, but unfortunately it would add more to the scope than what I'm willing before `1.0` is released. I really appreciate your interest and posting and issue though :)

**Comment by kellyselden** [comment]
No worries. Maybe I'll make a `node-fs-extra-extra` lol.

**Comment by jprichardson** [comment]
> No worries. Maybe I'll make a node-fs-extra-extra lol.

Haha :blush:

**Comment by kellyselden** [comment]
@jprichardson I ended up making the lib if you're curious https://github.com/kellyselden/fs-equal
