### ISSUE TITLE
In Windows invalid directory name causes infinite loop in ensureDir().

### ISSUE THREAD

**Issue by vzakon** [jprichardson/node-fs-extra#209]
Example:
`require('fs-extra').ensureDir("./bad?dir", function(err) { console.log("never here!"); });`

Infinite recursion call is here:
https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/mkdirs.js#L33

**Comment by jprichardson** [comment]
Thanks for reporting. I'd like to drop my custom `mkdirp` and go back to using https://github.com/substack/node-mkdirp again, but looks like it's still affected: https://github.com/substack/node-mkdirp/issues/70
