### ISSUE TITLE
copy/copySync behave differently when copying a symbolic file

### ISSUE THREAD

**Issue by chinesedfan** [jprichardson/node-fs-extra#210]
>
man cp: Symbolic links are always followed unless the -R flag is set.

`fse.copySync` keeps the same behavior with my `cp`(OSX 10.11.1). But `fse.copy` will always not follow links unless `options.dereference` is true.

**Comment by jprichardson** [comment]
I really appreciate you pointing these issues out :+1: So, you think `dereference` should default be set to `true`?

**Comment by chinesedfan** [comment]
Not really. It only depends on whether `-R` flag is set.
```
# follow
cp srcFile dstFile
# not follow
cp -R srcFile dstFile
cp -R srcDir dstDir
```
So, when copying a file, `dereference` is true. But when copying a folder, because `-R` must be set, `dereference` is false.

Please refer to [GNU document](https://www.gnu.org/software/coreutils/manual/html_node/cp-invocation.html#cp-invocation) and check my understanding.

**Comment by jprichardson** [comment]
Was fixed in https://github.com/rjz/node-fs-extra/commit/b50515c484d04f8c97d0253dd93694e73583a3cc
