### ISSUE TITLE
Not copying all files

### ISSUE THREAD

**Issue by ryanshawty** [jprichardson/node-fs-extra#211]
Trying to copy from one directory to another e.g.

fs.copy('uploads/name/etc/', 'store/name' ...);

But it ends up copying maybe 60 out of 204. The file permissions are exactly the same for all files. I don't understand how it can copy only a few files.

**Comment by jprichardson** [comment]
Are you passing a callback? Are you using any options?

**Comment by ryanshawty** [comment]
My bad it was a previous step I had taken in decompressing a tar file. Sorry!

**Comment by jprichardson** [comment]
No problem.
