### ISSUE TITLE
Merge extfs with this repo

### ISSUE THREAD

**Issue by alvinsight** [jprichardson/node-fs-extra#213]
Hi, 

Great work on this module, it really makes file/folder manipulation a lot easier.
I found myself having to check the existence of folders quite a lot, and I found the extfs module (https://github.com/marian2js/npm-extfs) perfect for this, but this module and extfs are kind of serving the same purposes, they even have common methods.
So I was wondering if you guys would like to merge (or to accept a PR that merges) extfs with fs-extra, especially as extfs looks like it's no longer maintained (it might not need to though).
Thank you, 
Alvin

**Comment by jprichardson** [comment]
It looks like `npm-extfs` could be rewritten to depend upon `fs-extra`. I'm not interested in the methods in in `npm-extfs` though (isEmpty / getDirs()). My priority is to get fs-extra to 1.0.0.

I appreciate your interest though.

**Comment by kruncher** [comment]
I personally would like to see `isEmpty` and `isEmptySync` make it into `fs-extra`.

**Comment by RyanZim** [comment]
@kruncher With fs-extra v3, you can just do:
```js
fs.readdir('dir').then(arr => Promise.all(arr.map(path => fs.pathExists(path)))
```

**Comment by kruncher** [comment]
@RyanZim "just" hehe, that seems quite verbose and prone to error.

I'd rather just do this:
```javascript
if (fs.isEmptySync(path)) {
    console.log("The specified directory is empty!");
}
```

**Comment by RyanZim** [comment]
You can open a new issue requesting this for reconsideration, can't promise anything.
