### ISSUE TITLE
Suspicious behavior of fs.existsSync

### ISSUE THREAD

**Issue by yetanotherusernamebecausegithubisbugged** [jprichardson/node-fs-extra#223]
I has ran into an unusual issue with fs.existsSync function. I think it's a bug but curious would you share this opinion or not (and would you fix it in fs-extra if you do?). The way to reproduce:
```bash
$ pwd
/home/me/tst
$ npm install fusejs
...
$ mkdir fusetest
$ cd fusetest
$ mkdir mnt
$ node ../node_modules/fusejs/examples/example_main.js mnt -ofsname=examplefs -orw -d
...
[Ctrl+C]^C
$ ls -l
ls: cannot access mnt: Transport endpoint is not connected
total 0
d????????? ? ? ? ?              ? mnt
$ mkdir mnt
mkdir: cannot create directory ‘mnt’: File exists
$ echo -e "var fs = require('fs-extra')\nconsole.dir(fs.existsSync('mnt'))" > testfuse.js
$ node testfuse.js
false
```
The node says that ./mnt doesn't exists when it actually does although in the broken state.

**Comment by jprichardson** [comment]
Sorry, I'm not sure. You may want to file an issue at the Node.js repo since `fs-extra` does not modify `existsSync()`.
