### ISSUE TITLE
Moving to the current directory

### ISSUE THREAD

**Issue by omarfouad** [jprichardson/node-fs-extra#226]
I would like to move some files and folders from a nested directory into the "current" directory (or the directory from where I'm calling the node CLI command). So I tried the following written inside `bin/cspweb-ui.js`:

``` js
var fs = require('fs-extra')

fs.move('./node_modules/@mominari/cspweb-ui/', './', function(err) {
  console.log(err)
})
```

but I'm getting the following error:

``` bash
{ [Error: EEXIST: file already exists, link './node_modules/@mominari/cspweb-ui/' -> './']
  errno: -17,
  code: 'EEXIST',
  syscall: 'link',
  path: './node_modules/@mominari/cspweb-ui/',
  dest: './' }
```

Any ideas?

Thanks.

**Comment by jprichardson** [comment]
For context, what is the "current" directory?

**Comment by omarfouad** [comment]
It's the directory from which I'm executing the CLI command.

**Comment by RyanZim** [comment]
@omarfouad Have you tried `.`? Not sure; @jprichardson ?

**Comment by RyanZim** [comment]
Going to close for lack of action.

**Comment by zhangmingze** [comment]
I met the same problem when move a existed directory, it's happened

**Comment by RyanZim** [comment]
@zhangmingze Please open a new issue with a reduced test case.
