### ISSUE TITLE
Uncatchable errors when there are invalid arguments

### ISSUE THREAD

**Issue by enneid** [jprichardson/node-fs-extra#227]
Try this code:

```
 fse = require('fs-extra')
try{
fse.move(null, null, (err, data) => {
console.log("Errr", err)})
}catch(err){
console.log("Err", err)
}
```

it will crash without chance to catch error.

**Comment by jprichardson** [comment]
So you're saying, you don't ever see "Errr"?

**Comment by enneid** [comment]
yes, try this code in pure  node console. In real application this will throw and ends brutally app

**Comment by RyanZim** [comment]
This is at https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/mkdirs.js#L32.

`fs` throws a TypeError if `path` is not a string. On one hand, I see @enneid's point, but this is a case where I think we should follow node.js' lead and throw an error.

Passing `null` is a programmer error, not a runtime error. If you have a unique case where this can be a runtime error, you will have to type-check your arguments before passing them to `fs-extra`.

CC: @jprichardson

**Comment by jprichardson** [comment]
> fs throws a TypeError if path is not a string. On one hand, I see @enneid's point, but this is a case where I think we should follow node.js' lead and throw an error.

👍

**Comment by enneid** [comment]
fs throws a TypeError if path is not a string. However in basic functionality you can easly catch this error!


`
 fs = require('fs')
try{
fs.link(null, null, (err, data) => {
console.log("Errr", err)}) 
}catch(err){
console.log("Crash", err) // will emit Crash [TypeError: dest path must be a string]
}
`
code crash on fs.link in move/index.js.  If you call wrap  each try{} catch{} atomic async method (like fs.link) you will not given any of uncachted error., you can handle error it **in async pattern (by callback)!**. If you will not provide this protection,  on low level, there is no chance to catch it on high level

**Comment by RyanZim** [comment]
@jprichardson ? 

I would tend to argue that in this case you should still type-check it yourself.

**Comment by enneid** [comment]
I think whole fs library  throw  only catchable errors. 
Validation issue is not on this level.  Library must  not loose fully context and throw error outside app

**Comment by jprichardson** [comment]
@enneid interested in submitting a PR?

**Comment by enneid** [comment]
I can't say when I may make pr , but ok
