### ISSUE TITLE
Adding read/write/output functions for YAML

### ISSUE THREAD

**Issue by IvanGoncharov** [jprichardson/node-fs-extra#231]
You library is very cool and helpful but my main format is YAML.
And this force me to create my own wrapper around read/write/output for raw files.
I use [js-yaml](https://github.com/nodeca/js-yaml) lib for all YAML related operations.

YAML became very popular in last few years.
If you look on GitHub you will find [22M](https://github.com/search?utf8=%E2%9C%93&q=language%3AYAML+filename%3A*.yml+filename%3A*.yaml&type=Code&ref=searchresults) of YAML files and it's already comparable with [99M](https://github.com/search?utf8=%E2%9C%93&q=language%3AJSON+filename%3A*.json&type=Code&ref=searchresults) JSON files.
Such functionality will be useful for many developers.

If needed I can submit PR request.

**Comment by jprichardson** [comment]
> You library is very cool and helpful but my main format is YAML.

Thanks. If people want to use YAML though, they can use `js-yaml` as you do. Putting YAML into this library would just bloat the library IMHO. Also, YAML isn't very popular in the JavaScript ecosystem, most just use JSON.
