### ISSUE TITLE
Copy a folder content  to its child folder.  

### ISSUE THREAD

**Issue by TheDubey** [jprichardson/node-fs-extra#232]
It make folder recursively if tried to copy folder content from parent folder to child folder.

**Comment by PengXing** [comment]
I've met the same problem.

**Comment by jprichardson** [comment]
What do you mean? Like copying from "/tmp/a" to "/tmp/a/b/c"?

**Comment by TheDubey** [comment]
Yes.. I mean it the same...

**Comment by jprichardson** [comment]
Ok then. Yeah, that should fail. This is intentional. If you wanna do that, read the directory, and find copy all items to the new directory.

**Comment by TheDubey** [comment]
Thanks....☺
