### ISSUE TITLE
.ensureDir(..) fails silently when passed an invalid path...

### ISSUE THREAD

**Issue by flynx** [jprichardson/node-fs-extra#237]
#### To reproduce:

`fs.ensureDir('l:/tmp/foo:moo', err => console.log('>>>', err) )`

#### Expected:
A error is generated and passed to the callback.

#### Result:

- The callback is never called
- CPU loaded -- looks like an infinite loop (did not investigate deeper)

_NOTE: for now tested only on windows._

**Comment by jprichardson** [comment]
Funny, I just started looking at this yesterday. Related: #209, #93.

**Comment by jprichardson** [comment]
Suggestions on a clean fix?

**Comment by flynx** [comment]
@jprichardson I did not dive into the implementation, but in general I think it's obvious, pass an error to the callback in the same manner as native node `.mkdir(..)` does -- on first dir that fails... and infinite loops and recursion are definitely out of the questions ;)

`fs.mkdir('l:/tmp/foo:moo', err => console.log('>>>', err) )`

**Comment by jprichardson** [comment]
>  but in general I think it's obvious, pass an error to the callback in the same manner as native node .mkdir(..) does -- on first dir that fails... and infinite loops and recursion are definitely out of the questions ;)

This is oversimplifying the problem ;) I'll come up with something.

**Comment by flynx** [comment]
Appears to be working fine now, thanks!!
