### ISSUE TITLE
Can't write to files while in a worker thread.

### ISSUE THREAD

**Issue by marcus13345** [jprichardson/node-fs-extra#238]
* **Version**: 5.10.0
* **Platform**: Mac OS X 10.11.4, `Darwin iMac.local 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64`
* **Subsystem**: cluster/fs-extra

I utilise clusters to deffer workloads in my application, and one task a worker may have to do is write a file. Here are the test cases i used:

This will work just fine:

    var fse = require('fs-extra');
    var path = require('path');
    var request = require('request');

    var filepath = path.join(__dirname, "image.jpg");
    request({url:"http://i.imgur.com/InnEHyN.jpg"}).pipe(fse.createWriteStream(filepath));

    var filepath2 = path.join(__dirname, "test.txt");
    fse.writeFile(filepath2, "Sample Text");

However, when i try to do these operations from a worker thread, they do not occur. I dont get any errors or output from the console, it just seems to silently fail.

    var fse = require('fs-extra');
    var path = require('path');
    var request = require('request');
    var cluster = require('cluster');

    if(cluster.isMaster) {
      cluster.fork();
    }else {
      var filepath = path.join(__dirname, "image.jpg");
      request({url:"http://i.imgur.com/InnEHyN.jpg"}).pipe(fse.createWriteStream(filepath));
  
      var filepath2 = path.join(__dirname, "test.txt");
      fse.writeFile(filepath2, "Sample Text");
    }

**Comment by jprichardson** [comment]
The snippet works fine for me under Node v5 and Mac OS X 10.11.

**Comment by marcus13345** [comment]
I tried it again today, and it works. im not sure what I was doing wrong, but the issue is somewhere else. closing the issue.
