### ISSUE TITLE
Depreciate regular expressions for copy's filter

### ISSUE THREAD

**Issue by martinheidegger** [jprichardson/node-fs-extra#239]
Regular Expression filters in [ncp.js:38](https://github.com/jprichardson/node-fs-extra/blob/141422ee384fda83e3e1d4af2727bc9dca799f68/lib/copy/ncp.js#L38) are run against the full source path, i.e.:

`/Users/martin/Private/projects/nodeschool/git-it-electron/node_modules/eslint/node_modules/uglify-js/node_modules/source-map/lib/util.js`

If I want in the folder `git-it-electron` to exclude the `eslint` folder I need to know that I am in the `/Users/martin/Private/projects/nodeschool/git-it-electron` folder when I do that. If I test for `/eslint/` then It would exclude the folder properly but If by some accident I would put the project in a folder called:

`/Users/eslint/Private/projects/nodeschool/git-it-electron`

It would ignore all of the files in my project 😢 . This means that someone would need to implement the file matching with that in mind. Given that `ncp.js` already [considers the working directory](https://github.com/jprichardson/node-fs-extra/blob/141422ee384fda83e3e1d4af2727bc9dca799f68/lib/copy/ncp.js#L13) I think it would be specially awesome if

   A. there would be the opportunity to have filters that work relatively to the working directory
   B. there would be the opportunity to specify where the working directory is (overriding the good `process.cwd()` default)

Additionally it would be super awesome if the filter would allow [glob](https://www.npmjs.com/package/glob) file patterns instead of regexp patterns because they are made for files.

_Note: I am thinking about the API a little and think it would be good to have an `include` and `exclude` option instead of filters. (Considering #65)_

**Comment by jprichardson** [comment]
What if the RegExp's were deprecated and you just passed a function `{filter: function() { }}`... this way you could use glob?

**Comment by jprichardson** [comment]
FYI, functions are supported now.

**Comment by martinheidegger** [comment]
They are supported but they don't know the base path. A deprecation might
be worth thinking about. Also it might be worth to specify the filter API
to be directly compatible with glob in order for the filter to work like
this: 'include: glob.bind(null, "**/*.js")'. I could also think an API like
'include: require("fs-extra/pattern")("**/*.js")' might be good

**Comment by martinheidegger** [comment]
They are supported but they don't know the base path. A deprecation might
be worth thinking about. Also it might be worth to specify the filter API
to be directly compatible with glob in order for the filter to work like
this: `include: glob.bind(null, "**/*.js")`. I could also think an API like
`include: require("fs-extra/pattern")("**/*.js")` might be good.

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
I'd prefer only functions, but I'm afraid that it'll break a lot of code. Long-term, this should use file glob patterns with another module like `glob`. So we should at least deprecate the Regex version for `1.0.0`. 

Thoughts?

**Comment by RyanZim** [comment]
@jprichardson Migration from regexes is simple:

```
- /somereg.*/
+ /somereg.*/.test
```

If you want to depreciate, go ahead.
