### ISSUE TITLE
walkSync request

### ISSUE THREAD

**Issue by rottmann** [jprichardson/node-fs-extra#240]
Need a replacement for the deprecated wrench module `wrench.readdirSyncRecursive(path)`.

Currently "much" code and extra modules are necessary to retrieve only a dir list with walk in sync way.

**Comment by sosspyker** [comment]
True we need a sync implmentation of walk() method. Gulp task with walk() (async) causes issues since some files may not be available for tasks down the line. Thx.

**Comment by zaaack** [comment]
+1 👍

**Comment by brentonhouse** [comment]
👍

**Comment by johannasc** [comment]
+1

**Comment by agnivade** [comment]
@jprichardson - I gave the incorrect PR (#286) tag to auto-close this issue. Would you mind manually closing this ?
