### ISSUE TITLE
copySync doesn't apply the filter to directories

### ISSUE THREAD

**Issue by dbountsman** [jprichardson/node-fs-extra#244]
copySync has a bug, it evaluates the filter only for files. The directoies are copied unfiltered. 
The asynchronous copy method evaluates the filter correct.

**Comment by paulhocker** [comment]
+1

copy uses NCP - copySync does a recursive call on itself - the smarts of NCP would need to be added to this funtion

**Comment by icefox0801** [comment]
+1

**Comment by raulggonzalez** [comment]
+1

**Comment by RyanZim** [comment]
Oops, duplicate of https://github.com/jprichardson/node-fs-extra/issues/180.
