### ISSUE TITLE
filter for empty dir

### ISSUE THREAD

**Issue by richswrighttj** [jprichardson/node-fs-extra#245]
Would it be possible to add in a filter to empty dir? I'd love to leave behind my .gitignore behind but carry on using fs.emptyDir

Thanks!

**Comment by RyanZim** [comment]
Wouldn't be a bad idea IMO. @jprichardson ?

**Comment by jprichardson** [comment]
I'm not opposed to it, but from an implementation standpoint, I think it would require a decent amount of code. Also, does the filter decide what to keep or what to remove? Or both? Then there becomes a lot more code.

Overall, I'm not opposed, but I don't think it should be any priority in the short-term. Closing, but please keep discussion going if anyone feels the need to. Also, @RyanZim if you feel differently, please reopen.

**Comment by RyanZim** [comment]
Nope, we're swamped enough at the present.
