### ISSUE TITLE
Just a Question ... Remove Servers

### ISSUE THREAD

**Issue by forensicsguy20012004** [jprichardson/node-fs-extra#249]
Hello, love the module....great work. Quick question, either I missed it in the documentation or I am using the module incorrectly, can I use this functionality to copy a file from one server to another. If it is possible please let me know...like I said I could have missed it in the documentation or I just coded something wrong on my side. Again, great work...Thanks...Matt

**Comment by jprichardson** [comment]
Fuse over SSH? SMB? What's the server OS?

**Comment by forensicsguy20012004** [comment]
Sorry, the OS is Windows...and I missed typed...Remove should have read...Remote..sorry about that. Essentially I would like to move a zip file from one Windows server to another....thanks again...Matt

**Comment by forensicsguy20012004** [comment]
I believe got this figured out. All appears to be working as designed. Thank you so much.
