### ISSUE TITLE
`fs.remove()` not removing files (works with `rm -rf`)

### ISSUE THREAD

**Issue by Bartozzz** [jprichardson/node-fs-extra#250]
Node.js version: `v5.10.1`
fs-extra version: `latest`

### Code:

```javascript
import fs from "fs-extra";

export default platform => {
    return new Promise( ( resolve, reject ) => {
        const path = `${platform.source}/index.html`;
        // => /Users/.../some_folder/index.html

        fs.remove( path, error => {
            if ( error ) {
                reject( error );
            } else {
                console.log( `Removed: ${path}` );
                resolve();
            }
        } );
    } );
};
```

### Output:

`Removed: /Users/.../some_folder/index.html`

### Issue:
The file still exists. When I use this command in the terminal: `rm -rf "/Users/.../some_folder/index.html"` the file is correctly deleted.

I wonder why the file cannot be deleted with the `.remove()` function? I am pretty sure the specified path is correct since it works when I am deleting the file with `rm -rf` command.

**Comment by dreamcatcha** [comment]
@Bartozzz what happened to be the issue? I'm having a similar issue

**Comment by Bartozzz** [comment]
It was 2 years ago, I don't remember. Probably something with permissions. Feel free to reopen this issue or create a new one if the error persists.
