### ISSUE TITLE
outputFile does not touch mtime when file exists

### ISSUE THREAD

**Issue by meleyal** [jprichardson/node-fs-extra#253]
When modifying a file it seems the `mtime` is not updated:

```js
it('should still modify the file', function (done) {
  var file = path.join(TEST_DIR, Math.random() + 't-e', Math.random() + '.txt')
  fse.mkdirsSync(path.dirname(file))
  fs.writeFileSync(file, 'hello world')
  console.log('statsFirst', fs.statSync(file).mtime.getTime())
  fse.outputFile(file, 'hello jp', function (err) {
    if (err) return done(err)
    assert.equal(fs.readFileSync(file, 'utf8'), 'hello jp')
    console.log('statsSecond', fs.statSync(file).mtime.getTime())
    done()
  })
})
```

```sh
> node test.js
...
  ․․․statsFirst 1466182153000
statsSecond 1466182153000
```

**Comment by RyanZim** [comment]
Will investigate

**Comment by RyanZim** [comment]
This has to do with the slight inaccuracy of `mtime`, try this:

    it('should still modify the file', function (done) {
        var file = path.join(TEST_DIR, Math.random() + 't-e', Math.random() + '.txt')
        fse.mkdirsSync(path.dirname(file))
        fs.writeFileSync(file, 'hello world')
        console.log('statsFirst', fs.statSync(file).mtime.getTime())
        setTimeout(function () {
          fse.outputFile(file, 'hello jp', function (err) {
            if (err) return done(err)
            assert.equal(fs.readFileSync(file, 'utf8'), 'hello jp')
            console.log('statsSecond', fs.statSync(file).mtime.getTime())
            done()
          })
        }, 5)
      })

```
statsFirst 1477611644242
statsSecond 1477611644246
```
