### ISSUE TITLE
Copying a file on windows fails

### ISSUE THREAD

**Issue by liammclennan** [jprichardson/node-fs-extra#257]
I'm using `fs.copySync(src, dest);`

It works on linux, but on windows I get 

```
Error: ENOENT: no such file or directory, open 'dest'
```

**Comment by jprichardson** [comment]
Will you post a snippet, including exact file names reproducing the problem?

Thanks.

**Comment by liammclennan** [comment]
The problem was a colon in the file name, so something like:

```
fs.copySync(src, 'fo:o.txt');
```

The [fs.open function](https://nodejs.org/api/fs.html#fs_fs_open_path_flags_mode_callback) produces the same result. There is no way for this to actually work. A better error message would be nice, but I think this is a problem in node, not fs-extra.
