### ISSUE TITLE
copy files does not preserve file timestamp

### ISSUE THREAD

**Issue by chenlucan** [jprichardson/node-fs-extra#258]
The sample code
`var fs = require('fs-extra');
fs.copy('explore.jpg', 'explore.fs.extra.jpg', function (err) {
  if (err) return console.error(err);
  console.log("success!");
});
`

The destination file modification time changes to current time.

Is it a way to preserve timestamp? like `cp --preserve=timestamps`

also please contribute to this question, it mentions about fs-extra
[Ctrl+C/V under Gnome vs cp command under linux](http://stackoverflow.com/questions/38257332/ctrlc-v-under-gnome-vs-cp-command-under-linux?noredirect=1#comment63936849_38257332)

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-fs-extra#copy

> preserveTimestamps (boolean): will set last modification and access times to the ones of the original source files, default is false.
