### ISSUE TITLE
Feature Request: isEmpty

### ISSUE THREAD

**Issue by donaldpipowitch** [jprichardson/node-fs-extra#259]
It would be nice, if `fs-extra` would have a function which checks, if a directory is empty.

**Comment by jprichardson** [comment]
What's the use case?

**Comment by donaldpipowitch** [comment]
Currently writing some sort of "documentation linter" which checks, if the "examples" directory in our projects is empty. Basically a more powerful "fs.exists". (Thinking of it, "isEmpty" could also check if a file is empty, if it isn't a directory.)

**Comment by RyanZim** [comment]
Wouldn't be opposed to an `isEmpty` method with a `filter` option, but ignoring meta files would be rather unexpected. Should be in a separate lib IMO.

@jprichardson Reopen if you disagree.
