### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by v3yr0n** [jprichardson/node-fs-extra#261]
I'm getting the above error when I do just var fs = require ('fs-extra'); 

Any idea why?
node version: 6.3.1
fs version: 0.0.2
fs-extra version: 0.30.0

**Comment by jprichardson** [comment]
What is "fs version: 0.0.2"? Also, without seeing any code to reproduce the error, it's hard to guess what's causing an error.

**Comment by v3yr0n** [comment]
fs version means the fs node version https://nodejs.org/api/fs.html :)

The only code I need to have that error is var fs = require ('fs-extra'); nothing more. 

Then I get: graceful-fs.js:157 - Uncaught TypeError: Cannot read property 'prototype' of undefined

**Comment by v3yr0n** [comment]
someone had the same issue as me :) http://stackoverflow.com/questions/36771585/nodejsuncaught-typeerror-cannot-read-property-prototype-of-undefined

**Comment by Nico-L** [comment]
Hi, it seems it is rather a [graceful-fs issue](Uncaught TypeError: Cannot read property 'prototype' of undefined #70).

**Comment by unclay** [comment]
Don't use fs-extra in web

**Comment by bennyn** [comment]
@unclay Thanks for this hint! I got rid off `fs-extra` in my web package by configuring this in my `webpack.conf.js`:

```json
  externals: {
    'fs-extra': '{}',
  }
```
