### ISSUE TITLE
Renaming a file using move fails when a file inside is open (at least on windows)

### ISSUE THREAD

**Issue by CxRes** [jprichardson/node-fs-extra#264]
I am not sure if this a fs issue or an fse issue. Apologies if it is the former.

I tried renaming a folder when a file inside it was open. fse created a folder with new name and copied everything into it and then deleted every file except the one open (which Windows locks). Normal Windows behaviour is to lock the folder itself so that it cannot be renamed... I am guessing this is a bug here?  

Using node 6.2.0 Windows 10 x64

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
This feels out of scope for `fs-extra`. Don't you think @RyanZim?

**Comment by RyanZim** [comment]
It's up to you. Don't know if this is big enough to error about or not.

**Comment by jprichardson** [comment]
I'll state that this is `wont-fix` isn't definitive - it only serves as a marker that this issue has been considered at this moment and that there are other priorities for the `fs-extra` authors to tackle. In the future we may reconsider.

**Comment by CxRes** [comment]
Maybe a `consider-later` tag might be more useful?

**Comment by jprichardson** [comment]
@CxRes I'd accept a PR to just get this done and over :) Are you up for it?

**Comment by CxRes** [comment]
@jprichardson Sadly, I have no knowledge of how to detect if a folder is locked in advance :( . If I understood how to fix it, I would have done a PR in August itself or at least suggested the code fix!
