### ISSUE TITLE
Link the `fs.stat fs.exists` etc. methods for replace the `fs` module forever?

### ISSUE THREAD

**Issue by lichenhao** [jprichardson/node-fs-extra#265]
RT, If there some links for that method, we will never need to use fs module forever .

**Comment by jprichardson** [comment]
I'm not sure what your question or issue is?

**Comment by lichenhao** [comment]
I mean may be the other method of `fs` can be linked in the extra and then , when we use the fs-extra module , we don't need to load the fs module again. It's not a problem but it's very lovely design. Just my idea.

**Comment by tndev** [comment]
@lichenhao all methods of `fs` exists in `fs-extra`  [Usage](https://github.com/jprichardson/node-fs-extra#usage):

> fs-extra is a drop in replacement for native fs. All methods in fs are unmodified and attached to fs-extra. 
> You don't ever need to include the original fs module again:

Could be more clear about what you think is missing?

**Comment by lichenhao** [comment]
@tndev  Thx~
