### ISSUE TITLE
fs-extra

### ISSUE THREAD

**Issue by Eliyanan** [jprichardson/node-fs-extra#266]
i downloaded node-fs-extra .zip file and rename it too fs-extra and place it in node-modules folder.. the problem is when i try to require this module it makes my nw.js app invisible. i had written it as z guidance says. so any helps..

**Comment by overlookmotel** [comment]
@Eliyanan I think you'd need to provide a bit more detail to get a response to this. Like wht do you mean by "makes my nw.js app invisible"?

**Comment by RyanZim** [comment]
@overlookmotel Is right. BTW, by all means use npm to install fs-extra.

@jprichardson Should this be closed?
