### ISSUE TITLE
copy not working as desired on Windows

### ISSUE THREAD

**Issue by rlintern** [jprichardson/node-fs-extra#270]
I'm having some trouble on Windows with the copy function.  Others on our team are using Linux and seem to have no trouble.  The following snippet gives me an error unless I create the 'target/folderA/' directory beforehand.  

```
var fsextra = require('fs-extra');

fsextra.copy('source/folderA/folderB', 'target/folderA/folderB', function (err) {
		if (err) {
    console.error(err);
		} else {
    console.log('good');
		}
});

```
The error I get is:
```
[ { [Error: ENOENT: no such file or directory, mkdir 'c:\dx\fs-extra-test\target\folderA\folderB']                                                                                     
    errno: -4058,                                                                                                                                                                      
    code: 'ENOENT',                                                                                                                                                                    
    syscall: 'mkdir',                                                                                                                                                                  
    path: 'c:\\dx\\fs-extra-test\\target\\folderA\\folderB' } ]                
```                                                                                                        
                                                                    

Is this expected behaviour on Windows or a bug?

Regards

**Comment by jprichardson** [comment]
Weird. Can you change this to absolute directories using `path.resolve()` to see if this is still a bug? I'm wondering if there's a bug somewhere related to relative directories.

**Comment by rlintern** [comment]
I think there may be a fundamental difference between mkdir on Windows versus mkdir on Linux.   I think Windows needs parent directories to exist first.  I vaguely remember something like this from another project in the past, or I dreamt it.   It may be more appropriate to use your own mkdir**s** command or equivalent.

**Comment by rlintern** [comment]
oh wait, using path.resolve() worked, as in:
`fsextra.copy(path.resolve('source/folderA/folderB'), path.resolve('target/folderA/folderB'),`

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
> @jprichardson ping?

Seems to me that the paths should be resolved in advance by `copy()`... thoughts @RyanZim?

**Comment by RyanZim** [comment]
If you can run `path.resolve` on input without side effects, I'd say do it!

**Comment by jprichardson** [comment]
> If you can run path.resolve on input without side effects,

This is the biggest concern. IDK, can we safely assume this? Maybe not?

**Comment by RyanZim** [comment]
@jprichardson I'll leave that to you.

**Comment by jprichardson** [comment]
> @jprichardson I'll leave that to you.

Since I can't say for certainty, I think we should pass on `path.resolve` for the time being. If someone else reads this is knows otherwise, please comment.

**Comment by dewelloper** [comment]
@jprichardson right it just copied when it used like this 
fs.copySync(path.resolve(sourceFile), path.resolve(targetFile));
