### ISSUE TITLE
Unclosed file handle on futimes error

### ISSUE THREAD

**Issue by chadnickbok** [jprichardson/node-fs-extra#271]
The call to fs.close(fd) should be performed _before_ the call to return in this function:

https://github.com/jprichardson/node-fs-extra/blob/master/lib/util/utimes.js#L53

**Comment by hhamilto** [comment]
Unless anyone is working on this, I'll submit a PR.

**Comment by jprichardson** [comment]
> Unless anyone is working on this, I'll submit a PR.

Would love this. Please include a test. Thanks!

**Comment by hhamilto** [comment]
> Please include a test.

Will do. I think there might be a few different ways to test this, so once the PR is up, I'll welcome some feed back on the best approach.

**Comment by hhamilto** [comment]
@jprichardson Question:
How do you feel about adding a devDependency on Sinon, or some other mocking library?

Background:
I'm thinking that mocking would be the best way to test that `close` is properly called even when the call to `futimes` returns an error. The only errors that `futimes` usually returns occur when the fd passed in refers to a file on a read-only file system, or if the owner of the file doesn't match the current user (from [here](http://man7.org/linux/man-pages/man2/utimes.2.html)). It doesn't seem practical to set up either of these conditions just for a test, unless I missed something when researching. 

If we mocked the `fs` functions that `utimesMillis` uses, then we could just assert that the close method is called even when `futimes` returns an error.

**Comment by jprichardson** [comment]
@hhamilto how do you feel about proxyquire?

**Comment by RyanZim** [comment]
@hhamilto How's that PR coming along?

**Comment by hhamilto** [comment]
@Ryan I'd welcome your feedback on it:
https://github.com/jprichardson/node-fs-extra/pull/289

**Comment by RyanZim** [comment]
Sorry, didn't realize a PR was filed.

**Comment by hhamilto** [comment]
No worries, I meant to put a ping on it a while back, to see if there is anything else that needs to be fixed before it gets merged.
