### ISSUE TITLE
Copy clobber flag never err even when true

### ISSUE THREAD

**Issue by ryancmlee** [jprichardson/node-fs-extra#272]
In the following code `err` is never not `null`:

```
fs.copy(sourcePath, targetPath, { clobber: true  }, (err) =>
{
    if (err)
        debugger
    fs.copy(sourcePath, targetPath, { clobber: true}, (err) =>
    {
        if (err)
            debugger
        fs.copy(sourcePath, targetPath, { clobber: false}, (err) =>
        {
            if (err)
                debugger
            fs.copy(sourcePath, targetPath, { clobber: false }, (err) =>
            {
                if (err)
                    debugger
            })
        })
    })
})
```

Maybe this is intended but then at least add the option for open flags so I can at least put `wx` and have it `err.code =  "EEXIST"`

Thanks,
Ryan

**Comment by qqilihq** [comment]
I'm asking myself as well: Is there any way to determine, if the file content was copied, when `clobber` is set to `false`?

**Comment by RyanZim** [comment]
@ryancmlee @qqilihq Good points. @jprichardson Thoughts?

**Comment by jprichardson** [comment]
Yep, this is a bug. If `clobber` is `false` and the destination exists, there should be an `Error`.

**Comment by RyanZim** [comment]
OK, will investigate.

**Comment by RyanZim** [comment]
The issue is https://github.com/jprichardson/node-fs-extra/blob/master/lib/copy/ncp.js#L92. @jprichardson Should I attempt to create a fake `EEXIST` error here or what?

**Comment by jprichardson** [comment]
@RyanZim yep, I think that'd be fine.

**Comment by RyanZim** [comment]
@jprichardson Creating a fake `SystemError` isn't easy, and I don't think I can replicate it completely. Advice?

**Comment by jprichardson** [comment]
@RyanZim what about...

```js
const err = new Error(file + ' already exists.')
err.code = EEXIST
```

?

**Comment by RyanZim** [comment]
I guess that will cover most cases; still will have a JS stack trace, IDK.

Should also set `err.errno = -17` & `err.path = file`.
