### ISSUE TITLE
Use with memory-fs?

### ISSUE THREAD

**Issue by arvitaly** [jprichardson/node-fs-extra#274]
Hi, i love your library, but can you add support for change native fs to https://www.npmjs.com/package/memory-fs or other fs?

**Comment by jprichardson** [comment]
I actually have a local branch where I've been working on this but got side-tracked. If you'd want to tackle this, I'd welcome this change. Maybe start with one function at a time, or maybe we need to create a factor method. Not sure yet.

**Comment by arvitaly** [comment]
I think, we have a good example [here](https://github.com/jprichardson/node-fs-extra/blob/8c56e5b263608359a612c805e3f867565987eb37/lib/mkdirs/mkdirs.js) already. Ok, i will try pull requests, thank you.

**Comment by jprichardson** [comment]
Ok great, but start with one function at a time please :)

**Comment by RyanZim** [comment]
@arvitaly @jprichardson What is the plan/status on this? Is the whole library going to do something like `mkdirs`?

**Comment by jprichardson** [comment]
@RyanZim my plan is to allow `fs-extra` to take in any `fs` object, by default `require('fs')` to allow for mock / memory filesystems. Some methods already have this support. I really like https://github.com/tschaub/mock-fs

**Comment by RyanZim** [comment]
:+1: I was wondering what API you were planning.

Possible ways:
```
var fs = require('fs-extra')
fs.registerFS(require('mock-fs'))
```

```
var fse = require('fs-extra')
var fs = new fse.Mock(require('mock-fs'))
```

```
var fs = require('fs-extra')
fs.mkdirp(path, {fs: require('mock-fs')}, callback)
```

Thoughts? I personally would favor the first one, or a combination of the first and third.

**Comment by jprichardson** [comment]
I think `fs.registerFS(require('mock-fs'))` is a great first start. I'd eventually like the ability to override at the functional level as well. That's where I started first... I believe you can see it in action in some functions... may just be in `jsonfile` though.

**Comment by borekb** [comment]
Sorry, just a newbie question, so currently `fs-extra` cannot be used together with `mock-fs`?

**Comment by RyanZim** [comment]
@borekb `mock-fs` changed quite a bit since we discussed this. I think you'd be able to use it with `fs-extra` now.

**Comment by manidlou** [comment]
@jprichardson @RyanZim so you mean all functions would accept an optional custom `fs` object the same as [mkdirs](https://github.com/jprichardson/node-fs-extra/blob/master/lib/mkdirs/mkdirs.js#L24)?

**Comment by CurosMJ** [comment]
`mock-fs` 4.4.2 and `fs-extra` 5.0.0 do not play well with each other. After mocking, `fs-extra` keeps using the un-stubbed `fs` module.

**Comment by masaeedu** [comment]
Could one of the maintainers of the project please let me know whether using ES6 features like object spread and arrow functions in the codebase is acceptable? The refactoring required is more or less straightforward, but it needs function composition and re-exporting of things in several places, which makes the code verbose and ugly when not using these features.

**Comment by RyanZim** [comment]
@masaeedu Anything supported in Node v4 is allowed. However, we'll be dropping Node 4 support April-May, so after that, it'd be anything supported in Node 6. Handy chart: http://node.green/

**Comment by masaeedu** [comment]
@RyanZim I'm going to assume that is a "yes" 😁

**Comment by RyanZim** [comment]
Node 6 supports a lot of stuff, but not object spreads.

**Comment by masaeedu** [comment]
@RyanZim My bad, I was referring to object destructuring (`const { foo, bar } = { foo: 1, bar: 2}`), got mixed up with the terminology. Object spread would be handy in some places, but you can just use `Object.assign`.

**Comment by kenberkeley** [comment]
So how's it going, may I ask?

**Comment by yuchonghua** [comment]
Can I use it with [memory-fs](https://www.npmjs.com/package/memory-fs) or WebSocket-fs? Because many times, fs only represents this machine, expecting to pass in fs

**Comment by RyanZim** [comment]
- https://github.com/webpack/memory-fs is unmaintained since 2017.
- https://github.com/tschaub/mock-fs now monkey-patches the `fs` module, so it doesn't need us to do anything as far as accepting `fs` as an option.

Given these two facts, I propose we close this out as `wontfix`. If we want to investigate playing better with `mock-fs`'s monkey-patching (I haven't tested how well it works currently), that should be a separate issue.

@manidlou @JPeer264 @jprichardson thoughts?

**Comment by maple3142** [comment]
Besides, [memfs](https://github.com/streamich/memfs) do exist too, so I think it is reasonable to have an option to provide a custom node-compatible `fs` option in fs-extra.

**Comment by RyanZim** [comment]
Closing as wontfix; reasoning in https://github.com/jprichardson/node-fs-extra/pull/733#issuecomment-580432843.
