### ISSUE TITLE
EMFILE, too many open files on Mac OS with JSON API

### ISSUE THREAD

**Issue by jareguo** [jprichardson/node-fs-extra#275]
readJson relies on `jsonfile` module, which just uses the original node fs module. It will cause the [EMFILE](http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me) error on Mac, so it's better to use `graceful-fs` everywhere to avoid the EMFILE problem.

**Comment by jprichardson** [comment]
@jareguo good point. Would you submit a PR in `jsonfile`?

**Comment by jareguo** [comment]
Sorry I don't have much time to submit a PR (and test it) lately, I just ignore all json API in my project.

**Comment by richdunajewski** [comment]
Seeing the same on Windows when writing JSON files in a loop (but waiting for the `outputJson` callback to fire before going through another iteration to prevent stacking up the writes). Nearly 200,000 iterations occurred before the EMFILE exception was eventually thrown. 

Perhaps the callback is firing before the file is truly closed, allowing a variable number of handles to be left open when in a loop situation?

**Comment by bhousel** [comment]
I'm getting this error when using `walk` too..

**Comment by RyanZim** [comment]
I'm working on fixing `walk`.

**Comment by RyanZim** [comment]
Done https://github.com/jprichardson/node-klaw/pull/10.

When that is merged and `klaw` makes a new release, this can be closed.
