### ISSUE TITLE
Cannot connect to Shared Folder

### ISSUE THREAD

**Issue by fradiocey** [jprichardson/node-fs-extra#276]
{ [Error: ENOENT: no such file or directory, lstat 'net use z: //mymswfs01/180-Public/BPMS/Book1.xlsx']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'net use z: //mymswfs01/180-Public/BPMS/Book1.xlsx' }

**Comment by hhamilto** [comment]
Just to help clarify, what operation were you trying when you get this error?

**Comment by RyanZim** [comment]
@fradiocey ping?

**Comment by RyanZim** [comment]
If I don't get a response from @fradiocey  within 7 days, I will close this.

**Comment by fradiocey** [comment]
Hi, please close this issue, the path cannot accessible, that is why got above error message, and other caused my computer using Windows 7 OS, it is not supported SMB2
