### ISSUE TITLE
copy() does not preserve file/directory ownership

### ISSUE THREAD

**Issue by greyarch** [jprichardson/node-fs-extra#278]
All files/directories in the copy are owned by the user that started the node.js process.

**Comment by RyanZim** [comment]
FWIW, unix `cp` doesn't preserve ownership by default. http://unix.stackexchange.com/questions/43605/how-do-i-copy-a-folder-keeping-owners-and-permissions-intact

@jprichardson Is this within the scope of fs-extra? I would tend to think this belongs in a separate `copy-preserve` module that does nothing but copy files preserving ownership and permissions; you may think differently.

**Comment by jprichardson** [comment]
> @jprichardson Is this within the scope of fs-extra? I would tend to think this belongs in a separate copy-preserve module that does nothing but copy files preserving ownership and permissions; you may think differently.

Sounds good.!
