### ISSUE TITLE
Exclude files pattern while copying using copy.config.js

### ISSUE THREAD

**Issue by Quocnamit** [jprichardson/node-fs-extra#290]
Hello everyone,

I'm using my custom copy.config.js to define my resource which will be copy to my build destination.

module.exports = {
  include: [
   {
      src: 'node_modules/ionic-angular/fonts/',
      dest: '{{WWW}}/assets/fonts/'
    }
  ]
};

I want to exclude some *.scss in 'node_modules/ionic-angular/fonts/'. How can I do this ?

Thanks

**Comment by RyanZim** [comment]
fs-extra currently doesn't support globs, you will need to use https://github.com/isaacs/node-glob.

You will need to use a combination of the `filter` option and glob to accomplish excluding a glob.

Something like this:
```
var fs = require('fs-extra')
var glob = require('glob')
// Using sync method here for simplicity:
var exclude = glob.sync('node_modules/ionic-angular/fonts/*.scss')

fs.copy('node_modules/ionic-angular/fonts/`, 'www/assets/fonts/', {
  filter: function (name) {
    // Check if any of the items in exclude match:
    return exclude.some(function (item) {
      return item !== name
    }
  }
}, function (err) {
  if (err) return console.error(err)
  console.log("success!")
}
```

Hope this answers your question; if so, please close.

**Comment by RyanZim** [comment]
Going to close this, can reopen if more help is needed.
