### ISSUE TITLE
API Docs

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#298]
@jprichardson Thinking about the documentation: `fs-extra`'s docs are rather large. Perhaps we are approaching the size to consider using documentation.js or similar. For smaller libs, I consider this more trouble than it's worth, but I think I see some benefits here. Thoughts?

Of course, I doubt we can get this done in time for v1.0.0, but looking into the future, this might be the route to pursue.

Refs: https://github.com/jprichardson/node-fs-extra/issues/148.

**Comment by jprichardson** [comment]
yeah, in the short-term (next few months), I think a changing the README to just have the table of contents and then a `docs/` directory with each module? Similar to how it's broken down in `lib/`.

**Comment by RyanZim** [comment]
> a docs/ directory with each module

Personally, I prefer all the docs in one place. :grin: 

documentation.js can output html, markdown, or inject the docs into the README. I'm not sure if we need a website, API.md or the inject function would do fine IMO.

I think keeping the docs inside the code would help keep them updated.

https://github.com/documentationjs/documentation

**Comment by jprichardson** [comment]
> I think keeping the docs inside the code would help keep them updated.

Yeah, I like this too. That's what I meant, having a `docs/` directory in this repo. I typically prefer `markdown` because of its simplicity as introducing an additional dev dependency adds one more thing - plus, documentation tools typically requiring building from markdown anyways so we'd have working markdown docs already.

However, if you feel strongly in one direction, I'll follow your lead.

**Comment by RyanZim** [comment]
> I think keeping the docs inside the code would help keep them updated.

I meant documentation inside code comments, right next to the methods. https://github.com/documentationjs/documentation uses JSDoc syntax, but is a bit smarter at documenting CommonJS modules and can output markdown as well as html. http://usejsdoc.org is a bit harder to use, and only outputs html.

**Comment by jprichardson** [comment]
> I meant documentation inside code comments, right next to the methods.

Ah, I despise JSDoc with a passion :) I'm from the school of thought that:

1. less lines of code is better (comments count here)
2. developers need to proactively develop good documentation outside of the code

I'm not claiming that I'm correct here nor that I can't change my mind, this is just where I stand today.

Let's delay this unless you have a strong preference not to.

**Comment by RyanZim** [comment]
> Ah, I despise JSDoc with a passion :)

I don't really like it either, but for larger projects with lots of methods like lodash, async.js (:wink:), etc. sometimes it's a necessary evil.

> Let's delay this

I'm OK with that.

**Comment by RyanZim** [comment]
@jprichardson I still prefer the docs all in one place, unless it's going to be a website with a sidebar nav (like http://nodejs.org/api). Not going to be dogmatic on this point, though.

**Comment by RyanZim** [comment]
@jprichardson Are we going to be changing anything with the docs for v2?

**Comment by jprichardson** [comment]
> @jprichardson Are we going to be changing anything with the docs for v2?

The only major change that I think makes sense in the short-term is moving everything after the table of contents. If we change other things, that's fine as well.

**Comment by RyanZim** [comment]
@jprichardson Should the docs for `ensureDir` and `mkdirs` be merged into one file in `docs/`?

**Comment by RyanZim** [comment]
> ### outputJson(file, data, [options], callback)
> 
> Almost the same as `writeJson`, except that if the directory does not exist, it's created.

@jprichardson Did Node `fs` have a `writeJson` method at one time? What is this referring to?

**Comment by jprichardson** [comment]
> @jprichardson Should the docs for ensureDir and mkdirs be merged into one file in docs/?

If we think that we'll eventually settle on one, then yes. If not, then no. Generally, I hate aliases in libraries... "one way to rule them all" FTW IMHO. However, it was created for consistency with `ensureFile`. Semantically, I think that `ensureDir` is better than `mkdirs`... but I'm not so sure they should be equivalent in their operation despite being so today.

Thoughts? 

As far as answering your question, I think the easiest path to completion is the acceptable one in this case, so, I'd venture to guess... then yes, they should be combined. Phew, sorry for the long answer here.

**Comment by RyanZim** [comment]
> Semantically, I think that ensureDir is better than mkdirs

I've been leaning that direction myself.

> I'm not so sure they should be equivalent in their operation despite being so today

What should be different in operation?

**Comment by RyanZim** [comment]
BTW, you can see a sneak peak of this at https://github.com/jprichardson/node-fs-extra/tree/docs.

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/340.
