### ISSUE TITLE
move() limit option

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#314]
The docs for `move` show a `limit` option. https://github.com/jprichardson/node-fs-extra#movesrc-dest-options-callback

> limit (number): number of concurrent moves, see ncp for more information

Since v1, our version of ncp does not respect `limit`. I was not aware of the fact that `move` used it when I removed it from ncp. It was undocumented for `copy`, and I assumed it could be removed safely.

Since we are using graceful-fs, `limit` is sort of pointless.

@jprichardson Since using `limit` in v1 is broken anyway, should we just remove it from the docs and `move`'s code?

**Comment by jprichardson** [comment]
> @jprichardson Since using limit in v1 is broken anyway, should we just remove it from the docs and move's code?

Yep.

**Comment by RyanZim** [comment]
PR done: #316.
