### ISSUE TITLE
Support glob patterns

### ISSUE THREAD

**Issue by monolithed** [jprichardson/node-fs-extra#318]
```js
fs.copySync('./{foo,bar}.js', './tmp');
fs.copySync('./foo.*', './tmp');
```

It would be nice to implement these patterns

**Comment by RyanZim** [comment]
This is something we might implement in the far-distant future. Implementing this will involve a lot of work. As far as time-frame, I would say it will be at least several years until we support this. For now, just use the `glob` or `globby` modules.

**Comment by ricardopolo** [comment]
@RyanZim after three years from the last response, do you think maybe this is going to develop this year?

Thanks

**Comment by RyanZim** [comment]
Figuring out how this is going to work will be a major undertaking. I, for myself, don't see myself having the necessary time to do this.

**Comment by RyanZim** [comment]
Given the complexity of this, I'm going to close this out as `wontfix`.

**Comment by m4heshd** [comment]
Sad to see the `wont-fix` tag because this is exactly what I need right now. Well, a massive function it is then. 😥
