### ISSUE TITLE
Create directory if not exists

### ISSUE THREAD

**Issue by monolithed** [jprichardson/node-fs-extra#319]
```
fs.copySync('foo.txt', 'tmp/');
```

```
Error: ENOENT: no such file or directory, open 'foo/'
```

I propose to add an option to create directory if not exists

**Comment by RyanZim** [comment]
We don't support copying to directories, see https://github.com/jprichardson/node-fs-extra/issues/320#issuecomment-261606432.

**Comment by monolithed** [comment]
I see what you mean, but please look at my examples:

##  Actual 

```js
let from = '...';
let to = '...'

let { base } = path.parse(from);

to = path.join(to, base);

fs.copySync(from, to);
```

##  Expected

```
let from = '...';
let to = '...'

fs.copySync(from, to);
```

There are a wide variety of project like Webpack, Grunt etc where you can see that behavior.
It's expected for most people. `fs-extra` is no `fs` and similar features are expected by design.
I guess you should reconsider reopening this issue.

@jprichardson what do you think?

**Comment by RyanZim** [comment]
I'll leave this to @jprichardson.

FWIW, your example could be shortened to:
```js
let from = '...';
let to = '...'

fs.copySync(from, path.join(path.dirname(from), to));
```

**Comment by monolithed** [comment]
> your example could be shortened ..

I know, but I don't like a single-line code with overhead.
