### ISSUE TITLE
fs.copy fails with chmod error when disk under heavy use

### ISSUE THREAD

**Issue by nicks** [jprichardson/node-fs-extra#326]
Sometimes, when the disk is under heavy use, we see fs.copy fail with the following error:
```
[Error] ENOENT: no such file or directory, chmod '/path/to/dir.js'
```

We tracked down the error to this line: https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/copy/ncp.js#L111
```
    writeStream.once('finish', function () {
      fs.chmod(target, file.mode, function (err) {
        if (err) return onError(err)
```

My current hypothesis is that the stream `finish` event is just for generic stream flush, and doesn't guarantee that the underlying filesystem operations have completed. If I change it to 'close', the issue goes away.

That said, I've very vague on the intended semantics of nodejs stream events, so I might be on the totally wrong path here.

**Comment by jprichardson** [comment]
I believe you are correct. Feel like submitting a PR? We'll be releasing 2.0 after Jan 1st and this would make in time for that release.

**Comment by nicks** [comment]
OK

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/327 (Thanks @nicks!). Should be released early next year.

**Comment by popod** [comment]
It seem that this error occurs always on 2.0.0 :(

![error](https://cloud.githubusercontent.com/assets/3807312/22714064/31711618-ed8b-11e6-87d5-eebee4cf7746.jpg)

**Comment by RyanZim** [comment]
@popod If this issue still exists, please open a new issue with a minimal, complete, and verifiable example. Thanks!
