### ISSUE TITLE
Copying files corrupts

### ISSUE THREAD

**Issue by mfgabriel92** [jprichardson/node-fs-extra#328]
Hi,

I am using AdonisJS as my MVC framework and I had issues using their [`move()`](https://github.com/adonisjs/adonis-framework/blob/cb3d938eab63e21dc10bbb7facf58f87cdc5c923/src/File/index.js#L156) method. They use `fs`, so I decided to look for something else. `fs-extra` seemed nice, since it seems to be an improvement of `fs`, but in the end, the same issue happens: after copying, the file is corrupted. Here's my code:

```
fse.ensureDir(publicPath, (error) => {
  if (error) {
    throw new HttpException(error, HTTPResponse.STATUS_INTERNAL_SERVER_ERROR);
  }
});

fse.copy(imageFile.tmpPath(), fullPath, (error) => {
  if (error) {
    throw new HttpException(error, HTTPResponse.STATUS_INTERNAL_SERVER_ERROR);
  }
});
```

The message is shows when opening the copied file is:

>Error interpreting JPEG image file (Not a JPEG file: starts with 0xef 0xbf)

No clue what's this, please, suggestions?

**Comment by RyanZim** [comment]
I am unable to reproduce this.

Please list the following information:

- Operating System
- Node Version
- fs-extra Version

Please make a MCVE and post it as a GitHub gist or repo. Thanks!
