### ISSUE TITLE
Does .walk() scale to large directories?

### ISSUE THREAD

**Issue by DomVinyard** [jprichardson/node-fs-extra#329]
Does the walk method scale up to large directories - (10 million files) - in the same way https://github.com/kemitchell/native-readdir.js. Or does it need to list out all the files first before it can emit anything?

**Comment by RyanZim** [comment]
@jprichardson ping?

**Comment by jprichardson** [comment]
@DomVinyard - I have never tested it with 10M files. However, I'm assuming it should be fine since it's using streams. But have a look for yourself, the code is less than 75 lines: https://github.com/jprichardson/node-klaw/blob/master/src/index.js Also, writing up a test script would be very easy.

**Comment by DomVinyard** [comment]
@jprichardson for completeness: https://github.com/jprichardson/node-klaw/issues/14#issuecomment-270098925
