### ISSUE TITLE
Add support for chmodr

### ISSUE THREAD

**Issue by JustinBeckwith** [jprichardson/node-fs-extra#331]
Keeping with the theme of recursive fs methods, I've needed the npm module `chmodr` a few times.  It would be nice if this lib offered a chmod with -R :)

**Comment by RyanZim** [comment]
Not a bad idea IMO; https://github.com/isaacs/chmodr/issues/9 should be fixed before we include this in fs-extra.

**Comment by manidlou** [comment]
It seems like [isaacs/chmodr#9](https://github.com/isaacs/chmodr/issues/9) is resolved. What do we want to do about this?

**Comment by jprichardson** [comment]
> It seems like isaacs/chmodr#9 is resolved. What do we want to do about this?

Since https://github.com/isaacs/chmodr exists, maybe we just redirect users to that? This way we can continue to focus on improving fs-extra for what it offers and get it to be really good at just a few things. Thoughts @RyanZim?

**Comment by RyanZim** [comment]
It's up to you @jprichardson.

**Comment by lmj0011** [comment]
just what I was looking for: https://github.com/jprichardson/node-fs-extra/issues/331#issuecomment-284513916 😄
