### ISSUE TITLE
mkdirp(path.dirname(dest) in move() logic needs cleaning up

### ISSUE THREAD

**Issue by tagyoureit** [jprichardson/node-fs-extra#341]
In trying to get move() to work, I noticed that (https://github.com/jprichardson/node-fs-extra/blob/1.x/lib/move/index.js#L29) `mkdirp(path.dirname(dest)` tries to create the parent directory of the target when specifying directory to directory copy.

eg. dest = /a/b/c 
    => 
     path.dirname(dest)===/a/b

Is this the intended logic?  If you want to copy from /src to /home/User/Documents/target the logic tries to create /home/User/Documents.

**Comment by RyanZim** [comment]
@tagyoureit 

> Is this the intended logic?

Yes, it is.

> If you want to copy from /src to /home/User/Documents/target the logic tries to create /home/User/Documents.

Yeah, though mkdirp handles the existence of /home/User/Documents just fine.

Most of the time, if you're copying to a directory that doesn't exist, you just want to create it. fs-extra does this for you.

If you want to disable this behavior, you can pass `clobber: false` in the options.
