### ISSUE TITLE
Licence Year

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#344]
@jprichardson Just a quick note before you release v2:

> ## License
> Licensed under MIT
Copyright (c) 2011-2016 JP Richardson

in the README

Also needs fixed in the LICENSE.

**Comment by RyanZim** [comment]
Also, don't forget to close the 2.0.0 milestone on Monday.

**Comment by jprichardson** [comment]
Closed with https://github.com/jprichardson/node-fs-extra/commit/b34da2762a4865b025cac06d02d6a2f1f1027b65
