### ISSUE TITLE
Missing docs for mkdirs and mkdirsSync

### ISSUE THREAD

**Issue by fiannaca** [jprichardson/node-fs-extra#346]
As of the doc restructuring in commit 383a26985cab5b8a184cea9fa776d2fa6da8a5fe, the documentation links in README.md for `mkdirs` and `mkdirsSync` point to `docs/ensureDir.md` instead of appropriate documentation.

**Comment by RyanZim** [comment]
From the `ensureDir` page:

> Aliases: mkdirs(), mkdirp()

`mkdirs` has always been an alias for `ensureDir`, I'm not sure why the docs were separated.

**Comment by fiannaca** [comment]
Ah, I missed that. Thanks

**Comment by RyanZim** [comment]
No Prob

**Comment by zalouma1** [comment]
I also miss the information, that this **is alias only**. As improvement, the title of doc page can contains all method names.
## ensureDirSync(dir), mkdirsSync(dir), mkdirpSync(dir)

**Comment by ma-zal** [comment]
I also miss the information, that this is alias only. As improvement, the title of doc page can contains all method names.

ensureDirSync(dir), mkdirsSync(dir), mkdirpSync(dir)

**Comment by RyanZim** [comment]
We are encouraging people to use `ensureDir`; we've considered removing the aliases: https://github.com/jprichardson/node-fs-extra/issues/171.
