### ISSUE TITLE
createReadStream failed to pipe twice.

### ISSUE THREAD

**Issue by fandisus** [jprichardson/node-fs-extra#354]
This:

fs.createReadStream(location[0])
.pipe(zlib.createGunzip())
.pipe(fse.createWriteStream('anu.temp'));

Does not cause an error.

While:

fse.createReadStream(location[0])
.pipe(zlib.createGunzip())
.pipe(fse.createWriteStream('anu.temp'));

Caused this:
![errr](https://cloud.githubusercontent.com/assets/4706686/22880458/cc089e2a-f214-11e6-801a-0c9bcd45c064.png)

Though this:
fse.createReadStream(location[0]).pipe(fse.createWriteStream('anu.temp'));

Does not create an error.

**Comment by RyanZim** [comment]
Looks like this might be a problem with `zlib`, not sure; anyhow, fs-extra just directly proxies the native fs methods, so I don't think this is a problem on our end.
