### ISSUE TITLE
Delete 1.x branch

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#361]
Just want to make sure everyone is OK with this.

We have a `1.x` for the v1 release line. We are not supporting v1 anymore, so I would like to delete this branch. Does anyone oppose this?

**Comment by jprichardson** [comment]
> We have a 1.x for the v1 release line. We are not supporting v1 anymore, so I would like to delete this branch. Does anyone oppose this?

Nope, go for it. Worst case scenario we can always recreate if needed.

**Comment by RyanZim** [comment]
Done
