### ISSUE TITLE
Github topics

### ISSUE THREAD

**Issue by JPeer264** [jprichardson/node-fs-extra#373]
It would be good to add [Github topics](https://github.com/blog/2309-introducing-topics) to `fs-extra`. Maybe something like: `filesystem` `nodejs`

**Comment by RyanZim** [comment]
:+1: 

@jprichardson You're the only one with rights to do it.

**Comment by jprichardson** [comment]
Done. Happy to change any of them or add/remove.

**Comment by RyanZim** [comment]
LGTM, thanks!
