### ISSUE TITLE
fs.move should noop when source and desc are the same.

### ISSUE THREAD

**Issue by jdalton** [jprichardson/node-fs-extra#377]
Since the file is already at its destination `fs.move` should noop. Similar to how `fs.remove` doesn't error if a file doesn't exist.

**Comment by RyanZim** [comment]
@jdalton I agree this case should be handled. Interested in submitting a PR?

BTW, what's the current behavior?

**Comment by jdalton** [comment]
Yep. I'll submit a PR. The current behavior is to throw an error (some already-exists error)

**Comment by jdalton** [comment]
Moved to #378.
