### ISSUE TITLE
fs.moveSync is missing (Release v2.1.0)

### ISSUE THREAD

**Issue by RyanCopley** [jprichardson/node-fs-extra#385]
```npm install --save fs-extra
smash@1.0.0 /Users/ryancopley/Projects/smash
└─┬ fs-extra@2.0.0
  ├── graceful-fs@4.1.11
  └── jsonfile@2.4.0


cat node_modules/fs-extra/lib/index.js
var assign = require('./util/assign')

var fse = {}
var gfs = require('graceful-fs')

// attach fs methods to fse
Object.keys(gfs).forEach(function (key) {
  fse[key] = gfs[key]
})

var fs = fse

assign(fs, require('./copy'))
assign(fs, require('./copy-sync'))
assign(fs, require('./mkdirs'))
assign(fs, require('./remove'))
assign(fs, require('./json'))
assign(fs, require('./move')) < ---- NO MOVE SYNC
assign(fs, require('./empty'))
assign(fs, require('./ensure'))
assign(fs, require('./output'))

module.exports = fs

// maintain backwards compatibility for awhile
var jsonfile = {}
Object.defineProperty(jsonfile, 'spaces', {
  get: function () {
    return fs.spaces // found in ./json
  },
  set: function (val) {
    fs.spaces = val
  }
})

```

Is the npm package up-to-date? If not, could it please be? :-)

Thanks,
Ryan

**Comment by manidlou** [comment]
@RyanCopley `moveSync` is implemented but is not published on npm yet. Surely, new version will be published soon, but I personally don't know when exactly that'd be. @jprichardson and @RyanZim should have a better idea about this.

**Comment by RyanZim** [comment]
@jprichardson Perhaps we should publish v2.1.0 soon?

**Comment by ninox92** [comment]
+1

**Comment by jprichardson** [comment]
> @jprichardson Perhaps we should publish v2.1.0 soon?

Sounds good. I'll plan tomorrow. @RyanZim can you prepare the `CHANGELOG`? Thank you!

**Comment by RyanZim** [comment]
Sure, PR on the way.

**Comment by RyanZim** [comment]
PR done: https://github.com/jprichardson/node-fs-extra/pull/386.

**Comment by RyanCopley** [comment]
I think the npm module still needs published, not 100% positive though.

**Comment by RyanZim** [comment]
Yep, only @jprichardson can do that.

**Comment by RyanZim** [comment]
OK, got publish rights. v2.1.0 is shipped: https://github.com/jprichardson/node-fs-extra/commit/90b3609b894b27ff9ccd1f820c9a2eb44314f809.

**Comment by RyanCopley** [comment]
Thank you!

**Comment by ninox92** [comment]
Thanks!
