### ISSUE TITLE
Cleaning empty folders

### ISSUE THREAD

**Issue by RyanCopley** [jprichardson/node-fs-extra#387]
Not sure how comprehensive you all want fs-extra to be... but I occasionally use this script to clean up empty folders: 
```
function cleanEmptyFoldersRecursively(folder) {

    const isDir = fs.statSync(folder).isDirectory();
    if (!isDir) {
        return;
    }
    let files = fs.readdirSync(folder);
    if (files.length > 0) {
        files.forEach(function(file) {
            const fullPath = path.join(folder, file);
            cleanEmptyFoldersRecursively(fullPath);
        });
        files = fs.readdirSync(folder);
    }

    if (files.length === 0) {
        fs.rmdirSync(folder);
        return;
    }
}
```

It removes all empty directories recursively. I think I stole this code off the internet from somewhere, but re-implementing it would be trivial. Would you all want something like this included in the `empty` package? I could open a PR if the idea is appreciated

Thanks,
Ryan

**Comment by RyanZim** [comment]
I'm not in favor of this, for the following reasons:

- It's fairly simple sugar (you can implement it yourself). Admittedly, all the `empty*` methods are pretty simple sugar.
- If we add this, where will we stop? What about when someone requests a method that removes empty files, or removes files over a certain size, etc? It's hard to draw the line between useful methods and feature bloat.

I'll let other members of the team express their opinion before closing this, though.

**Comment by jprichardson** [comment]
I side with @RyanZim on this one. Thank you @RyanCopley for posting the issue though - and please continue to share your thoughts and post other issues for feature suggestions and improvements. We appreciate it.
