### ISSUE TITLE
Error handling in documentation

### ISSUE THREAD

**Issue by adadgio** [jprichardson/node-fs-extra#388]
There are wrong statement in the docs. In strict mode, when you use `if (err) return console.error(err)` in async functions such as...

```
fse.move(origin, dest,  { overwrite: true }, (err) => {
        if (err) { console.log(err); return; }

       // do something else
        console.log('Done);
    });
```

The code in the callback never gets executed because in case of success `err` is undefined and not `false`.

It should be either:

```
fse.move(origin, dest,  { overwrite: true }, (err) => {
        if (typeof err !== 'undefined') { console.log(err); return; }

       // do something else
        console.log('Done);
    });
```

or you should return false in `err` in case of success.

Cheers!

**Comment by RyanZim** [comment]
I'm not sure what you're trying to say. If you write `if (err) return console.log(err)`, the `console.log` is only going to be executed if `err` is truthy.
