### ISSUE TITLE
#copy deletes contents of directory

### ISSUE THREAD

**Issue by OzairP** [jprichardson/node-fs-extra#395]
### Environment
OS: OSX El Capitan 10.11.6
Node: v7.6.0 (using NVM) (As per #358)
NPM: 4.1.2
FS-Extra version:
```
├─┬ esdoc@0.4.8
│ └── fs-extra@0.26.5 
└── fs-extra@1.0.0 
```

### Code

```JS
import fs from "fs-extra";

fs.copy("../../Steam/GameCache/csgo/", "../../Users/Ozair/csgo_23", {"overwrite": true}, err => {
     if(err)
          reject(err);
     else
          fulfill("Transfer successful");
});
```

FS-Extra deletes the contents of the source directory and no files move onto the destination.

**Comment by manidlou** [comment]
@OzairP is there any specific reasons that you run very old version `@1.0.0` of `fs-extra`? As you probably know, the latest release is `v2.1.2`.

**Comment by OzairP** [comment]
Actually, it seems that I misread the documentation. I called `emptyDirSync` under the assumption that it checks if the dir is empty, but I was wrong when rereading the documentation. I apologize about that.
