### ISSUE TITLE
copySync freezes

### ISSUE THREAD

**Issue by sebakerckhof** [jprichardson/node-fs-extra#396]
I'm using fs-extra 2.1.2 in the latest electron version (1.6.2, via electron-forge) , based on node 7.4.

I've got a piece of code that looks like:
```js
      console.log(`Saving config`)
      try {
        console.log(`Backing-up current config file`)
        fs.copySync(this._configFile, this._previousFile);
      } catch (e) {
        console.log(`Error while backing up old config file`, error)
      }

      try {
        console.log(`Writing new config file`)
        fs.writeJsonSync(this._configFile, this.config, {
          spaces: 2
        })
      } catch (error) {
        console.log(`Error while writing config file`, error)
      }
```

When `this._configFile` does not exist, the following output is printed:

```
Saving config
Backing-up current config file
```

It never goes into the error or to the writing of the config. It seems to be frozen, while it should give an error that the origin path does not exist.

**Comment by manidlou** [comment]
Mmm.. that's strange! `copySync()` should throw `ENOENT` error if src doesn't exist. I try to reproduce the case, but when I run this,

```js
const fs = require('fs-extra')
try {
  fs.copySync('srcnotexist', 'dest')
} catch (err) {
  console.log(err)
}
```
It throws `Error: ENOENT: no such file or directory, stat 'srcnotexist'` error.

**Comment by RyanZim** [comment]
@sebakerckhof What's your OS?

**Comment by RyanZim** [comment]
@sebakerckhof ping?

**Comment by RyanZim** [comment]
Closing for lack of action.
