### ISSUE TITLE
ensureDir() does not work when a part of the given directory is still existing

### ISSUE THREAD

**Issue by JulianLang** [jprichardson/node-fs-extra#397]
Assume there already is a directory ```C:\User\some\path```. When trying to ensure the following directory nothing happens: ```C:\User\some\path\in\addition```. I expected that ```\in\addition``` would be created automatically. I think ensureDir will not work when a part of the directory structure already exists.

**Comment by RyanZim** [comment]
Works fine for me: https://runkit.com/57ebc041d4a27f140028fd78/58d295b037829f0014690594

Can you create a reduced test case?

**Comment by JulianLang** [comment]
Yes I will try and come back then

**Comment by JulianLang** [comment]
Okay, sorry it seems to be working for a simple example. I try to figure out what went wrong with my code, and may come back if I've found out.
