### ISSUE TITLE
Documentation for .ensureDir(...) and .emptyDir(...) not clear

### ISSUE THREAD

**Issue by kantenkugel** [jprichardson/node-fs-extra#399]
I am using bluebird to promisify this lib. I am using the only documented parameter of ensureDir/emptyDir to reject the Promise (only error is documented to be passed to the callback).

However, when one of those functions actually has to create the folder / folder structure, the first argument has the value of the created folder.

My question now is: is the first callback parameter always the created folder / undefined and the second parameter the actual error? Or are those 2 parameters mixed?

It would also be nice to clarify this in the docs.

**Comment by manidlou** [comment]
@kantenkugel I agree that `ensureDir()` is not clearly documented about callback parameters and should be updated. Sorry about the confusion. In fact, The same issue is already open. Please see #182.

Just for a quick answer, `ensureDir()` (which is an alias for `mkdirs`) returns the path of the first directory that is created as the second argument of the callback. Something like this:

```js
const fs = require('fs-extra')

fs.ensureDir('some/dir', (err, made) => {
  if (err) return console.error(err)
  console.log(made)
})
```

**Comment by manidlou** [comment]
Maybe that'd be better we close this as this one is somehow a duplicate of #182?

**Comment by kantenkugel** [comment]
That is strange... when I use it something like this:

```js
fs.ensureDirAsync('some/path')
.then(error => {
    if(error)
        return Promise.reject(error);
    ....
})
.catch(error => {
    console.log('error:', error);
})
```

My catch block gets thrown with the directory name as error-value. From my understanding I am only using the first argument of the callback. Does this have something to do with the promisification of blackbird?

**Comment by kantenkugel** [comment]
Ok it seems as bluebird correctly detects resolve/reject. Sorry for being dumb.
I just couldn't find the default promisifier that bluebird uses to check if I was correct
