### ISSUE TITLE
fs.copy throw unexplained error ENOENT, utime 

### ISSUE THREAD

**Issue by nirmelamoud** [jprichardson/node-fs-extra#40]
Hi

trying to copy a file from path a to another path 50% of the time, I get the following error
 Error: ENOENT, utime 'my target path'
 this happen right after I call fs.copy(oldPath, targetpath, function (error) { - -it get to the block with the above error - any idea ?

the file exist in the old path, but the strange thing is that it is also appeared on the target path , so the copy worked ???

what is the above error ? (what is the utime part of it) ?

I think it happens when fs.copy try to set the timestamp of the file after copying it, when I wrap it with try catch it never happened again - but the problem is that its not consistent it happen only in 50% of the times.

thanks

**Comment by AndyOGo** [comment]
same random `ENOENT` errors here, though the path is correct. Really weird.
Happened as I switched from sync to async APIs.

**Comment by RyanZim** [comment]
@AndyOGo Please open a new issue, preferably with a reduced test case. Thanks!
