### ISSUE TITLE
require('fs-extra') giving error in electron main process

### ISSUE THREAD

**Issue by gaikwadrahul20** [jprichardson/node-fs-extra#400]
`var app = require('app');`
`var fs = require('fs-extra');`
`var builder = require('xmlbuilder')`

at line 2 it is giving error:

> App threw an error when running [SyntaxError: missing ) after argument list]
This code is written in electron main process which uses node.js

**Comment by RyanZim** [comment]
@gaikwadrahul20 Please post the full error, including the stack trace. I suspect this is a problem with your code, not ours.

**Comment by gaikwadrahul20** [comment]
@RyanZim Thank you so much for the reply. I suspect the same first but then I have gone through the code and commented the second line i.e. `var fs = require('fs-extra');` and guess what the error's gone. sending here stack trace of the error.

![image](https://cloud.githubusercontent.com/assets/12632118/24828676/dd1a9354-1c7f-11e7-88b9-a951b885577c.png)

**Comment by RyanZim** [comment]
@gaikwadrahul20 Try running a linter on your JS code to find the syntax error.

**Comment by gaikwadrahul20** [comment]
I tried it is not giving any error.

**Comment by RyanZim** [comment]
Did you lint all your code? I don't know what's going on with your code, but I know this: if `fs-extra` released a syntax error, there would be plenty of other people complaining. I don't think this is an issue with `fs-extra`, so I'm going to close this.

One final thing to try is `rm -rf node_modules/ && npm install`, just in case you have a corrupted installation of `fs-extra`.

**Comment by jprichardson** [comment]
I'd add to this @gaikwadrahul20 - I've been using fs-extra in Electron for 1.5 years now (both renderer and main), and I've had no problems.

**Comment by erm3nda** [comment]
Case of me the debug version was using global fs-extra, while the compiled version had no fs-extra on node_modules, hence will now work.
