### ISSUE TITLE
Remove fs.spaces

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#401]
Perhaps I'm doing something wrong, but I can't get `fs.spaces` working.

Test case: https://runkit.com/57ebc041d4a27f140028fd78/58e92c306fa07e0013ccb3e6

@jprichardson ?

**Comment by jprichardson** [comment]
Maybe we should remove `fs.spaces`?

**Comment by RyanZim** [comment]
Suits me; it isn't documented anyhow; users who need it can use `jsonfile`. If people really complain, we can add it back.

**Comment by RyanZim** [comment]
PR done: https://github.com/jprichardson/node-fs-extra/pull/402

**Comment by RyanZim** [comment]
Fixed in #403; should be released in v3.0.0.
