### ISSUE TITLE
Cannot delete directory with .git

### ISSUE THREAD

**Issue by louisgv** [jprichardson/node-fs-extra#404]
If a directory has a `.git` directory, fs.remove will throw this error:

{ Error: ENOTEMPTY: directory not empty, rmdir 'sample/.git'
    at Error (native)
  errno: -66,
  code: 'ENOTEMPTY',
  syscall: 'rmdir',

**Comment by RyanZim** [comment]
Unable to reproduce. What's your OS, Node.js version, & fs-extra version?

**Comment by louisgv** [comment]
For some strange reason, after I clean up my setup and do it again, fs-extra was able to remove the directory :p...

Actually, I think it was after I upgrade my node version...

My current version are:
```
  "fs-extra": "^2.1.2"

uname -v
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64

node -v
v6.10.0
```

I think it's resolved for me. Let me know if I should close it :)
