### ISSUE TITLE
3.0.0 tag published with 'v' prefix

### ISSUE THREAD

**Issue by MylesBorins** [jprichardson/node-fs-extra#410]
Howdy... as mentioned in title... the 3.0.0 release was tagged without 'v'... this is breaking citgm.

If you plan to continue doing releases without the 'v' prefix let us know and we'll update our lookup table

**Comment by RyanZim** [comment]
Versions 2.0.0 and earlier omitted the `v` prefix. (Versions before 0.9.0 did include the prefix) Future versions will not include the `v` prefix for the foreseeable future.

Curious what you're using the git tags for.

**Comment by MylesBorins** [comment]
@RyanZim I've updated our lookup.

We use the git tags to grab the tarball from github. We use that tarball to build + test fs-extra in CI  when we are doing releases of Node.js as part of a larger smoke testing suite.

**Comment by RyanZim** [comment]
OK, didn't know that!

We'll try to keep the tags unprefixed from now on.
