### ISSUE TITLE
Add a function to expand paths on all platforms

### ISSUE THREAD

**Issue by mike-lischke** [jprichardson/node-fs-extra#413]
It would be super helpful if you could add a function that expands paths with special symbols (tilde comes to mind on *nix like platforms) or env variables (e.g. `"%TEMP%\resetvars.bat"` on Windows) to valid paths that can be consumed by the rest of the module.

**Comment by RyanZim** [comment]
Not a bad idea, but out of scope for this module. Would be a better fit for https://github.com/jprichardson/node-path-extra. I'd appreciate if you'd open an issue there.

Tilde functionality can be provided by https://github.com/sindresorhus/untildify

**Comment by RyanZim** [comment]
For reference: issue is here: https://github.com/jprichardson/node-path-extra/issues/25
