### ISSUE TITLE
fs.move and fs.copy are not success in version 2.1.2

### ISSUE THREAD

**Issue by divefox** [jprichardson/node-fs-extra#416]
I have error in the latest version of fs-extra. When I use it to copy or move the folder, it have the error like: 

```
Error: ENOENT
errno: -1,
code: 'ENOENT',
syscall: 'rename',
```

and my code is like these:
```js
fsx.move(mvsrc, mvdist, { overwrite: true }, err => {
  if (err) return console.error(err)
  console.log('success!')
});
```
Is there something I write wrong?
Thank you very much!

**Comment by RyanZim** [comment]
@divefox Your code looks fine. I think your problem is that `mvsrc` doesn't exist.
