### ISSUE TITLE
Add isEmpty and isEmptySync methods so that I don't need to use 'extfs' as well as 'fs-extra'

### ISSUE THREAD

**Issue by kruncher** [jprichardson/node-fs-extra#420]
It would be nice to avoid the need to be dependent on 2 separate packages `fs-extra` and `extfs` when doing file manipulations:
```javascript
const fs = require("fs-extra");
const extfs = require("extfs");
```

It would be nice if `fs-extra` included `isEmpty` and `isEmptySync` methods such that the following is possible:
```javascript
if (fs.isEmptySync(path)) {
    console.log("The specified directory is empty!");
}
````

or:
```javascript
fs.isEmpty(path).then(isEmpty => {
  if (isEmpty) {
    console.log("The specified directory is empty!");
  }
});
```

**Comment by jprichardson** [comment]
@kruncher can you elaborate on the use case?

**Comment by kruncher** [comment]
@jprichardson To determine whether or not a directory is empty or not.

To be more specific, in my current use case, I want to run some logic if the given directory is empty but I want to stay clear and present the end-user with an error message if it contains files and/or sub-directories.

The implementation provided by `extfs` does the job nicely and these two methods seem like a natural fit for `fs-extra` since both of these libraries augment the built-in `fs` with these extra functions.

**Comment by jprichardson** [comment]
> To be more specific, in my current use case, I want to run some logic if the given directory is empty but I want to stay clear and present the end-user with an error message if it contains files and/or sub-directories.

Can you elaborate more here? What logic do you want to run if it's empty? Why would you not just present an error message if the directory exists? 

I'm trying to figure out the strong use case of not just checking if the directory exists? i.e. why is that not good enough?

**Comment by kruncher** [comment]
> Why would you not just present an error message if the directory exists?
Because the empty directory is created by an entirely different process.

**Comment by Inve1951** [comment]
you could use the native `fs.readdir(path, cb)` with cb as:
```
function (err, files) {
  isEmpty = !files.length
  ...
}
```

no need for a whole library to avoid of 1 line of code.

hope this helps you.

**Comment by RyanZim** [comment]
@jprichardson What's the decision here?

**Comment by RyanZim** [comment]
Overall, this feels like a tiny edge-case not worth supporting. Closing at least for now.
