### ISSUE TITLE
Deprecate universalify

### ISSUE THREAD

**Issue by gagle** [jprichardson/node-fs-extra#426]
Related to [util.promisify](https://github.com/nodejs/node/compare/f72376d3230be7c968e392d59680bd01f8c20360...faf6654ff75e0f275afddfd980387235c3ddf103) and [Pomise support](https://github.com/jprichardson/node-fs-extra/pull/403)

**Comment by RyanZim** [comment]
@gagle util.promisify hasn't even been released yet. fs-extra follows the Node LTS support schedule, so it will be awhile until we can even think about this.

Further, util.promisify converts functions without backwards-compat to callbacks; I'm not willing to make that change in fs-extra ATM.

I vote to close and tag as `future`.

CC: @jprichardson @manidlou

**Comment by manidlou** [comment]
Sorry for the late reply! crazy schedule :anguished:! I also agree with @RyanZim in this regard.

**Comment by RyanZim** [comment]
OK, closing for now since we have unanimous vote from the maintainers on this.
