### ISSUE TITLE
outputJSONSync not defined

### ISSUE THREAD

**Issue by fatdem** [jprichardson/node-fs-extra#427]
Seems like a typo but it appears that there is a mismatch here from this [file](https://github.com/jprichardson/node-fs-extra/blob/master/lib/json/index.js).

```js
jsonFile.outputJsonSync = require('./output-json-sync')
jsonFile.outputJson = u(require('./output-json'))
// aliases
jsonFile.outputJSONSync = jsonFile.outputJSONSync
```

**Comment by RyanZim** [comment]
@fatdem Thanks for reporting; that's a nasty typo I introduced in v3.0.0 Will fix and patch release ASAP

**Comment by fatdem** [comment]
Thank you for the quick response!
