### ISSUE TITLE
flush file system on copy

### ISSUE THREAD

**Issue by Inve1951** [jprichardson/node-fs-extra#430]
i have to ensure that the files copied using `fse.copy()` are actually written to the physical drive.
i'm proposing a flag for it in the function's options object.

this could be achieved by using `fs.fsync()` or possibly even by simply listening for the `'finish'` event instead of the `'close'` event.

second way sure is really easy to implement. however i'm unsure what ["has been flushed to the underlying system"](https://nodejs.org/api/stream.html#stream_event_finish) actually means.

if it flushes to windows' write cache then it's unsufficient.

**Comment by RyanZim** [comment]
`copy()` used to use `finish`, see https://github.com/jprichardson/node-fs-extra/issues/326 for discussion.

**Comment by Inve1951** [comment]
too bad.

just experimented a bit and found out that `fs.createWriteStream()`'s returned `WriteSteam` object comes with the property `fd` which can be successfully used with `fsync()`.

it would have to be called before the `'end'` event since the file descriptor is already closed when it's emitted.

node.js docs reffer to [this](http://man7.org/linux/man-pages/man2/fsync.2.html) for `fsync(fd)`:
> fsync() transfers ("flushes") all modified in-core data of (i.e.,
       modified buffer cache pages for) the file referred to by the file
       descriptor fd to the disk device (or other permanent storage device)
       so that all changed information can be retrieved even after the
       system crashed or was rebooted.  This includes writing through or
       flushing a disk cache if present.

but
> Calling fsync() does not necessarily ensure that the entry in the
       directory containing the file has also reached disk.  For that an
       explicit fsync() on a file descriptor for the directory is also
       needed.

so after finished writing and flushing all files of a directory we'd have to do another `fsync()` on the directory.

**Comment by Inve1951** [comment]
wrote #432 as a starting point.
it seems to do what it should. i got no idea how to confirm that however.

**Comment by RyanZim** [comment]
@Inve1951 Have you actually verified that fs-extra as it currently exists is causing an issue here?

**Comment by Inve1951** [comment]
@RyanZim I'm not sure what issue you are refering too. This is about adding a feature.
Flushing the copied content is required to ensure it's intact after e.g. a power failure. (think backup system)

**Comment by Inve1951** [comment]
@RyanZim, @jprichardson

was able to confirm the PR's functionallity.

tested in a VM with WinXP SP3 x86 NTFS, both OS and disk write cache enabled.
forced a bluescreen after the callback returned. (immediately and after a few secs delay)

copy(src, dest, {sync: true/false}, cb)

with `sync: false` after system reboot:
 - all copied files present
 - MD5 missmatch for files bigger 30MB

with `sync: true` after system reboot:
 - all copied files present
 - no MD5 missmatches

**Comment by RyanZim** [comment]
@jprichardson I'm not sure if this is within scope for fs-extra. If we add this here, where else will we need to add it? Personally, I think this warrants a separate module if we're going to worry about this kind of low-level stuff.

CC: @manidlou

**Comment by manidlou** [comment]
@Inve1951 thanks for your help here. We all appreciate your work. However, I am on the same page as @RyanZim. I am personally not inclined to add this feature. Primarily because I think it somehow breaks the overall consistency of `fs-extra` functions, as @RyanZim pointed out:

> If we add this here, where else will we need to add it?

**Comment by RyanZim** [comment]
Based on the majority vote of the maintainers, I'm going to close this. @jprichardson feel free to reopen if you disagree.

**Comment by jprichardson** [comment]
I actually do think we should consider adding this feature in the future, but not in the existing PR and I think it should be a consistent interface across all functions (where it makes sense). I also don't know the best way we'd test this either. I'm in favor, but it's going to take a lot of work to get it done and I'm not sure the priority is there for this on our end as maintainers. Me personally, I'm not able to make it a priority, and I certainly won't volunteer the time of @RyanZim or @manidlou.

Open to your thoughts @Inve1951.

**Comment by Inve1951** [comment]
> I think it should be a consistent interface across all functions (where it makes sense).

I think so too. As i stated above my PR should be considered a starting point only. I wrote it for `copy()` since that's where i needed and missed it.

In my opinion it makes most sense in `copy()` and `copySync()` since those are the functions you'd use for creating a backup copy. (can't think of another use case)

Beyond that implementing the flush is a nobrainer if you understand the existing code's flow (which i didn't at first). All you need is a file descriptor.

If it's desired I'm willing to participate in implementing it, @jprichardson.

**Comment by jprichardson** [comment]
> If it's desired I'm willing to participate in implementing it, @jprichardson.

How can we test it?

**Comment by Inve1951** [comment]
We can run the old tests to confirm it didn't break existing functionality. But for testing the flush itself i'm afraid that's not possible entirely within Node.js.
If data was flushed can be checked by directly communicating to the storage device (via interrupts) from my understanding. Other than that crashing the OS and reading the data afterwards tells us if the OS' write cache was flushed. The storage device's flush could be confirmed the same way by taking away the power supply.
Btw it's best practice to have the storage device's write cache disabled and only use the one the OS provides. Because if you don't then the OS can never know for sure if data was written, unless it spams interrupts, which in my tests resulted in ~50% duration increase of write operations.
This is well observable when using the flush provided by my PR with large amounts of data (>1GB).

**Comment by Inve1951** [comment]
I went thru the node.js source code to find out how `fs.fsync()` knows that it finished.
Got completely lost in that _mess_ and ended up in `queue.h`.

If someone else wants to try, [this](https://github.com/nodejs/node/blob/master/src/node_file.cc#L785) is where you wonna start.

Best of luck.
