### ISSUE TITLE
outputFile does not automatically create parent directory

### ISSUE THREAD

**Issue by jheising** [jprichardson/node-fs-extra#431]
Lib Version: 3.0.1
Node Version: v6.10.2

For some reason `pathExists` at https://github.com/jprichardson/node-fs-extra/blob/master/lib/output/index.js#L16 always seems to return `true`.

The file path I'm using is relative to my cwd. This used to work in older versions, but seems to be broken in the current version.

**Comment by jheising** [comment]
I take that back. It appears to be broken in the older version too.

**Comment by jheising** [comment]
Appears to be a problem with relative paths in the node.js runtime.

**Comment by RyanZim** [comment]
I'm not sure if I follow your issue; perhaps try `path.resolve()` on the path?
