### ISSUE TITLE
Cannot read file using promises

### ISSUE THREAD

**Issue by lamuertepeluda** [jprichardson/node-fs-extra#434]
It looks like the library cannot override the fs built-in readFile method for usage with promises.

**Node v7.10.0**

```javascript
const fname = path.resolve('.', 'myfile.txt');
fs.readFile(fname, 'utf8').then(()=> console.log('success'))
```

yelds to `TypeError: Cannot read property 'then' of undefined`.

Same thing happens if I use async/await, of course. Falling back to readFileSync for now.

**Comment by RyanZim** [comment]
@lamuertepeluda Works fine for me: https://runkit.com/57ebc041d4a27f140028fd78/592d788062c30b00126ef82e

Are you using fs-extra v3+ ?

**Comment by lamuertepeluda** [comment]
Aww, my bad... I didn't notice I was stuck with 2.x. Updating resolved everything.
