### ISSUE TITLE
rimraf error: Promise.promisify(fs.removeSync`) without options

### ISSUE THREAD

**Issue by kirrg001** [jprichardson/node-fs-extra#437]
Hey 👋

I use bluebird (`3.5.0`) with `fs-extra` (`3.0.1`) and rimraf complains complains for me.

`Promise.promisify(fs.removeSync)(path)`
^ I am not using the options parameter.

Bluebird passes a function as second parameter.
I assume this need's fixing here and not in `bluebird`, but let me know.

```
AssertionError: rimraf: options should be object
    at rimrafSync (/Users/kirrg001/dev/ghost/ghost/node_modules/fs-extra/lib/remove/rimraf.js:234:10)
```

If i use `Promise.promisify(fs.removeSync)(path, {})`, it works.

Thank you!

**Comment by RyanZim** [comment]
@kirrg001 Why are you trying to promisify a sync method? That isn't necessary.

**Comment by kirrg001** [comment]
yeah just realised as well, haha.
Still throws an error. Close if you want 🙃
