### ISSUE TITLE
All methods are unresolved in IntelliJ

### ISSUE THREAD

**Issue by Ionaru** [jprichardson/node-fs-extra#440]
When I create example.js in IntelliJ:
```javascript
var fs = require('fs-extra');
var configFilename = 'example.json'
fs.removeSync(configFilename);
```

removeSync has the warning "Unresolved function or method removeSync()"

The package is in my node_modules
Using Node v8.1.1

**Comment by RyanZim** [comment]
Closing since this is an IntelliJ issue, not an fs-extra issue.

**Comment by graphee-gabriel** [comment]
Just in case anyone stumble upon here looking for the same thing than @Ionaru 
To fix this, simply add the module `@types/fs-extra` with npm/yarn.
Fixed the issue for me on intellij/webstorm.
