### ISSUE TITLE
Check the path is file?

### ISSUE THREAD

**Issue by EmpireWorld** [jprichardson/node-fs-extra#441]
How can i check the path is file using `fs-extra`?

I need a better way than `fs.stat`.

Thanks.

**Comment by RyanZim** [comment]
@EmpireWorld What's wrong with `fs.stat`? With `async/await`, it's easy:

```js
(await fs.stat(filename)).isFile()
```

With promises, it's not much harder:

```js
fs.stat(filename).then(stats => stats.isFile())
```

**Comment by EmpireWorld** [comment]
Nice. thanks i was used callbacks so it made it a little longer. next i will use this awesome method.

Thanks.
