### ISSUE TITLE
Move to using `util.promisify` to return correct value in promise

### ISSUE THREAD

**Issue by danielgindi** [jprichardson/node-fs-extra#442]
Node.js 8 has `util.promisify`, which calls the function at the `util.promisify.custom` symbol to return a custom promise.
This is used in the Fs module to return different values from the promise. 

For example, in the `read` method, instead of an array of the callback arguments, an object will be returned like `{ bytesRead: 1234, buffer: <Buffer 0x12 0x34 0x56 0x78> }`.

As `fs-extra` intends to be fs-compliant, it should return the correct promise also according to the docs at https://nodejs.org/api/fs.html.

Note:
This may introduce some breaking changes where promises in fs-extra returned arrays previously. Should be a major version release for moving to Node.js 8.

**Comment by RyanZim** [comment]
Yep, this is planned for the future. We just haven't gotten around to looking into this yet. Care to contribute?

Here's the polyfill we'd probably use: https://www.npmjs.com/package/util.promisify

Note that we need to do this in a way that is backwards compatible to Node 4+ That might take a fair amount of hacking to get this working.

**Comment by danielgindi** [comment]
`Symbol` is supported in Node 4 so shouldn't be too complicated

**Comment by danielgindi** [comment]
Well after looking into it again - I don't think we even need the polyfill.
As any "extra" fs methods are not documented to have special promise return values using `promisify`, only the native fs methods like `read` and `write` do.

So we only need to make sure that the universal versions of them will work with `promisify` - if `promisify` is present.
If it's not present, then all should continue to work as it used to.

**Comment by danielgindi** [comment]
I have a non-breaking-changes branch, will create a PR soon after a few tests

**Comment by danielgindi** [comment]
Damn. graceful-fs is wrapping the functions too.

**Comment by RyanZim** [comment]
See https://github.com/jprichardson/node-fs-extra/pull/444#issuecomment-310134745; merging into https://github.com/jprichardson/node-fs-extra/issues/436.
