### ISSUE TITLE
[feature request] fs.copy don't work really like 'cp -r'

### ISSUE THREAD

**Issue by bySabi** [jprichardson/node-fs-extra#443]
on shell terminals:
 `cp -r foder1 dest` will create `dest\folder1`

but with `fs.copy('folder1', 'dest')` only `folder1` content is copy to `dest`

Will be really useful add a option for include `folder1` on copy.  Maybe 
`{ src: true }`  or  `{ parent: true }` or `{ includeParent: true `} ..

**Comment by RyanZim** [comment]
Basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/323; same logic applies here.
