### ISSUE TITLE
Please add some info about Webpack 2^+Uglify issues when bundling

### ISSUE THREAD

**Issue by iongion** [jprichardson/node-fs-extra#446]
Please add some foot notes about using fs-extra with webpack and uglifyjs(IE: AWS lambda environment). It simply is incompatible due to uglifyjs being incompatible with arrow functions or other ES6 node features you use. And there is a lot of time spend to actually find out why.
Usually, to speed up things, node_modules are ignored in standard webpack configs, but this will make it impossible to minify, that is why my webpack 2.0 config exclude is like this:

```
var transpiledSystemModules = [
  'universalify',
  'fs-extra',
];
var excludeExpression = [
  'node_modules(?!(\\/|\\\\)(',
  transpiledSystemModules.join('|'),
  '))'
].join('');
var rules = [
  {
    test: /\.js$/,
    exclude: [
      // /node_modules/
      // /node_modules(?!(\/|\\)(universalify|fs-extra))/
      new RegExp(excludeExpression),
    ],
    use: [{
      loader: 'babel-loader',
      options: {
        presets: ['es2015']
      },
    }],
  },
  {
    test: /\.html|\.txt\.ejs\.jst$/,
    use: 'raw-loader'
  },
];
```

**Comment by RyanZim** [comment]
I don't get the point. Minifying Node.js code is an exception, not the normal use-case. No reason to clutter the readme with this info.

@jprichardson What's your opinion?

**Comment by jprichardson** [comment]
> @jprichardson What's your opinion?

This is out of scope. There are rare use cases where you'd ever want bundle fs-extra in webpack.
