### ISSUE TITLE
Buffer.alloc error on node 4.4

### ISSUE THREAD

**Issue by justinhelmer** [jprichardson/node-fs-extra#452]
https://github.com/jprichardson/node-fs-extra/pull/451

**Comment by RyanZim** [comment]
fs-extra is supposed to support Node 4.4. What version of fs-extra are you using? What method gives this error?

**Comment by justinhelmer** [comment]
`Buffer.alloc` does not exist in 4.4, which is used in fs-extra 3.0 and higher

**Comment by RyanZim** [comment]
I know that `Buffer.allloc` doesn't exist in Node 4.4. But fs-extra 3+ doesn't use it. If I'm wrong, please tell me which method is using it.

**Comment by justinhelmer** [comment]
It gets called by Tar.create I can find the specific source after lunch

**Comment by RyanZim** [comment]
fs-extra doesn't have any method like `Tar.create`; are you using another library on top of fs-extra?

**Comment by justinhelmer** [comment]
I'm so sorry, submitted to the wrong repo.

I apologize for wasting your time, please close
