### ISSUE TITLE
remove force: true

### ISSUE THREAD

**Issue by guohuihot** [jprichardson/node-fs-extra#453]
like

```
$.del.sync(delFile, {
                    force: true
                });
```

**Comment by RyanZim** [comment]
@guohuihot Where did you get that code sample? That doesn't look like `fs-extra` code.

**Comment by guohuihot** [comment]
https://github.com/sindresorhus/del#force

If you want to delete the file does not exist, it will be wrong, but this is not the result I want;

**Comment by guohuihot** [comment]
fs.remove('a.js', {force: true})

**Comment by RyanZim** [comment]
I don't know what you're trying to get across; is this a bug or a feature request?

**Comment by RyanZim** [comment]
Closing for lack of action.
