### ISSUE TITLE
fs.move fails with EEXIST even when overwrite option is enabled

### ISSUE THREAD

**Issue by laurent22** [jprichardson/node-fs-extra#454]
It doesn't happen all the time but sometimes I'm getting the following error message when using `move()` with the `overwrite` options:

```
{ Error: EEXIST: file already exists, link '/tests/fuzzing/sync/.sync/214b820bf10c4744994fb9a876e433d3.md_1498950555952' -> '/tests/fuzzing/sync/214b820bf10c4744994fb9a876e433d3.md'
    at Error (native)
  errno: -17,
  code: 'EEXIST',
  syscall: 'link',
  path: '/tests/fuzzing/sync/.sync/214b820bf10c4744994fb9a876e433d3.md_1498950555952',
  dest: '/tests/fuzzing/sync/214b820bf10c4744994fb9a876e433d3.md' }
```

I'm calling it like this, as a promise: `fs.move(oldPath, newPath, { overwrite: true });` and most of the time it works but sometime it's going to generate the EEXIST error. Any idea what could be the reason?

**Comment by RyanZim** [comment]
@laurent22 What OS is this happening on? 

Is there any chance another application could be writing to `newPath` at the same time?

**Comment by laurent22** [comment]
This is on Windows 10 under WSL (latest version). To be fair though I had all kind of problems with the file system under WSL including with reputably reliable software like SQLite. So I'm not sure if it's an issue that fs-extra can handle better or simply a bug in WSL that Microsoft needs to fix.

**Comment by RyanZim** [comment]
Yeah, probably a WSL issue. I'd welcome a PR if someone can figure out how to fix this (without too much trouble), but I'm personally not sure this is something the core team should spend time trying to fix.

CC @jprichardson @manidlou

**Comment by manidlou** [comment]
> Yeah, probably a WSL issue.

Think so too.

As @laurent22 said:

> I had all kind of problems with the file system under WSL including with reputably reliable software like SQLite.

I am not sure this is even a bug from our end!

> I'm personally not sure this is something the core team should spend time trying to fix.

Agreed.

**Comment by lauredecaudin** [comment]
Hi, I have the same problem with my Windows 10 VM (which is not WSL if I understand well, if not, please tell me)

**Comment by tormozz48** [comment]
@RyanZim @manidlou 
I have the same floating issue on:
```
Distributor ID:  Debian
Description:  Debian GNU/Linux 8.10 (jessie)
Release:  8.10
Codename:  jessie
```
Version of `fs-extra` is 7.0.1

**Comment by tormozz48** [comment]
I think that this issue can occur while perform multiple move operation like this:
```js
Promise.all([
    './foo/bar1',
    './foo/bar2',
    ....
    './foo/bar999'
].map((dest) => fs.move('./mySrc', dest, {override: true})));
```

Each of move operation include mkdirp itself and can fail on creation common root folder in concurrency mode.

**Comment by laurent22** [comment]
Could be. When I had this bug, I was randomly creating/deleting many directories and files using a fuzzing program so it could indeed be some issue with the way `move()` handles concurrency.
