### ISSUE TITLE
writeJson and writeJsonSync don't work in hidden files

### ISSUE THREAD

**Issue by CGReinhold** [jprichardson/node-fs-extra#457]
Using [winattr](https://www.npmjs.com/package/winattr) to set a file to hidden and I'm not able to write json over it anymore. Without this line it works properly, but with it the file can be read but not written:

`winattr.setSync(myFilePath, { hidden: true });`

**Comment by RyanZim** [comment]
@CGReinhold Can you still write to the file using `fs.writeFile`?

**Comment by CGReinhold** [comment]
fs.writeFile and fs.writeFileSync also don't work. The following error is emmited when using file.writeFile:

Error: EPERM: operation not permitted, open 'C:\Users\mypath'

for while, in order to make my code work I'm doing this:

```
winattr.setSync(myFile, { hidden: false });
fs.writeJsonSync(myFile, arquivo)
winattr.setSync(myFile, { hidden: true });
```

**Comment by RyanZim** [comment]
This indicates this is an actual Node.js issue; closing as `invalid`.
