### ISSUE TITLE
Copy Errors should have code property like Node

### ISSUE THREAD

**Issue by Faline10** [jprichardson/node-fs-extra#461]
Requested enhancement: fse is a stand-in for fs and as such you would expect similar errors, including the code property. One should be able to check `error.code ===' EEXIST'`, for example. Instead we are checking `err.message === 'Source and destination must not be the same.'`

Update: This is specifically for calls to copy. I see that move, for instance, has error codes.

Node reference: https://nodejs.org/api/errors.html#errors_node_js_error_codes

**Comment by RyanZim** [comment]
PR welcome to add any error codes where it makes sense; however, src and dest being the same for a copy operation isn't really an `EEXIST` error.

**Comment by RyanZim** [comment]
Closing for lack of action.
