### ISSUE TITLE
copySync empty folder into an existing file

### ISSUE THREAD

**Issue by czb** [jprichardson/node-fs-extra#464]
Copy an empty folder into an existing file. I would expect, an error should be thrown as the file cannot be overwritten by a folder. Since the folder is empty, no error is thrown and no folder is created. If the folder is not empty, `ENOENT` is thrown.

**Comment by RyanZim** [comment]
This behavior is consistent in both `copy` & `copySync`. The behavior does seem a little weird, though. To be honest, this is what I hate about `copy`; there are a million edge cases + always one more that you haven't thought of.

CC @jprichardson @manidlou for thoughts here; so far I haven't pinned down _why_ it's doing this.

**Comment by RyanZim** [comment]
@jprichardson @manidlou ping?

**Comment by manidlou** [comment]
Yeah I also confirm the faulty behavior! However, I applied a possible fix for this issue in #502 that prevents this from happening. When rewriting `copy` is finished, then related changes will be applied to `copySync` as well since they need to be consistent.

**Comment by manidlou** [comment]
Fixed in 5.0.0 :tada:
