### ISSUE TITLE
ensureFileSync vs ensureDirSync

### ISSUE THREAD

**Issue by czb** [jprichardson/node-fs-extra#465]
When `ensureDirSync` is called on a folder that already exists as a file, `EEXIST` is thrown as expected.

When `ensureFileSync` is called on a file that already exists as a folder nothing is thrown.

Should not the two behaviours be the same? IMHO either both should throw or none of them should throw.

**Comment by RyanZim** [comment]
Yep, confirmed. The issue is that we're just checking if the path exists; we should stat the path and check if it's a file instead.
