### ISSUE TITLE
readJson async returning undefined

### ISSUE THREAD

**Issue by awjreynolds** [jprichardson/node-fs-extra#467]
Using your example the code, the promised based version of readJson returns an undefined object.
```js
const fs = require('fs-extra');


export async function getContextData() {
  fs.readJson('./package.json', (err, packageObj) => {
    if (err) console.error(err);
    console.log(packageObj.version); // => 0.1.3
  });

  // Promise Usage
  fs.readJson('./package.json')
  .then(packageObj => {
    console.log(packageObj.version); // => 0.1.3
  })
  .catch(err => {
    console.error(err);
  });

  const contextFile = './context.json';
  const jsonData = await fs.readJson(contextFile, { throws: true });
  return jsonData;
  // fse.readJson(contextFile, { throws: true }, (err, jsonData) => {
  //   return jsonData;
  // });
}
```

```
Output:
2.0.0
/Users/adamreynolds/Work/p4vis/node_modules/jsonfile/index.js:46
    callback(null, obj)
    ^

TypeError: callback is not a function
    at /Users/adamreynolds/Work/p4vis/node_modules/jsonfile/index.js:46:5
    at /Users/adamreynolds/Work/p4vis/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:503:3)
```

**Comment by RyanZim** [comment]
Seems to be working fine for me: https://runkit.com/57ebc041d4a27f140028fd78/597208635afec60012d4de47

What version of fs-extra are you using?

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by sixertoy** [comment]
Yo!
Strange behavior here too

Context:
- Node v7.8.0
- Yarn v0.27.5 + experimental workspaces (mono repo)
- fs-extra v4.0.1

```bash
fse.readJson(file)
  .then(() => {
    console.log('loaded');
  });
```
> `TypeError: Cannot read property 'then' of undefined`

- Fail when installing fs-extra with yarn wokspaces
- OK when installing fs-extra as a current project dependency

**Comment by RyanZim** [comment]
@sixertoy Please open a separate issue for that with a minimal test case repo.

**Comment by GaikwadPratik** [comment]
@RyanZim  I can confirm that I am getting the same error mentioned by @awjreynolds

`TypeError: callback is not a function
 at /server/node_modules/jsonfile/index.js:46:5
 at /server/node_modules/graceful-fs/graceful-fs.js:78:16
 at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)`

I am verified it in all major versions of `fs-extra". So far I can reproduce this behavior at any time for `readJson`. I even tried passing an empty object to force the overloaded function call. But it doesn't work at all.

**Comment by RyanZim** [comment]
@GaikwadPratik Please open a new issue with a reduced test case.
