### ISSUE TITLE
Delete all files but not folders in a folder

### ISSUE THREAD

**Issue by vk011** [jprichardson/node-fs-extra#471]
Really good plugin and I know there is functionality to clear a folder but that deletes both files and folders within the folder, would be good to have the option to delete all files in a folder but not folders within that folder.

**Comment by RyanZim** [comment]
This seems like an edge case to me; @jprichardson @manidlou Thoughts?

**Comment by jprichardson** [comment]
Yep, edge case. Use https://github.com/jprichardson/node-klaw
