### ISSUE TITLE
[fse.copy]copy a folder to another folder failed without any infomation

### ISSUE THREAD

**Issue by andyforever** [jprichardson/node-fs-extra#476]
Like this:
While there are 3 folders, folder `b` is under `a`
`cp -r a/b c/` 

`fse.copy('a/b', 'c')` will not succes unless there is a 'b' folder under folder 'c'

**Comment by RyanZim** [comment]
What version of fs-extra are you using?

**Comment by jrtitus** [comment]
I think @andyforever's confusion is coming from the fact that, while they have similar parameters, `cp -r a/b c/` and `fse.copy('a/b', 'c')` are not equivalent commands.

`cp -r a/b c/` - Copies the `b` directory and all files underneath it into `c`

`fse.copy('a/b', 'c')` - Copies everything under the `b` directory into `c`

`fse.copy('a', 'c')` is the equivalent command in this case.

> Tested with fs-extra v 4.0.1.

**Comment by andyforever** [comment]
2.0.0 @RyanZim

**Comment by RyanZim** [comment]
You could try using fs-extra 4.1.0. Also, take a look at @jrtitus's comment; it's a pretty good explanation of the differences between `cp -r` and `copy()`.

**Comment by andyforever** [comment]
@jrtitus @RyanZim ok.Thanks.
