### ISSUE TITLE
ensureFileSync does not create a file

### ISSUE THREAD

**Issue by jrtitus** [jprichardson/node-fs-extra#477]
The documentation for [`ensureFileSync()`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureFile-sync.md) makes it sound like if the file specified does not exist, it is created (along with the directory elements), and if the file does exist, it is not modified:

> **Ensures that the file exists.** If the file that is **requested to be created** is in directories that do not exist, these directories are created. **If the file already exists, it is NOT MODIFIED.**

On the other hand, `ensureFileSync()`'s "alias" `createFileSync()` DOES create the file if it doesn't exist (and still does not modify it if it does exist), but the function is undocumented.

The term "alias" implies the same behavior with a different name, which is not the case here.

> fs-extra@0.30.0

> $ node --version 
v6.11.1

**Comment by RyanZim** [comment]
They are exact aliases. FWIW, your version of fs-extra is outdated, the latest version is 4.1.0. If you can make a reduced test case demonstrating this behavior in the latest version, I'd be glad to look into it.

**Comment by jrtitus** [comment]
Works correctly in 4.0.1 (latest version installed using `npm i --save-dev fs-extra`). Thanks for the quick reply. I should have uninstalled/re-installed to make sure I had the latest version in the first place.
