### ISSUE TITLE
[Windows] fs.copy error with {preserveTimestamps}

### ISSUE THREAD

**Issue by laggingreflex** [jprichardson/node-fs-extra#478]
`fs.copy(src, dest, {preserveTimestamps: true})` fails on Windows with error:

>EPERM: operation not permitted, open 'D:\...(dest)'

The error occurs in this part of the code:

Edit: Correction : <strike>https://github.com/jprichardson/node-fs-extra/blame/master/lib/copy/ncp.js#L113</strike>

https://github.com/jprichardson/node-fs-extra/blame/master/lib/copy/ncp.js#L116
```js
        if (preserveTimestamps) {
          utimes.utimesMillis(target, file.atime, file.mtime, function (err) {
            if (err) return onError(err) <<
            return doneOne()
          })
```

I forked the library and these 2 tests are also failing: 

```
2 failing

  1) copy > modification option > when modified option is turned on should have the same timestamps on copy:

      Uncaught AssertionError [ERR_ASSERTION]: 1502926785048 === 1502926785000
      + expected - actual

      -1502926785048
      +1502926785000

      at lib\copy\__tests__\copy-preserve-time.test.js:64:20
      at Array.forEach (<anonymous>)
      at copy (lib\copy\__tests__\copy-preserve-time.test.js:46:17)
      at doneOne (lib\copy\ncp.js:228:16)
      at lib\copy\ncp.js:118:20
      at fs.close.closeErr (lib\util\utimes.js:61:23)
      at node_modules\graceful-fs\graceful-fs.js:43:10
      at FSReqWrap.oncomplete (fs.js:135:15)

  2) copySync > modification option > when modified option is turned on should have the same timestamps on copy:

      AssertionError [ERR_ASSERTION]: 1502926785030 === 1502926785000
      + expected - actual

      -1502926785030
      +1502926785000

      at lib\copy-sync\__tests__\copy-sync-preserve-time.test.js:56:20
      at Array.forEach (<anonymous>)
      at Context.it (lib\copy-sync\__tests__\copy-sync-preserve-time.test.js:40:15)
```

**Comment by RyanZim** [comment]
@laggingreflex Are you on 32-bit windows?

**Comment by laggingreflex** [comment]
64-bit, Window 10

**Comment by laggingreflex** [comment]
Expanding on the `utimes.utimesMillis` the error comes from here: 

https://github.com/jprichardson/node-fs-extra/blame/a061b2507ccdff474a80172c2f5db637bfa53905/lib/util/utimes.js#L55

```js
  fs.open(path, 'r+', (err, fd) => { // <<< 
    if (err) return callback(err)
    fs.futimes(fd, atime, mtime, futimesErr => {
      fs.close(fd, closeErr => {
        if (callback) callback(futimesErr || closeErr)
      })
    })
  })
```

If I replace it with just this fixes the issue for me:

```js
  fs.utimes(path, atime, mtime, futimesErr => {
    if (callback) callback(futimesErr)
  })
```

But the tests still don't pass. Using `fs.utimes` vs. `fs.open`>`fs.utimes`>`fs.close` seems to be required for millisecond precision and it's discussed here https://github.com/jprichardson/node-fs-extra/pull/141#issuecomment-114126331

**Comment by laggingreflex** [comment]
Also interesting that the error doesn't occur when running tests, but the tests still fail.

**Comment by laggingreflex** [comment]
I found out in my case the issue was that the destination file was set to "read only". 

I think these might be two separate issues. 

* Tests failing due to millisecond issue

* In my issue the original file (src) has read-only attribute checked, so when `fs.copy` copies the file it copies and sets that attribute as well (with `fs.chmod`) and so sets the read-only attribute. Then when it wants to change the access/modified time it cannot open the file for editing.

**Comment by laggingreflex** [comment]
#479 fixes my issue.

**Comment by RyanZim** [comment]
v5 significantly rewrote `copy()`, assuming this is fixed.
