### ISSUE TITLE
prependFile

### ISSUE THREAD

**Issue by cwtuan** [jprichardson/node-fs-extra#481]
Does it support `prependFile(path, content, encoding)`?

**Comment by RyanZim** [comment]
No, not sure this is an edge-case worth supporting.

Also note that assuming your dealing with Strings and not Buffers, and the file isn't too big to load into memory, you can just do this:

```js
fs.readFile(path, encoding)
  .then(fileContent => fs.writeFile(path, content + fileContent, encoding))
```

@jprichardson @manidlou Thoughts?

**Comment by jprichardson** [comment]
Nope, at least not for now.

**Comment by cwtuan** [comment]
@RyanZim Yes, it could implement this like
```
fs.prepend = function(path: string, content: string, encoding: string) {
   fs.readFile(path, encoding)
    .then(fileContent => fs.writeFile(path, content + fileContent, encoding))
}
```

This would be nice if this package provide this function.
