### ISSUE TITLE
Copy does not seem to work on Windows

### ISSUE THREAD

**Issue by haroldo-ok** [jprichardson/node-fs-extra#482]
Even testing something as simple as:

	fs = require('fs-extra');
	fs.copy('C:\\temp\\x.c', 'C:\\temp\\blah');

It gives the error:

	Error: EPERM: operation not permitted, unlink 'C:\temp\blah'

**Comment by manidlou** [comment]
@haroldo-ok what is the version of your node and `fs-extra`?

**Comment by RyanZim** [comment]
It's a permission issue; you don't have correct permissions to be messing with `C:\temp\blah`.

**Comment by haroldo-ok** [comment]
@manidlou: I can't remember the exact version right now, but I had just installed it using npm, without specifying a version number, and immediately proceeded to test it on node's REPL.
@RyanZim: The error message may indicate that, but that cannot be the case, otherwise calling 'copy' or 'xcopy' from the Windows console wouldn't have worked.

**Comment by RyanZim** [comment]
Closing for lack of action.
