### ISSUE TITLE
fs.readFile causes race condition

### ISSUE THREAD

**Issue by adius** [jprichardson/node-fs-extra#483]
I used 

```js
const fileContent = await fsp.readFile(filePath, 'utf8')
```

and had to replace it with:

```js
const fileContent = await new Promise((resolve, reject) => {
      require('fs')
        .readFile(filePath, 'utf-8', (error, data) => {
          if (error) reject(error)
          else resolve(data)
        })
    })
```
because it caused a race condition or something.
This is completely crazy. How can this even happen?

**Comment by RyanZim** [comment]
@adius Are you using the latest version of `fs-extra`?

**Comment by adius** [comment]
yes, v4.0.1

**Comment by RyanZim** [comment]
We can't really debug this issue without a reduced test case repo that demonstrates this race condition.

**Comment by adius** [comment]
> is the 15th most popular package on npm

That's why this is so scary 😳

> Frankly, I suspect you have a race condition in your code

I hope so 😅. We are using `async / await`, maybe that's a problem somehow?

**Comment by RyanZim** [comment]
Well, probably the easiest way to get race conditions is to use `await` inside a `forEach`, `map`, or similar Array method. The entire array will be iterated in parallel without `await`ing for each iteration to finish.

**Comment by adius** [comment]
Oh boy. I hate npm / yarn. I have no idea how a package manager is able to install a program, report is installed, listing it correctly with `npm info` and yet installing it in some almost correct state.

After deleting all node_modules dirs, all caches, all lock-files, and reinstalling, it now works.

Luckily! … this bug was just too strange 😟

**Comment by adius** [comment]
Thanks for your patiently help! 😊

**Comment by RyanZim** [comment]
Well, glad to hear it's working! No idea how that could have happened.
