### ISSUE TITLE
chmod 666 is wrong

### ISSUE THREAD

**Issue by zengming00** [jprichardson/node-fs-extra#484]
https://github.com/jprichardson/node-fs-extra/blob/ab2fae9ae10379b6d1633128e8f35b5d872a89e8/lib/remove/rimraf.js#L120

use chmod 0o666

**Comment by RyanZim** [comment]
Yep, good catch; sorry, this slipped through the cracks somehow. Relevant rimraf commit: https://github.com/isaacs/rimraf/commit/38b907fd64656923cc4004ce353e1ad101bd8d1c
