### ISSUE TITLE
mkdir doesn't support space seperated multiple paths

### ISSUE THREAD

**Issue by Vandivier** [jprichardson/node-fs-extra#486]
in bash et al, this will make two directories:
`mkdir hi hey`
in node-fs-extra it doesn't.

Will yall be implementing or accept a PR?

**Comment by RyanZim** [comment]
@Vandivier `fs-extra` isn't an exact clone of the way bash works. In many ways, bash's behavior can be a bit implicit. We feel developers should be explicit about their intentions. `mkdir hi hey` doesn't really explicitly tell you whether two directories are being created, or if a single directory containing a space in the filename is being created.

Creating two directories asynchronously is pretty simple with Promises:
```js
Promise.all(['hi', 'hey'].map(d => fs.mkdir(d)))
```
