### ISSUE TITLE
Remove directory with many files

### ISSUE THREAD

**Issue by LaurensRietveld** [jprichardson/node-fs-extra#487]
When removing a directory with many (say, 1million+) files, JS runs out-of-memory. This is probably because fs-extra first lists of all the files in memory.
I get that this is difficult to fix with the fs API that nodejs give us, but thought I'd add this as issue anyway (should nodejs support something like a dir-entries iterator, or even a proper `remove` implementation)

**Comment by RyanZim** [comment]
Honestly, if you're dealing with file trees this big, you're best off just shelling out to `rm -rf` (or the windows equivalent, depending on the OS).

`fs-extra` uses a modified version of https://github.com/isaacs/rimraf, which is built by the CEO of npm and former BDFL of Node.js. If he didn't figure out a way to handle such big directories, I don't see the point of us trying to do it.

**Comment by LaurensRietveld** [comment]
Using rm - rf is what I ended up using. As I said, I don't expect this issue to be fixed due to the nodejs (fs) api limitations, but thought I'd add it here as a reference for other users anyway

**Comment by RyanZim** [comment]
Going to close this out, since I don't have any good ideas for fixing this.
