### ISSUE TITLE
EPERM: operation not permitted, mkdir

### ISSUE THREAD

**Issue by yoyo837** [jprichardson/node-fs-extra#488]
First, I'm sorry my English is very bad.

I call copySync in the main thread can work fine, but when the asynchronous call it  is report error (post 
 => /sync). In addition, I use ensureDirSync to create a directory that does not exist right, it's work fine.

Looks like it can only write a file can not write a directory

The code is large, find the keywords '**svfs.copy**' and '**nuxtBuild**' please.

My main code is here:
server/fs.js
```javascript
import fs from 'fs'
import fsextra from 'fs-extra'

export default {
  /**
   * 创建目录，如果不存在
   * @param {string} dir
   */
  mkdir(dir) {
    if (dir == null) {
      return
    }
    fsextra.ensureDirSync(dir)
  },
  /**
   * 复制文件
   * @param {string} src
   * @param {string} dest
   */
  copy(src, dest) {
    if (src == null || dest == null) {
      return
    }
    console.log(`copy from ${src} to ${dest}`)
    fsextra.copySync(src, dest)
  },
  /**
   * 清空目录/删除目录下所有
   * @param {string} dir
   */
  emptyDir(dir) {
    if (dir == null) {
      return
    }
    this.removeFileFromDir(dir, file => {
      return file.toLowerCase() !== '.gitkeep'
    })
  },
  /**
   * 删除目录下部分文件/目录
   * @param {string} dir
   * @param {function} fn
   */
  removeFileFromDir(dir, fn) {
    if (dir == null) {
      return
    }
    fn = typeof fn === 'function' ? fn : file => {
      return true
    }
    fs.readdirSync(dir).forEach(file => {
      if (fn(file)) {
        this.removeFile(`${dir}/${file}`)
      }
    })
  },
  /**
   * 删除文件/目录
   * @param {string} file
   */
  removeFile(file) {
    if (file) {
      console.log('del', file)
      fsextra.removeSync(file)
    }
  }
}

```

server/index.js
```javascript
import path from 'path'
import Koa from 'koa'
import KoaRouter from 'koa-router'
import Boom from 'boom'
import bodyParser from 'koa-bodyparser'
import c2k from 'koa2-connect'
import proxy from 'http-proxy-middleware'
import { Nuxt, Builder } from 'nuxt'
import svfs from './fs'

const app = new Koa()
const router = new KoaRouter()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 9086

// Import and Set Nuxt.js options
const config = require('../nuxt.config.js')
config.dev = !(app.env === 'production')

// config.build.buildDir 不配置默认.nuxt
// fsextra.removeSync(/^\.nuxt/) // fsextra.removeSync 不支持正则
svfs.removeFileFromDir('./', file => {
  return file.toLowerCase().startsWith('.nuxt')
})

// 是否正在构建
const Separator = '-'
// let isBuilding = false
let buildIndex = 0
let nuxt
// Instantiate nuxt.js
function nuxtBuild() {
  // isBuilding = true
  if (nuxt) {
    config.build.buildDir = `${nuxt.options.buildDir.split(Separator)[0]}-${++buildIndex}` // 换一个目录
  }
  const innerNuxt = new Nuxt(config) // 如果重复利用Nuxt, nuxt在build的时候是不能提供服务的, 所以每次new
  if (nuxt == null) { // 初始化的时候第一次没有，直接赋值
    nuxt = innerNuxt
  }

  const pagePath = path.join(__dirname, '../pages') // nuxt的pages页面目录
  svfs.emptyDir(pagePath) // 清空
  try {
    // EPERM: operation not permitted, mkdir: When the asynchronous 'sync' calls it
    svfs.copy(config.skin.getPagesPath.apply(innerNuxt), pagePath) // 复制新的 
  } catch (e) {
    console.error(123)
    console.error(e)
    svfs.mkdir(Date.now().toString()) // work fine
  }

  const builder = new Builder(innerNuxt)
  builder.build().then(() => {
    if (nuxt === innerNuxt) {
    } else {
      const temp = nuxt
      nuxt = innerNuxt
      temp.close()
    }
    // isBuilding = false
    console.log('Build completed!')
  }).catch(e => {
    console.error(e)
    process.exit(1)
  })
}

// Build in development
const doAPIReg = /\.do$/
const cp = c2k(proxy({
  target: 'http://localhost:8082/portal/'
}))

if (config.dev) {
  router.get(doAPIReg, cp)

  router.post(doAPIReg, cp)

  nuxtBuild()
}

app.use(bodyParser())

app.use(router.routes())
app.use(router.allowedMethods({
  throw: true,
  /* eslint-disable new-cap */
  notImplemented: () => new Boom.notImplemented(),
  methodNotAllowed: () => new Boom.methodNotAllowed()
}))

router.post('/sync', (ctx, next) => {
  console.log('收到同步请求 ---> ', ctx.request.body)
  ctx.status = 200
  ctx.response.body = {
    result: 123
  }

  nuxtBuild.apply(this)
})

router.get(/(^\/_nuxt(?:\/|$))|(^\/(?:__webpack_hmr|$)$)/, async function(ctx, next) {
  ctx.status = 200 // koa defaults to 404 when it sees that status is unset

  await new Promise((resolve, reject) => {
    ctx.res.on('close', resolve)
    ctx.res.on('finish', resolve)
    nuxt.render(ctx.req, ctx.res, promise => {
      // nuxt.render passes a rejected promise into callback on error.
      promise.then(resolve).catch(reject)
    })
  })
})

app.listen(port, host)
console.log(`Server listening on ${host}:${port}`)

```

**Comment by yoyo837** [comment]
![1787be23-4e35-4ad8-9cf5-c6a29498c996](https://user-images.githubusercontent.com/6134547/30208171-daaa511e-94c4-11e7-8e1f-62ef7652eaec.png)

**Comment by yoyo837** [comment]
![304a0147-5de8-4c94-a73d-0f6e4680b52c](https://user-images.githubusercontent.com/6134547/30208519-6aa02478-94c6-11e7-896f-77517636d944.png)

**Comment by RyanZim** [comment]
You're trying to handle async errors with `try`/`catch`, which doesn't work. You've either got to pass a callback into async methods, handle the returned promise, or `await` them.

**Comment by yoyo837** [comment]
I'm sorry you misunderstood what I meant. I don't have any asynchronous function that use fs-extra, using synchronous function all of them. I mean that I called the nuxtBuild function twice. nuxtBuild used the fs-extra synchronization function. The first call is the node main thread, and the second is triggered after the koa receives the request . It is always synchronized inside the nuxtBuild.

**Comment by yoyo837** [comment]
Also, the asynchronous function use try catch cannot handle the error at all, but my screenshot I uploaded says that the error has been handled by try catch, because it is a true synchronization function.

**Comment by RyanZim** [comment]
You are using `fs-extra` async functions. `copy` & `emptyDir` are both async functions.

**Comment by yoyo837** [comment]
@RyanZim 
No No No...
I wrap the functions, `copy `& `emptyDir`  in my file >>>**server/fs.js.**<<< Please look carefully, they are not fs-extra's functions of the same name. I've already shown the full content of this file when I opened the issue. https://github.com/jprichardson/node-fs-extra/issues/488#issue-256194201

my `copy` function called `fsextra.ensureDirSync`，`emptyDir` called `fsextra.removeSync`.

`fsextra.ensureDirSync` and  `fsextra.removeSync` is sync functions.

**Comment by RyanZim** [comment]
Sorry, didn't notice that part. Honestly, I cannot debug your issue without a minimal, reproducible, test case.

**Comment by yoyo837** [comment]
@RyanZim 
I created a repo to debug the problem. [Here](https://github.com/yoyo837/node-fs-extra-488)
Step:
1. yarn run dev
2. Request `http://localhost:086/sync` as post with HTTP tool like [`HttpRequester`](https://github.com/tommut/HttpRequester) in Firefox add-on

**Comment by jprichardson** [comment]
@yoyo837 you're going to need to distill this down into a small and minimal reproducible test case. We're not going to debug your entire code.

**Comment by yoyo837** [comment]
I think I might know what the problem is: I empty it and copy the target directory from another is also being watched to modify the file.

Thanks for your reply. @RyanZim  and @jprichardson :)
