### ISSUE TITLE
Would you accept a PR for a function returning the total size of a specified directory?

### ISSUE THREAD

**Issue by tkambler** [jprichardson/node-fs-extra#489]
Something akin to:

```
lib.getTotalSize('./some/dir')
    .then((size) => {
        // Size === total combined size (in bytes) of all files held within specified directory
    });
```

**Comment by RyanZim** [comment]
Not sure if this is within scope of this project; @jprichardson @manidlou ?

---

Have you tried any of these?

- https://www.npmjs.com/package/get-folder-size
- https://www.npmjs.com/package/readify

**Comment by tkambler** [comment]
@RyanZim I'm currently using `get-folder-size`, but having a built-in function within `fs-extra` would be nice, as it would negate the need for yet another module. The functionality seemed like it was within scope, but maybe not. That's why I'm asking. :)

**Comment by manidlou** [comment]
Not sure either!

**Comment by RyanZim** [comment]
Closing as per @errorx666
