### ISSUE TITLE
Use `fs.copyFile` where applicable

### ISSUE THREAD

**Issue by benjamingr** [jprichardson/node-fs-extra#490]
`fs.copyFile` has landed with Node.js 8.5.0. You should consider using it for copying files when/where applicable.

**Comment by RyanZim** [comment]
@benjamingr Thanks for bringing this up. Man, I'm so happy to have this in core. :tada: 

One question I have: How does `copyFile` handle symlinks?

---

Todo list:

- [ ] I need to get on top of things and get this promisified in https://github.com/normalize/mz; our fs promisify implementation is a fork of mz and I like to port changes back to them.
- [ ] We need to update our fs promisification to mirror the changes on mz.
- [ ] We need to implement this in `copy` & `copySync`, still falling back to our methods in older envs. @manidlou Let's do this after your changes are merged. This should definitely be semver-major; there will probably be os-specific stuff to work-around.

**Comment by RyanZim** [comment]
Self-assigning for now to get the ball rolling, may ask others to help later though.

**Comment by manidlou** [comment]
> One question I have: How does copyFile handle symlinks?

@RyanZim I tested when src is a symlink, and `copyFile()` creates a regular file for dest.

**Comment by metabench** [comment]
I'm looking at this project as a way to preserve timestamps while copying files (in Windows), but have run into the EPERM error while copying symlinks. Please be wary of using another method that copies the symlinks but does not preserve timestamps if it's an option to do so.

**Comment by RyanZim** [comment]
@manidlou Do you want to work on using `copyFile` where it's supported, falling back to our current implementation in older versions of Node? The work should be based against the `develop` branch.

**Comment by manidlou** [comment]
> @manidlou Do you want to work on using copyFile where it's supported, falling back to our current implementation in older versions of Node? The work should be based against the develop branch.

Sure thing.

**Comment by RyanZim** [comment]
PR done for `copy`: #505 

@manidlou We also need to use `fs.copyFileSync` in `copySync` when possible.

**Comment by manidlou** [comment]
> @manidlou We also need to use fs.copyFileSync in copySync when possible.

That's right! I am working on it.

**Comment by manidlou** [comment]
It's just `copySync` needs serious cleanup (its implementation is not consistent with new changes that we applied to `copy`), and I am willing to work on it. But, I think it's better to add the native `fs.copyFileSync` first, then work on other parts of it! let me know if there is any objections!

**Comment by manidlou** [comment]
PR updated for `copySync`: #505.

**Comment by RyanZim** [comment]
OK, I think everything that needs done here is done in `develop`; closing out for now; will be released in the next major version.

**Comment by arcanis** [comment]
@RyanZim By any chance, do you have an idea when the next version will be released? The copy rewrite listed in the 5.0.0 milestones seems to have been merged in #502, so is "cannot copy a directory within itself" the last missing part?

**Comment by RyanZim** [comment]
@arcanis AFAIK, everything's ready for the release, I'd have to double-check. I've just been too busy to release it. I'll try to hit it soon, though it doesn't suit me tonight. Ping me if I don't have 5.0.0 out within a week.
