### ISSUE TITLE
preserve timestamps on move files

### ISSUE THREAD

**Issue by lbell** [jprichardson/node-fs-extra#493]
Any chance to add a `preserveTimestamps` option on move? Or should I just use something like:

```
fs.copy(src, dest)
.then(() => {
  fs.remove(src)
  .then(() => {
    console.log('Copied & Removed!')
  }).catch(err => {
    console.error(err)
  })
}).catch(err => {
  console.error(err)
})
```

Edit: I just found something in the works: https://github.com/jprichardson/node-fs-extra/pull/342

**Comment by RyanZim** [comment]
Sorry for the slow response here. PR welcome; not sure if it'd be easier to cleanup the existing PR or reimplement it from scratch.

**Comment by RyanZim** [comment]
Given that no one has stepped up to implement this since 2017, I'm gonna close this one out. If somebody wants this badly and is willing to do the work to implement it, please comment below.
