### ISSUE TITLE
Consider linking to a cross-platform API for checking devices and partitions

### ISSUE THREAD

**Issue by philippefutureboy** [jprichardson/node-fs-extra#504]
I am currently building an utility to detect the filesystem alongside some other properties of the volumes and devices on the computer. The utility will support macOS, Windows and Linux.

On Linux I use the commands `df -T`, `fdisk -l` and `lsblk` to obtain my information, while on mac I use `diskutil info -all` and `wmic logicaldisk get` on Windows. I will provide as much of a unified interface as possible, returning an hash of all devices and volumes with properties `id`, `node`, `whole`, `parent`, `name`, `size`, `description`, `physical block size`, `logical block size`, `read only`, `removable`, `filesystem type`, `mounted`, `mount point`, `blocks`, `space available`, `space used`, `total space`.

Interested? :)

**Comment by RyanZim** [comment]
Sounds like a great project, but this belongs in a separate module IMO. `fs-extra` uses only native fs methods; it never shells out. Perhaps we could link to your project from our readme, though.

**Comment by philippefutureboy** [comment]
All good, np :)
This is still under development, but you can find the repo here - https://github.com/qzdio/node-fsfilesystem
Out of curiosity, by native methods you mean from the node js `fs` package?

**Comment by RyanZim** [comment]
> Out of curiosity, by native methods you mean from the node js fs package?

Yes

**Comment by RyanZim** [comment]
Gonna close this out for now; @philippefutureboy feel free to comment below or open a new issue when your module is "complete" (though good modules are never truly complete, I know). :smiley_cat:

**Comment by philippefutureboy** [comment]
Sounds good, I should be finished with the first version either today or tomorrow!

**Comment by philippefutureboy** [comment]
Could I ask you for a small favor? I am currently running my test using my own setups, but there is no guarantee that my setups cover all the use cases possible. Hence if you have computers under Linux, MacOS or (especially) Windows, it would be great if you could send me a .txt file of the output of the respective command for the OS:

* Linux: `df -T && echo "" && echo "**********" && echo "" && fdisk -l && echo "" && echo "**********" && echo "" && lsblk -o kname,fstype,mountpoint,label,ro,rm,model,type -P`
* MacOS: `diskutil info -all`
* Windows: `wmic logicaldisk get Caption,Description,DeviceID,FileSystem,FreeSpace,Name,Size,VolumeName`

It would be a great help :)

**Comment by philippefutureboy** [comment]
After an unexpectedly herculean effort (and some expected delay):

[fs-filesystem](https://github.com/qzdio/node-fs-filesystem)

**Comment by RyanZim** [comment]
Haven't tested but looks OK overall. Reopening to discuss linking from the README. @jprichardson @manidlou What are your thoughts here?

**Comment by philippefutureboy** [comment]
Hey guys! Any update? :)

Cheers 🚀

**Comment by RyanZim** [comment]
@jprichardson @manidlou ping!?

**Comment by jprichardson** [comment]
@philippefutureboy very cool. This should be a separate module for the time being. When I feel `fs-extra` has stability and can do things like `chmodr` and regex on files, we can revisit. But until then, I'd like to keep what you have as a separate module. We'd accept a PR though to the readme to inform people that this is a complementary module.

**Comment by philippefutureboy** [comment]
@jprichardson thanks for the comment! As you can see, PR is up :3

**Comment by RyanZim** [comment]
Considering closed by #534. Tagging as future to remind about merging.
