### ISSUE TITLE
Handling copy of folder inside of other folder

### ISSUE THREAD

**Issue by gabrielstuff** [jprichardson/node-fs-extra#508]
Hello,

I'm trying to move a folder containing a lot of other folders inside an new folder.
Unfortunately one of the copy fails : 

```
errno: -17,
  code: 'EEXIST',
  syscall: 'symlink',
  path: 'Versions/Current/Resources',
```

What I was expecting was that all other folders copy and only those with existing name failed.

I'm using `fs.moveSync(file, path.join(targetDir, path.basename(file)))` on OSX with node `8.9.0`

Thanks,

G

**Comment by RyanZim** [comment]
@gabrielstuff This is intended behavior; if you want to delete the destination before beginning to move files, pass the `overwrite` option: https://github.com/jprichardson/node-fs-extra/blob/master/docs/move-sync.md#movesyncsrc-dest-options
