### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by brajeshchandra2002** [jprichardson/node-fs-extra#510]
Hi ,
We have installed fs-extra module into our project .
While compiling we are facing "Module not found: Error: Can't resolve 'fs'" exception.
fa module refereed in fs-extra inner library.
How to resolve this please suggest.

**Comment by RyanZim** [comment]
What are you using to compile your code?

**Comment by brajeshchandra2002** [comment]
Hi ,

Thanks for your response.
It's working now,
I have added target:node in webconfig file.

**Comment by manidlou** [comment]
Closing this since the user is no longer experiencing the issue.
