### ISSUE TITLE
Add issue template

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#513]
What do you think of adding [issue template](https://github.com/blog/2111-issue-and-pull-request-templates)?

**Rationale**
When users create a new issue, it is useful (and sometimes required) to know what their OS, node, and fs-extra versions are. Some users provide them when they create the issue, but not all of them. If they don't specify the required supporting information, usually our first question would be to ask about their OS, node, and fs-extra versions. So, by having an issue template, we can be ahead of ourselves and jump into resolving issues instead of waiting for the user to respond to our first question of OS, and library versions!

**Comment by RyanZim** [comment]
Fine with me!

**Comment by manidlou** [comment]
Alright! I'll add it then.
