### ISSUE TITLE
fs.copy | fs.copySync failing silently

### ISSUE THREAD

**Issue by mikemackay** [jprichardson/node-fs-extra#515]
Hi,

I'm trying to simply copy a directory, and all it's inclusive files, into another (in my case, replicate into an output folder), however this fails using either method without any errors. For example:

```
fs.copySync('./shared', './output', function(err) {
    if (err) return console.error(err);
    console.log("success!")
});
```

When running this, the copy doesn't take place and all I see in the console is:

> ./shared

So no error message or debug info. I'm using Node v8.9.1 and fs-extra 4.0.2 on a Mac.

Any ideas or suggestions?

Thanks,

Mike

**Comment by RyanZim** [comment]
You're passing a callback to `copySync`. Either use `copy` and pass a callback, or use `copySync` and don't pass a callback.

**Comment by mikemackay** [comment]
Ah jees, sorry - one of those weeks, thanks @RyanZim 

(Sorry I di also mean to tag this as 'question').

**Comment by RyanZim** [comment]
No Problem

(BTW, you can't tag issues unless it's your repo or you're a collaborator at the repo; so you didn't forget anything there)
