### ISSUE TITLE
copy "archive" option (cp -a)

### ISSUE THREAD

**Issue by aikar** [jprichardson/node-fs-extra#522]
It would be nice if an archive option for copy was provided to mimic -a on cp, to copy a file/directory exactly as it was in the source.

at least primarily, file owner and file permissions

**Comment by RyanZim** [comment]
We already preserve permissions by default, and we have a `preserveTimestamps` option for preserving timestamps.

Not particularly clear on how file ownership works in Node.js, maybe the rest of the team knows more? @jprichardson @manidlou

**Comment by aikar** [comment]
it would be something to worry about when ran with sudo/root, to avoid the file being owned by root, to keep original owner.

https://nodejs.org/api/fs.html#fs_fs_chown_path_uid_gid_callback

**Comment by RyanZim** [comment]
Given that I haven't heard anything from the rest of the team, I'm gonna say PR welcome. @aikar You want to try this?

**Comment by manidlou** [comment]
Yeah as @RyanZim said, we already have `preserveTimestamps` option and we set the file permissions (mode) through `fs.chmod()` after the copy is completed by default. But currently we don't do anything for ownership.

According to `cp` man page, `cp -a` means `preserve=all` which is `preserve the specified attributes (default: mode,ownership,timestamps), if possible additional attributes: context, links, xattr, all`.

**Comment by manidlou** [comment]
So the question is do we want to set the file ownership by default like what we currently do for mode or we wanna make it optional like `preserveTimestamps`?

**Comment by manidlou** [comment]
@jprichardson @RyanZim @JPeer264 ?^

**Comment by RyanZim** [comment]
IMO, our default behavior should match [`fs.copyFile`](https://nodejs.org/api/fs.html#fs_fs_copyfile_src_dest_mode_callback), and any deviation from that should be an option, if supported.

I am a bit curious how frequently you'd be running as root though; which is the primary reason you'd want this feature.

**Comment by RyanZim** [comment]
As per https://github.com/jprichardson/node-fs-extra/issues/912; `fs.cp` is coming to Node core, and options there will be dictating our feature set, so closing as wontfix.
