### ISSUE TITLE
question: How to list files copied or written

### ISSUE THREAD

**Issue by joemidi** [jprichardson/node-fs-extra#525]
Is there a way to log out the files that have been copied over or files that have been written by `fs-extra` ?

```
write bar/index.html
copy  foo/js/main.js -> bar/js/main.js
copy  foo/styles/style.css -> bar/styles/style.css
```

**Comment by RyanZim** [comment]
No, there's nothing built into fs-extra to do this. Why?

**Comment by jprichardson** [comment]
You could output in a function passed to `filter`?

**Comment by RyanZim** [comment]
Closing for lack of action.
