### ISSUE TITLE
move function excute successfully when the overwrite option is false 

### ISSUE THREAD

**Issue by jiazhengwen** [jprichardson/node-fs-extra#526]
- **Operating System:** win7 x64
- **Node.js version:** 7.9.0
- **`fs-extra` version:** 4.0.3

move function excute successfully when the overwrite option is false

**Comment by RyanZim** [comment]
I'm not sure I understand?

**Comment by manidlou** [comment]
yeah @jiazhengwen what do you mean exactly?

**Comment by jiazhengwen** [comment]
@RyanZim @manidlou 

Operating System: win7 x64
Node.js version: 7.9.0
fs - extra version: 4.0.3
function: move

precondition:buld and testbuild folder already exist
code:
fs.move(__dirname + "/build", __dirname + "/testbuild", { overwrite: false }, function(err) {
  console.log(err);
});

expect: Error:EEXIST: file already exists
actual result: move success, testbuild is overwritten.

**Comment by manidlou** [comment]
Aakh! @RyanZim another OS inconsistency! and again another weird behavior (error code) from Windows!

@jiazhengwen what happens is, when `{overwrite: false}` and dest is a directory that already exists, `fs.link` which is internally used by `move()`, on Windows oddly returns `EPERM` error and not `EEXIST` error! :flushed: 

Currently, part of `move()` logic is when `EPERM` error happens, that is most likely a cross-device error and it correctly (as it is documented) performs the move operation. The thing is, Windows is being a bitch here and returns a different error code! which means we have to tweak our implementation to handle OS specific behavior on that.

**Comment by RyanZim** [comment]
Is this related to https://github.com/jprichardson/node-fs-extra/issues/492?

**Comment by manidlou** [comment]
> Is this related to #492?

Kind of. In #492, `EPERM` error not being called. Here, it is being called while not expected to be called!

From all of these, it is obvious to me that we shouldn't rely on `fs.link` and `EPERM` error code! We should come up with more concrete logic for `move()`.

**Comment by manidlou** [comment]
After all of these, I believe `move` needs major reconsideration anyway! I'll open an issue addressing that.

**Comment by RyanZim** [comment]
@manidlou any progress here?

**Comment by manidlou** [comment]
Worked on it a bit, then I got distracted! I'll try to finish it this weekend.

**Comment by RyanZim** [comment]
Fixed in `v6-dev`; will be released later this month.
