### ISSUE TITLE
Is it possible to add a filter to fs-extra.emptyDir() method?

### ISSUE THREAD

**Issue by dark19940411** [jprichardson/node-fs-extra#527]
- **Operating System: Mac OS 10.13.1**
- **Node.js version: v9.0.0**
- **`fs-extra` version: 4.0.2**
When I'm using emptyDir() method, it always clear the whole given directory which I don't want it to. I want to keep some files down. So my question is: Is it possible to add a filter to fs-extra.emptyDir() method?

**Comment by RyanZim** [comment]
@dark19940411 Why not just call `fs.readdir()` and filter the results, then remove the files you don't want? I don't like the idea of `emptyDir` not actually emptying a directory.

Example code:
```js
fs.readdir('dir').then(files => {
  return Promise.all(files.filter(filterFn).map(file => fs.remove(file)))
})
```
If you want to create the directory if it doesn't exist, call `fs.mkdirp('dir')` first.

**Comment by dark19940411** [comment]
@RyanZim That'll do! Seems like I miss the `remove` function. Thanks anyway.
