### ISSUE TITLE
filter function breaks after first false 

### ISSUE THREAD

**Issue by i-am-dror** [jprichardson/node-fs-extra#530]
- Operating System: mac high sierra (10.13.2)
- Node.js version: v8.6.0
- `fs-extra` version: 5.0.0

filter function breaks after first false 

```js
const fse = require('fs-extra');
const imgList = require("./list.json");
const src = './src';
const dest = './dist';
const namesInList = (element) => {
  const isInList = imgList.list.find((v) => { return element.indexOf(v) > -1; });
  return isInList !== undefined;
};
const filterFunc = (path) => {
  return namesInList(path);
};

fse.copySync(src, dest, { filter: filterFunc });
```

**Comment by RyanZim** [comment]
You're returning `false` for directories, and when you return `false` for a directory, it doesn't recurse into that directory. You need to check that you're dealing with a file when filtering; like this:

```js
const fse = require('fs-extra');
const imgList = require("./list.json");
const src = './src';
const dest = './dist';
const namesInList = (element) => {
  const isInList = imgList.list.find((v) => { return element.indexOf(v) > -1; });
  return isInList !== undefined;
};
const filterFunc = (path) => {
  const stats = fs.statSync(path);
  return stats.isFile() && namesInList(path);
};

fse.copySync(src, dest, { filter: filterFunc });
```

**Comment by i-am-dror** [comment]
so how can i recurse for directories? even after implementing your changes the script breaks after first false.

**Comment by RyanZim** [comment]
Sorry, wrote that too fast. The line `return stats.isFile() && namesInList(path);` should read `return !stats.isFile() || namesInList(path);` instead.

**Comment by i-am-dror** [comment]
thank, that did the trick
