### ISSUE TITLE
Module not found in AWS Lambda function

### ISSUE THREAD

**Issue by scriptPilot** [jprichardson/node-fs-extra#533]
Unfortunately I cannot use the module in a AWS Lambda function. With lodash, for example, it works well.

Works
```
const lodash = require('lodash')
exports.handler = (event, context, callback) => {
  callback(null, 'everthing fine');
}
```

Works not
```
const fs = require('fs-extra')
exports.handler = (event, context, callback) => {
  callback(null, 'everthing fine');
}
```

Both modules properly installed.

**Comment by RyanZim** [comment]
Is it properly installed?

**Comment by manidlou** [comment]
Also please make sure you add everything in the root directory to your zip file including `node_modules` directory.

**Comment by scriptPilot** [comment]
@manidlou - Good hint, with `npm install --prefix ./lambda-folder/` it works! :-)
