### ISSUE TITLE
Missing/unhelpful stacktrace

### ISSUE THREAD

**Issue by Xerillio** [jprichardson/node-fs-extra#543]
I'm having trouble locating where errors are thrown because I'm not getting any useful stacktraces from what I expect is fs-extra. A case in point:
```javascript
// test.js
const fse = require("fs-extra");

// The path "C:/d/e" doesn't exist, thus writing a file should fail
const path = "C:/d/e/f.txt";
fse.writeFile(path, "Some content")
    .then(() => console.log("success"))
    .catch(err => {
        console.log(err.stack);
    });
// Console outputs:
// Error: ENOENT: no such file or directory, open 'C:\d\e\f.txt'
//     at Error (native)
```

I would expect the stacktrace to include a reference to this file.
Perhaps it makes sense to note that this is also the case when I'm running a test in Typescript using Mocha and async/await instead of Promises.

Is this intended?

- **Operating System: Win10**
- **Node.js version: 6.11.0**
- **`fs-extra` version: 5.0.0**

**Comment by RyanZim** [comment]
If you use `fs.writeFile` with a callback instead of `fse.writeFile`, you won't get any better stack traces. That's how system-level errors look in Node.js
