### ISSUE TITLE
Adding copy/move progress information. It will be really useful in a lot of cases

### ISSUE THREAD

**Issue by vasylhoban** [jprichardson/node-fs-extra#545]

**Comment by vasylhoban** [comment]
@jprichardson Can you think about adding functionallity of showing move/copy progress? Appreciate!

**Comment by RyanZim** [comment]
What kind of information do you want? How would the API look like?

**Comment by vasylhoban** [comment]
When you move or copy something (file or folder) with fs.move/fs.copy, it will be good to have ability to see percantage and amount(in bytes) of copied/moved information. Aslo I need the execution time of this operation.

**Comment by RyanZim** [comment]
IDK, this is going to be very complex to implement. I'm inclined to say this is out of scope. @jprichardson @manidlou @JPeer264 thoughts?

**Comment by vasylhoban** [comment]
I've found only one solution for this github.com/freeall/progress-stream. But sadly I need to say that this library can work only with single files and only with copy operation.

**Comment by JPeer264** [comment]
I did some research on this topic. It is quite hard to implement this, as it is just possible to measure the progress of each file (not just JavaScript). So we have to calculate the filesizes ahead of time - this might tend to performance issues (this is just an assumption). I'm joining @RyanZim's mind and think it will be out of scope

**Comment by RyanZim** [comment]
@JPeer264 I was thinking perf would be an issue as well. I'm gonna close this out, if someone on the team objects, please reopen.

**Comment by vasylhoban** [comment]
@RyanZim @JPeer264  Understood. Thanks guys for your time. Actually I am going to try to implement this  feature in my own project. If you can give some articles or some additional information which can help me to develop this I will really appreciate.

**Comment by JPeer264** [comment]
> If you can give some articles or some additional information which can help me to develop this I will really appreciate.

Sure. In the case of [cpy](https://github.com/sindresorhus/cpy/blob/master/index.js#L77-L82) this was implemented by showing the percentage with the file length. In `cpy` the files were already found by `glob`, so it's already known how many files there are (we do it differently). 

`rsync` is also capable of doing something like that (according to [that](https://serverfault.com/a/441724)), but it's implemented in C - I also didn't look in the source code, so I can't share the info where exactly this got implemented.

**Comment by manidlou** [comment]
@vasylhoban I'm not sure but you may find [progress](https://github.com/visionmedia/node-progress) useful too.

**Comment by vasylhoban** [comment]
Thanks guys. Will try to figure out with this tomorrow

**Comment by mrchantey** [comment]
Progress and eta can be achieved by diffing directory sizes at some regular interval.
Here's an [example](https://gist.github.com/mrchantey/1c99d909836c65e8ac438d2bae2f09d2) using [fs-extra](https://www.npmjs.com/package/fs-extra) and [get-folder-size](https://www.npmjs.com/package/get-folder-size).
