### ISSUE TITLE
why shut my copy task when i wanna to copy a dir with use filter function

### ISSUE THREAD

**Issue by moonrailgun** [jprichardson/node-fs-extra#552]
https://github.com/jprichardson/node-fs-extra/blob/a0d44c1773a72870ecfa1ff378b80a388fb445ef/lib/copy/copy.js#L59-L65

example:
```javascript
fs.copy(srcDir, destDir, {
  filter: () => {
    console.log('run filter')
    return false
  },
}, (err) => {
  if (err) return console.error(err);

  console.log('success!');
});
```
shut down in first file copy!  

i have no idea why about use `cb()` when run `handleFilter `. maybe i just wanna copy a dir and hope to filter some file which i dont want to copy   
is this a reasonable design?

**Comment by RyanZim** [comment]
You're consistently returning `false` from your `filter`, which indicates you don't want to copy anything, so fs-extra just stops.

**Comment by moonrailgun** [comment]
@RyanZim ,i mean although i always return `false`, it should log `run filter` many times if my `srcDir` has many files.  
but just log once and done

**Comment by manidlou** [comment]
@moonrailgun you are strictly returning `false` in your filter function. The way that `copy` handles filter is that if filter function returns `false`, it doesn't do anything. If you want to use a filter function, you essentially need to specify some sorts of conditions. IDK, at least you can set your filter function returns `true` on your src directory, if you wanna see some logs!

**Comment by moonrailgun** [comment]
@manidlou @RyanZim 
Well above code is just a demo. and i write another demo to express my mind.  

now , i have a dir like this:
```
.
├── index.js
└── src
    ├── a
    ├── b
    └── c
```

and the index.js is a test script like this:
```javascript
const fs = require('fs-extra');

fs.copy('./src', './dist', {
  filter: function(src) {
    if(src.indexOf('b') >= 0) return false;//  i dont want to copy file b
    return true;
  }
}, (err) => {
  if (err) return console.error(err);

  console.log('success!');
})
```

Then , i cd to this dir and run `node index.js`  
console output `success!` but the tree is not changed

```
├── index.js
└── src
    ├── a
    ├── b
    └── c
```

and then, i change my `index.js` line 5  
from `if(src.indexOf('b') >= 0) return false;` to `if(src.indexOf('d') >= 0) return false;`(always return true in filter function), everything will be okay.
```
├── dist
│   ├── a
│   ├── b
│   └── c
├── index.js
└── src
    ├── a
    ├── b
    └── c
```

my `fs-extra` is latest version in npm:5.0.0

**Comment by manidlou** [comment]
Mmm...! @moonrailgun I guess you don't get your desired results because your filter condition is based on the src path string, and we overwrite the src and dest with their full paths while we shouldn't! I blame myself on that!

In order to make sure about this, will you please change your filter condition to something like this? If my guess is true, your code should work with these changes.

```js
const fs = require('fs-extra');
const path = require('path');

fs.copy('./src', './dist', {
  filter: function(src) {
    const basename = path.basename(src)
    if(basename.indexOf('b') >= 0) return false;//  i dont want to copy file b
    return true;
  }
}, (err) => {
  if (err) return console.error(err);

  console.log('success!');
})
```

**Comment by moonrailgun** [comment]
@manidlou well this work, but not my mind.  
its not a good demo because some external cause. like the file path, you know.  
its my fault, I apologize.

but plz look at the follow code:
```javascript
const fs = require('fs-extra');

fs.copy('./src', './dist', {
  filter: () => {
    const isPass = Math.random() < 0.5;
    console.log(isPass);
    return isPass;
  },
}, (err) => {
  if (err) return console.error(err);

  console.log('success!');
  return null;
});
```

if the pass return false in first times, or second times. the task is done. and or return false not the first times, its run.

and i find why its done . because the first times and second times the src is the root dir. if my filter function not pass it, its throw a error and done my copy task.

i just want to copy dir with `.gitignore` file. and the root path not to pass it.

maybe add some tips in readme file? hopes can help others who happened same problem like me.


thanks for your help

**Comment by manidlou** [comment]
@moonrailgun the proposed fix #554 is under review. It will be most likely published in the next release.

**Comment by moonrailgun** [comment]
Good change! same path for filter func can avoid some problem and avoid use `path.relative` in every function loop every times!
thanks for your change

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/554, will be in the next release later this month.
