### ISSUE TITLE
Add cwd option

### ISSUE THREAD

**Issue by kbrusinets** [jprichardson/node-fs-extra#556]
It would be nice to add "cwd" option for functions.
Example: `fs.copy(from, to, { cwd: rootDirectory });`

**Comment by RyanZim** [comment]
Why can't you do `fs.copy(path.join(rootDirectory, from), path.join(rootDirectory, to))`?

**Comment by kbrusinets** [comment]
I can and i did it this way, but i think using cwd option is prettier.

**Comment by RyanZim** [comment]
I don’t like the idea of adding it here, because that starts a slippery slope of adding it to move() etc. Also would complicate the filter option.

**Comment by RyanZim** [comment]
Closing for now, if any of the collaborators disagree, we can reopen.
