### ISSUE TITLE
Crash when have no access to write to destination file in copy 

### ISSUE THREAD

**Issue by coderaiser** [jprichardson/node-fs-extra#56]
When I try to copy file and I have no access to write to distillation, my [application](http://cloudcmd.io) is crashing with error:
```js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/home/io/name.js'
```
There is example of code I use:
```js
var fse  = require('fs-extra');

fse.copy(from, to, function(error) {
    console.log(error);
});
```
Looks like there is a [problem in ncp module](https://github.com/AvianFlu/ncp/pull/39). But author staying quite. Maybe `ncp` could be changed with another module which do the same, but more correct?

**Comment by jprichardson** [comment]
Added a test for this: https://github.com/jprichardson/node-fs-extra/commit/4cc4c2eac656fb2e6fcb0f7a00d3a3037aa584a2 Was fixed awhile ago.
