### ISSUE TITLE
Possible to include wildcards in delete?

### ISSUE THREAD

**Issue by newmanw** [jprichardson/node-fs-extra#57]
Would be nice to be able to delete based on wildcards.

    fs.remove('/tmp/something.*', function(err) { ...

**Comment by jprichardson** [comment]
This should actually be possible now that `rimraf` supports wildcards (`fs-extra` depends upon `rimraf`). Closing.

**Comment by pomber** [comment]
How do you use wildcards?  
Looks like there is no way to set `disableGlob `to false in remove functions.

**Comment by jprichardson** [comment]
> How do you use wildcards?

You can't. Your best bet is to use a file system walker like https://github.com/jprichardson/node-klaw and match using a filter, and then remove.

**Comment by pomber** [comment]
Shouldn't it be possible using just rimraf with disableGlob false?

**Comment by jprichardson** [comment]
> Shouldn't it be possible using just rimraf with disableGlob false?

Sure, but IIRC, we have it hardcoded to false. So you'd then have to include `rimraf` if you want to do that.

**Comment by jwmann** [comment]
Are we still not able to use wildcards?
Why can't we pass `{ glob: true }` to `fs.remove()` so `rimraf` can do the job?

**Comment by RyanZim** [comment]
We have a fork of `rimraf` that doesn't include globbing. Globbing just makes everything far more complicated, and we're not willing to take that on ATM.
