### ISSUE TITLE
Where to find changelog

### ISSUE THREAD

**Issue by jacobq** [jprichardson/node-fs-extra#574]
I noticed that v6.0.0 was just released (thank you for your work), and would like to know where I can find a list of breaking changes. The [release page](https://github.com/jprichardson/node-fs-extra/releases/tag/6.0.0) doesn't seem to have any information. Was this just to drop Node 4.x support or are there API changes that I should examine before upgrading my application?

**Comment by jprichardson** [comment]
In the file `CHANGELOG.md`: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#600--2018-05-01 😄

**Comment by jacobq** [comment]
Ah, thank you. I should've thought to look for a file like that but had only searched the README.
