### ISSUE TITLE
How to copy contents of a directory into root

### ISSUE THREAD

**Issue by erok415** [jprichardson/node-fs-extra#576]
Hi there,
How do I do the equivalent of `cp -r [directory]/. ../../` or `cp -r ui/build/. .` ?

I'm trying to copy the contents of a build directory into the root application directory but without the containing build directory.

Thanks for your help.
Erik

**Comment by manidlou** [comment]
@erok415 have you tried something like this?!

```js
const fs = require('fs-extra')

const src = 'ui/build'
const dest = './'

fs.copy(src, dest, err => {
  if (err) return console.log(err)
  console.log('done')
})
```

**Comment by manidlou** [comment]
@erok415 did you get your desired result?

**Comment by RyanZim** [comment]
Closing for lack of response.
