### ISSUE TITLE
I thought node version 4+ is supported 

### ISSUE THREAD

**Issue by omidfi** [jprichardson/node-fs-extra#579]
Hello, thanks for the nice library :) 
I remember in the ES6 discussions, people mentioned node version 4.9+ for this library. But seems that it actually needs node 6+ because of the spread operators. 

Should that be mentioned in Readme? I'm just hoping it saves some time for someone who needs to support node 4.

**Comment by RyanZim** [comment]
fs-extra v6 dropped Node 4 support since it's EOL: https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md#600--2018-05-01

**Comment by omidfi** [comment]
Thanks. 

Would it help to mention the node version requirement in Readme? 

 Otherwise please feel free to close this.

**Comment by RyanZim** [comment]
I personally hate having to remember to update the README; people can look at the `.travis.yml` and figure it out.

**Comment by JPeer264** [comment]
@RyanZim what about having specified `engines` in the `package.json`? I think that would help more people who are not familiar with a `.travis.yml`.
https://docs.npmjs.com/files/package.json#engines

**Comment by jprichardson** [comment]
@JPeer264 great idea. Would you submit a PR?
