### ISSUE TITLE
Stack trace not included in fs.copy error

### ISSUE THREAD

**Issue by bitmage** [jprichardson/node-fs-extra#58]
To reproduce:

``` javascript
var fs = require('fs-extra');
fs.copy('/does/not/exist', '/something/else', function(err) {
    console.log('error:', err); // error is nested in array
    console.log('error stack:', err[0].stack); // message prints but no stack trace
});
```
1. Why the array nesting?  Is it necessary?
2. Stack trace should be present.  Mandatory for debugging.

**Comment by jgosmann** [comment]
For the record, I could have used a stack trace today in debugging an issue with Gatsby. The Gatsby CLI only prints the stack trace attached to the error (which is none in this case). I ended up hacking the Gatsby CLI to print a stack trace for the call site where the error is printed which led me back to the error callback. That ended up being sufficient in my case, but if I needed to know from where the `fs.copy` was called originally, I would have been out of luck.
