### ISSUE TITLE
Module not found: Error: Can't resolve 'fs-extra'

### ISSUE THREAD

**Issue by rawm10** [jprichardson/node-fs-extra#581]
- **Operating System:**
Windows 10 Pro

- **Node.js version:**
 "@types/node": "~8.9.4",

- **`fs-extra` version:**
6.0.1

-**angular:**
"@angular/core": "^6.0.0",

-**Typescript:**
     "typescript": "~2.7.2"
**issue:**
I have researched, researched, and researched some more, not understanding why when running ng serve I am receiving an error of :
 "ERROR in ./src/app/contact/contact.component.ts
            Module not found: Error: Can't resolve 'fs-extra' in {this would be my path my .ts file referencing the fs-extra}" but when i do ex: fs.readdir it can pick up the the method I am calling

**How I import:**
import * as fs from 'fs-extra';

**use:**
 fs.readdir('../assets/images', function(err, flist) {
      if (err) {
        console.log(err) ;
        throw err;
      }
      if (flist != null) {
        flist.forEach((x) => collection.push(x));
       }

Much appreciated if someone knows of a solution for this or have came across this, could help out.

Thanks!

**Comment by rawm10** [comment]
this is being ran in Node.

**Comment by RyanZim** [comment]
Sorry for going missing partway through the thread, is this still an issue?

**Comment by digoburigo** [comment]
Operating System:
Windows 7

Versions:
-  "@angular/core": "^6.0.3"
- "fs-extra": "^7.0.0"
- "typescript": "~2.7.2"

How I imported:
import * as fs from "fs-extra";

My use case:
I'm trying to read a kml file and when i try to compile the Errors are shown.
``` 
const buffer = fs.readFileSync("../assets/teste2.kml");
    const kmlDocument = new KmlDocument(buffer.toString());
    for (const placemark of kmlDocument["placemarks"]) {
      console.log(placemark);
    }
```

Errors:
```
WARNING in ./node_modules/xml2js/node_modules/sax/lib/sax.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\xml2js\node_modules\sax\lib'

ERROR in ./node_modules/graceful-fs/polyfills.js
Module not found: Error: Can't resolve 'constants' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\graceful-fs'
ERROR in ./node_modules/fs-extra/lib/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib'
ERROR in ./node_modules/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\empty'
ERROR in ./node_modules/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\graceful-fs'
ERROR in ./node_modules/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\graceful-fs'
ERROR in ./node_modules/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\jsonfile'
ERROR in ./node_modules/fs-extra/lib/util/utimes.js
Module not found: Error: Can't resolve 'os' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\util'
ERROR in ./node_modules/fs-extra/lib/copy/copy.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\copy'
ERROR in ./node_modules/fs-extra/lib/copy-sync/copy-sync.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\copy-sync'
ERROR in ./node_modules/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\empty'
ERROR in ./node_modules/fs-extra/lib/ensure/file.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/symlink.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/link.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/ensure/symlink-paths.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\ensure'
ERROR in ./node_modules/fs-extra/lib/json/output-json.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\json'
ERROR in ./node_modules/fs-extra/lib/json/output-json-sync.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\json'
ERROR in ./node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/mkdirs/mkdirs.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/mkdirs/win32.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\mkdirs'
ERROR in ./node_modules/fs-extra/lib/move/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\move'
ERROR in ./node_modules/fs-extra/lib/move-sync/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\move-sync'
ERROR in ./node_modules/fs-extra/lib/output/index.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\output'
ERROR in ./node_modules/fs-extra/lib/remove/rimraf.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\remove'
ERROR in ./node_modules/fs-extra/lib/util/utimes.js
Module not found: Error: Can't resolve 'path' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\fs-extra\lib\util'
ERROR in ./node_modules/graceful-fs/legacy-streams.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\graceful-fs'
ERROR in ./node_modules/xml2js/lib/parser.js
Module not found: Error: Can't resolve 'timers' in 'C:\Users\Usuario\Desktop\Projetos\teste-readers\node_modules\xml2js\lib'
```

**Comment by RyanZim** [comment]
@digoburigo Are you in Node? Looks like none of the core modules are resolving.

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by lim-enhui** [comment]
I have a similiar issue to this closed issue.

`ERROR in ./~/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\fs-extra\lib\empty'
 @ ./~/fs-extra/lib/empty/index.js 4:11-24
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\graceful-fs'
 @ ./~/graceful-fs/graceful-fs.js 1:9-22
 @ ./~/fs-extra/lib/fs/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\graceful-fs'
 @ ./~/graceful-fs/fs.js 3:9-22
 @ ./~/graceful-fs/graceful-fs.js
 @ ./~/fs-extra/lib/fs/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\jsonfile'
 @ ./~/jsonfile/index.js 5:8-21
 @ ./~/fs-extra/lib/json/jsonfile.js
 @ ./~/fs-extra/lib/json/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js`
