### ISSUE TITLE
Feature request ( isSameDir )

### ISSUE THREAD

**Issue by neutrino2211** [jprichardson/node-fs-extra#584]
I deal with alot of paths everyday and more than often I need to compare and see if a path is the same as another. 
```javascript
var fse = require ("fs-extra");
//Name is subject to change
console.log(fse.isSameDir("/usr","/usr")) //true
```
So I would like to present this feature and myself to the project because I can implement this and make a pull request

**Comment by RyanZim** [comment]
Precisely what would this method do? In your example, you could use `===`.

**Comment by neutrino2211** [comment]
Using `===` means using path.resolve twice and `isSameDir` syntactically makes more sense which also allows developers to know what it does especially when there is alot more code around it

**Comment by RyanZim** [comment]
I'm not :100: convinced this is a great idea, but in any case, it would be better suited for https://github.com/jprichardson/node-path-extra instead of `fs-extra`.
