### ISSUE TITLE
fs-extra@5.0.0 + node v10.1.0 = (node:25046) ExperimentalWarning: The fs.promises API is experimental

### ISSUE THREAD

**Issue by sulliwane** [jprichardson/node-fs-extra#586]
- **Operating System: linux**
- **Node.js version: v10.1.0**
- **`fs-extra` version: v5.0.0**

I'm getting this warning when using fs-extra@5.0.0 (and I need to be compatible with node v6, so i cannot jump to fs-extra@6.0.1).

But if I upgrade to fs-extra@6.0.1, the the warning is gone.

**Comment by RyanZim** [comment]
`fs-extra` v6.0.1 should support Node v6; if it doesn't, that's a bug. fs-extra v5 is no longer supported.

**Comment by sulliwane** [comment]
Ok, thanks. I will update then. I read this : https://github.com/jprichardson/node-fs-extra/blob/master/CHANGELOG.md

> Drop support for Node.js versions 4, 5, & 7

I misread, it doesn't specify support drop for v6 that's right. I'm a bit intrigued why node v7 was dropped though...

**Comment by RyanZim** [comment]
Node v7 isn't an LTS release, so it reaches EOL sooner. v7 is already EOL, so we don't support it, since it's not getting security updates anymore.
