### ISSUE TITLE
Weird stat behaviour when used in a Bluebird.map

### ISSUE THREAD

**Issue by eysi09** [jprichardson/node-fs-extra#591]
- **Operating System:** macOS High Sierra Version 10.13.4 (17E199)
- **Node.js version:** 8.9.0
- **`fs-extra` version:** 6.0.1

I've noticed a weird issue where `stat` may fail silently depending on how it's invoked when used with `Bluebird.map`. In particular, it fails when called without explicitly using a (redundant) arrow function. 

This will always fail:
```javascript
const bad = await Bluebird.map(["/some/path"], fp => fp).map(stat)
```
This works:
```javascript
const good = await Bluebird.map(["/some/path"], fp => fp).map(fp => stat(fp))
```

I haven't noticed this with other methods in `fs-extra`. 

E.g. this works:
```javascript
await Bluebird.map(["/some/path"], fp => fp).map(pathExists)
```
 and the following only fails in the last chain when `stat` is called:
```javascript
const test = await Bluebird.map(["/some/path"], fp => fp)
  .filter(pathExists)
  .map(fp => {console.log(fp); return fp}) // "/some/path"
  .map(stat)
```

**Comment by RyanZim** [comment]
What about `lstat`?

**Comment by RyanZim** [comment]
Promisification is done by https://github.com/RyanZim/universalify under the hood. It seems that somehow, `.fromCallback` isn't playing well with `Bluebird.map`. Can you test with a dummy callback function and universalify directly and see if your problem is there?

**Comment by eysi09** [comment]
Ok, I think I see it now.

Applying the promisified function like that inside the `map` causes it to be invoked with all the parameters supplied to the `map` callback, namely `currentValue`, `index` and `array`.

So in the following, the `cb` is actually the index `0` because that's the second parameter in the `map` callback:

```
  const callbackFn = (n, cb) => {
    console.log("Received args:", n, cb) // a, 0 
    setTimeout(() => cb(null, n), 15)
  }
  const fn = universalify.fromCallback(callbackFn)
  const test = ["a"].map(fn)
```
This returns:

```
Received args: a 0
/Users/eysi/code/garden-io/garden/build/src/cli/cli.js:242
            setTimeout(() => cb(null, n), 15);
                             ^

TypeError: cb is not a function
    at Timeout.setTimeout [as _onTimeout] (/.../cli.js:242:30)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

Should this be considered an issue with universalify? If so, I'd be happy to open a new issue there. And I'm closing this one.

**Comment by RyanZim** [comment]
I can't see how universalify could handle this, since there's no way for it to know how many arguments the underlying function accepts. It simply passes in a callback function as the last argument, if the last argument isn't a function.
