### ISSUE TITLE
Feature Request: the 'move' method should have the same options as copy

### ISSUE THREAD

**Issue by offg777** [jprichardson/node-fs-extra#594]
the 'move' method should have the same options as copy, mainly the filter option would be helpful.
___
![image](https://user-images.githubusercontent.com/31667350/41418062-95deec54-6fb4-11e8-9595-4fb195f04c06.png)
___
![image](https://user-images.githubusercontent.com/31667350/41417953-59eefa68-6fb4-11e8-83a0-257d461ab7b9.png)

**Comment by RyanZim** [comment]
How would this work? The filtered files would stay in their original place?

**Comment by offg777** [comment]
Yes, and maybe you could add a 'delete if filter returns false' option.

**Comment by RyanZim** [comment]
This seems really complicated, I'm thinking you'd be better served by using `klaw` to walk the directory and move the files you need to.

**Comment by RyanZim** [comment]
Voting to close as too much of an edge case to support; @jprichardson @manidlou @JPeer264?

**Comment by jprichardson** [comment]
I think the intent is good - however, I agree on the complexity. @offg777 if you're willing to submit PRs to get this rolling we can reopen and visit. Please don't submit a PR to solve these problems before discussing on how it'd be done - we'd hate for you to spend your time writing code to only have it wasted. So submit your proposal here - one option at a time.
