### ISSUE TITLE
Why no promisified `lchmod`?

### ISSUE THREAD

**Issue by ramhejazi** [jprichardson/node-fs-extra#595]
Why the module does not promisify the [`fs.lchmod`](https://nodejs.org/api/fs.html#fs_fs_lchmod_path_mode_callback) function? The `api` array in [lib/fs/index.js](https://github.com/jprichardson/node-fs-extra/blob/master/lib/fs/index.js) doesn't have an element for `lchmod` function.

**Comment by ramhejazi** [comment]
Thanks for the fast reply. I submitted a PR.

**Comment by ramhejazi** [comment]
That week was very long Ryan. I have temporarily added the function to `fs-extra` in a package that I was developing: https://github.com/ramhejazi/draxt/blob/master/src/interfaces/Node.js#L18

**Comment by RyanZim** [comment]
So sorry, this slipped through the cracks on me, I will try to patch as soon as I can.

**Comment by ramhejazi** [comment]
No worries and no need to say sorry man.  It just needed one line for temporarily fixing it.

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/596; will be released in v7
