### ISSUE TITLE
Does not promisfy createReadStream/createWriteStream

### ISSUE THREAD

**Issue by solutionstack** [jprichardson/node-fs-extra#598]
Example:
`import  fs  from 'fs-extra';
import * as http from 'http';

http.createServer(function (req, res) {

    res.writeHead(200, {'Content-Type': 'application/json'});

    fs.createReadStream('./sample.json.js')
     .then((data) => {

        console.log(data);
     }).catch((err) => {

        console.log(err);
    })
}).listen(3000);`

would output
`fs.createReadStream(...).then is not a function`

**Comment by RyanZim** [comment]
Streams don't use callbacks by default, so they're not reasonably promisifyable. This is intentional.

**Comment by switz** [comment]
Totally reasonable, but would be kinda magical to abstract a promise interface for streams. Useful in simple contexts. But I completely understand why you wouldn't want to. Just tossing in my 2 cents.

**Comment by rayfoss** [comment]
https://humanwhocodes.com/snippets/2019/05/nodejs-read-stream-promise/
```
function readStream(stream, encoding = "utf8") {
    
    stream.setEncoding(encoding);

    return new Promise((resolve, reject) => {
        let data = "";
        
        stream.on("data", chunk => data += chunk);
        stream.on("end", () => resolve(data));
        stream.on("error", error => reject(error));
    });
}
const text = await readStream(process.stdin);
```

Streams are giving me headaches... They aren't done when I need them to be causing subtle annoying bugs
