### ISSUE TITLE
chmod & chown for mkdirs

### ISSUE THREAD

**Issue by cadorn** [jprichardson/node-fs-extra#60]
So I create a bunch of directories with `mkdirs` and now I need to change permissions and ownership for the created directories.

There should be an optional options argument to mkdirs:
````
{
  chmod: 400,
  chown: {
    user: "user",
    group: "group"
  }
}
````

Thoughts on above or how I would solve this otherwise?

**Comment by jprichardson** [comment]
Closing. In the long-run, something like this would be great. But before we get there, we'll need a recursive `chmod`/`chown`. Before we get those methods, we'll need a `walk()`. So this would be a long way off :(

**Comment by M-erb** [comment]
@jprichardson Thank you for such an awesome library! Just a few questions on this. Do the above statements still stand with how the library works today? Also can ```mode``` be passed to other functions such as "outputFile".

For example would this work?
```await fse.outputFile('path/to/file.txt', 'a string', {mode: 0400})```
