### ISSUE TITLE
Get information of copySync operation, files which were skipped or overwritten

### ISSUE THREAD

**Issue by mpsingh2003** [jprichardson/node-fs-extra#602]
- **Operating System: Windows 10**
- **Node.js version: 8.11.2**
- **`fs-extra` version: 6.0.1**

I am creating a new directory by merging 2 directories, say creating directory Z from X and Y. Following are the steps I am following:
1. Copy directory X to Z (No issues)
2. Copy directory Y to Z. In this step, there is a chance some files may have same name. I don't want to overwrite those files but want to have information which files are resulting in name conflict so that I can copy those particular files with a different name, say by appending '_copy'.

I tried using `errorOnExist` option also, but it then halts the execution when name conflict occurs. Also `copySync` method returns undefined and not any useful information.

**Comment by RyanZim** [comment]
This is a complex specialty use-case; I'd suggest using https://github.com/manidlou/node-klaw-sync to walk the directory structure, test for existing files, and run copy/rename operations as needed.
