### ISSUE TITLE
Error copying files with special characters (accent).

### ISSUE THREAD

**Issue by marlluslustosa** [jprichardson/node-fs-extra#605]
Fedora 27 KDE (using Sirikali client Cryfs)

Hello, when trying to copy a folder or file with accented name or special character I get a message that this file does not exist and does not copy into the folder.

I made a print about it.
![screenshot_20180720_120731](https://user-images.githubusercontent.com/29416568/43011678-92900f1a-8c1a-11e8-873c-b237d6e28784.png)

**Comment by julmot** [comment]
Having the same issue with `@` (part of a node_modules folder name)

**Comment by RyanZim** [comment]
Pretty sure this is a dupe of #575; closing.
