### ISSUE TITLE
rimraf: options should be object

### ISSUE THREAD

**Issue by CreatorVilius** [jprichardson/node-fs-extra#615]
- **Operating System:** Windows 10
- **Node.js version:** 10.8.0
- **`fs-extra` version:** 7.0.0

Error:

```js
(node:11676) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: rimraf: options should be object
    at Object.rimrafSync [as removeSync] (Dir\node_modules\fs-extra\lib\remove\rimraf.js:234:10)
```

When deleting folder with files.

Code:

```js

fse.removeSync(`./temp-modules`, (err) => {
          if(err) console.error(err)
        })
```

**Comment by RyanZim** [comment]
You're using the sync version, which does not accept a callback. Either use the regular `fse.remove`, or omit the callback for `fse.removeSync`.

**Comment by CreatorVilius** [comment]
Yeah, i removed callback and it fixed my issue.

When edited post noticed your message.
