### ISSUE TITLE
copyFileSync leaves source file open if the openSync on the destination fails

### ISSUE THREAD

**Issue by marshalljmiller** [jprichardson/node-fs-extra#616]
- **Operating System:** RHEL 7
- **Node.js version:** 1.7.9
- **`fs-extra` version:** 4.0.0

I ran into a situation where an app failed to create a destination file because it did not have write permissions on the destination directory.  The problem is that the source file was already opened and it was not closed when the error occurred.  The source file is on a DVD and, due to the open file, it can't be unmounted until the app exits.

**Comment by RyanZim** [comment]
You're using an old version of `fs-extra`; I think this is fixed in the latest version.
