### ISSUE TITLE
npm install fs-extra doesn't work

### ISSUE THREAD

**Issue by rantiev** [jprichardson/node-fs-extra#62]
Hi, I have tried to reinstall all modules. And now i can't install properly fs-extra. Sometimes console says it can't find compatible ncp, module, i try to install ncp, then it start to say that it can't find compatible mkdirp module, then i install mkdirp, and it says about ncp again. 

D:\work\WebServers\home\localhost\www\ThemeFramework\ThemeFramework>npm install
fs-extra
npm http GET https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/ncp
npm http GET https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/rimraf
npm ERR! Error: No compatible version found: mkdirp@'^0.5.0'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.0.6","0.0.7","0.1.0","0.2.0
","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1
","0.4.2","0.5.0"]
npm ERR!     at installTargetsError (C:\Program Files\nodejs\node_modules\npm\li
b\cache.js:709:10)
npm ERR!     at C:\Program Files\nodejs\node_modules\npm\lib\cache.js:631:10
npm ERR!     at RegClient.get_ (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\npm-registry-client\lib\get.js:101:14)
npm ERR!     at RegClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\
node_modules\npm-registry-client\lib\get.js:37:12)
npm ERR!     at fs.js:266:14
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "fs-extra"
npm ERR! cwd D:\work\WebServers\home\localhost\www\ThemeFramework\ThemeFramework

npm ERR! node -v v0.10.7
npm ERR! npm -v 1.2.21
npm http 304 https://registry.npmjs.org/ncp
npm http 304 https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/rimraf
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\work\WebServers\home\localhost\www\ThemeFramework\ThemeFramework
\npm-debug.log
npm ERR! not ok code 0

**Comment by jayshri-developer** [comment]
> Oh, yeah... that's gotta be the issue. A recent npm (packaged with Node.js) update started using `^`. It could be that older versions don't support `^`?

what exactly write for update npm
