### ISSUE TITLE
Wrong jsonfile imported when bundling with webpack

### ISSUE THREAD

**Issue by erikjalevik** [jprichardson/node-fs-extra#620]
- **Operating System:** Windows 10
- **Node.js version:** 8.9.3 (in Electron)
- **`fs-extra` version:** 7.0.0

I just added fs-extra to my Electron project and am using the move and moveSync functions. When run from the jest tests, everything works fine. When building the real app, it gets bundled with webpack, and it then fails at the following point at startup:

1. My code requires fs-extra/index.js.
2. fs-extra/index.js requires fs-extra/lib/json/index.js
3. json/index.js requires fs-extra/lib/json/jsonfile.js
4. jsonfile.js requires external module jsonfile and then tries to retrieve its readFile function
5. Here readFile is undefined, and the code crashes in universalify.fromCallback.

It seems like webpack generates a require statement to fs-extra/lib/json/jsonfile.js instead of to the module called jsonfile, based on this output:

```
const u = __webpack_require__(/*! universalify */ "./node_modules/universalify/index.js").fromCallback
const jsonFile = __webpack_require__(/*! jsonfile */ "./node_modules/fs-extra/lib/json/jsonfile.js")

module.exports = {
  // jsonfile exports
  readJson: u(jsonFile.readFile),
  readJsonSync: jsonFile.readFileSync,
  writeJson: u(jsonFile.writeFile),
  writeJsonSync: jsonFile.writeFileSync
}
```

Is this a bug or a config issue on my side?

**Comment by RyanZim** [comment]
Looks like a bug in webpack or your config.

**Comment by b-zurg** [comment]
@erikjalevik did you ever figure this out?

**Comment by erikjalevik** [comment]
Hi @b-zurg, too long ago for me even to remember having written this question, but I had a look through my commit history and found a change to the webpack config that seemingly fixed it:

```
   resolve: {
-    modules: [".", "./modules", "../node_modules"]
+    modules: [
+      path.resolve(__dirname, 'dist'),
+      path.resolve(__dirname, 'dist/modules'),
+      'node_modules'
+    ]
   },
```

Hope that's of any help.
