### ISSUE TITLE
[Feature request] add a cancel event for copy and move operations

### ISSUE THREAD

**Issue by AlexSHoffman** [jprichardson/node-fs-extra#621]
Would that be possible to add a "cancel operation" event?

It would be nice to have a way to cancel a copy or move operation during the transfer.

**Comment by manidlou** [comment]
hmm..! not sure about this! Generally, I am not a fan of this! It can be complicated and messy. But @AlexSHoffman what do you mean exactly?! Will you elaborate on the idea please?

**Comment by AlexSHoffman** [comment]
@manidlou I'm not sure what's the best way to do it but I think the simplest one for async operations is to cancel the promise. Refs: 
- https://blog.bloomca.me/2017/12/04/how-to-cancel-your-promise.html
- https://stackoverflow.com/a/37642079/6171895

Maybe even add an emitter to that so users could specify the functions to run after it's cancelled, e.g.

```JS
copy.on('cancel', () => {
   // do something, e.g. show a notification toast
})

```

For synchronous operations, I think you can continuously interrupt function execution and check if the operation has been cancelled. But you would also need to track and store the progress to continue the execution after checking the `cancelled` variable, here's a silly example:
https://codepen.io/anon/pen/bxwLro?editors=1011

I'm not sure if it even makes sense to add this functionality for sync copy/move operations, since usually when you're copying / moving a lot of files you are using async copy/move operations anyway.

**Comment by AlexSHoffman** [comment]
@manidlou I agree, after additional research I realized it's gonna be pretty hard to do. I'm going to close the issue then
