### ISSUE TITLE
Make it more modular

### ISSUE THREAD

**Issue by jimmywarting** [jprichardson/node-fs-extra#627]
I was wondering if you could make this more modular so that you don't need to install  the hole package. Kinda like lodash dose. cuz right now i'm only after one thing... `fs.remove`

so would be nice if i could install it via
```
npm install @fs-extra/remove 
# or the way lodash dose it:
npm install fs-extra.remove 
```

I'm not keen to install 194kB just for that, might as well inline my function

**Comment by jimmywarting** [comment]
> What benefit does breaking this up bring?

Disc space, install speed, javascript compilation time, startup time, Build time

**Comment by JPeer264** [comment]
I am a big fan of having a modular structure in the browser, especially when it comes to loading times, but server side it does not make much sense for me.

Furthermore if we have a modular structure we should also make the native fs functions modular, which might be a lot of extra work.

I think nowadays it does not matter if there are 200kb more or less on a disc, or to save (I assume) 20ms of compilation time. I don't know if this brings a lot of benefit to the majority of the users.

**Comment by jprichardson** [comment]
Long-term, I'd be okay with a monorepo, but consumers of `fs-extra` would still get only one package. As part of the monorepo, we'd also publish `fs-extra.remove` et al. It then carries a branding benefit. 

I think we're still a long ways off from this though. I'd rather focus on making `fs-extra` really useful and bug free before we go down this path.
