### ISSUE TITLE
Walk

### ISSUE THREAD

**Issue by newmanw** [jprichardson/node-fs-extra#63]
You mention including a walk feature in the docs.

+1

Not sure its get more simple than something like this:
https://github.com/coolaj86/node-walk

In the end though I understand about 'too much'...

**Comment by jabjab** [comment]
@mikermcneil Just a note, but something similar to the output of [Python's walk function](https://docs.python.org/3/library/os.html#os.walk) might be useful. The output for each directory in the tree operated on is a `(dirpath, subdirnames, filenames)` tuple, and it avoids having to repeat the path for every file and every subdirectory in the current dir (though you'll still end up with the subdir paths if you continue the walk into the subdirectories).

**Comment by cookch10** [comment]
What about writing an event emitter around `enumerateFileSystemInfos` from [fs-filesysteminfo](https://github.com/cookch10/node-fs-filesysteminfo)?  May or may not be a good fit, but a suggestion nonetheless.

**Comment by jprichardson** [comment]
I really like the streaming interface provided by https://github.com/thlorenz/readdirp. So far, that's the direction that I'm leaning towards.

**Comment by jprichardson** [comment]
This has been started: https://github.com/jprichardson/node-fs-extra/tree/master/lib/walk It's intentionally left undocumented as the interface will almost certainly change.

**Comment by jprichardson** [comment]
Walker streams implementation complete: https://github.com/jprichardson/node-fs-extra/commit/f215fc3c568dfa8e58f4f49b6c77a499309ac7fc 

Pretty basic, but it gets the job done. Now to add tests / documentation.

**Comment by jprichardson** [comment]
Finally documented the implementation and published in `0.25.0`. https://github.com/jprichardson/node-fs-extra/tree/0.25.0
