### ISSUE TITLE
paused before potential out-of-memory crash

### ISSUE THREAD

**Issue by hitao123** [jprichardson/node-fs-extra#630]
- **Operating System:**
Mac OS X 10.14
- **Node.js version:**
v8.10.0
- **`fs-extra` version:**
fs-extra 4.0.3

when use ndb (Chrome dev tools) occurs "paused before potential out-of-memory crash"

```
function readFileSync (file, options) {
  options = options || {}
  if (typeof options === 'string') {
    options = {encoding: options}
  }

  var fs = options.fs || _fs

  var shouldThrow = true
  if ('throws' in options) {
    shouldThrow = options.throws
  }

  try {
    var content = fs.readFileSync(file, options)
    content = stripBom(content)
    return JSON.parse(content, options.reviver)
  } catch (err) {
    if (shouldThrow) {
      err.message = file + ': ' + err.message
      throw err
    } else {
      return null
    }
  }
}
```

![jietu](https://user-images.githubusercontent.com/16607714/46784389-7e0aed80-cd60-11e8-9f70-dbcba57c1e49.jpeg)

**Comment by RyanZim** [comment]
How big file are you reading? Also, your `fs-extra` version is out of date, please consider upgrading.

**Comment by hitao123** [comment]
about 15M @RyanZim

**Comment by RyanZim** [comment]
I'm wondering if that file + whatever else you have in memory is pushing your memory requirements. Try running your script with `node --max-old-space-size=8192 <script.js>`.

**Comment by RyanZim** [comment]
Assuming this is resolved.
