### ISSUE TITLE
Strip BOM 

### ISSUE THREAD

**Issue by aubergene** [jprichardson/node-fs-extra#640]
I use this to open CSV files written by Excel and they have a byte order mark (BOM - 0xFEFF). It's easy to strip off, but perhaps would be handy if that functionality was included in fs-extra.

**Comment by RyanZim** [comment]
I question whether this is in-scope for fs-extra. With the exception of the JSON methods, none of the fs-extra methods care about the contents of the files at all. There is a library dedicated to what you're describing: https://www.npmjs.com/package/read-file

**Comment by aubergene** [comment]
Yeah, you're right it's not the place for it, was just frustrated and tracing up the stack as to where this could go. Thanks

**Comment by pnkapadia64** [comment]
I have documents with turkish translations and some of them get prepended with an unknown character.
[Screenshot](https://imgur.com/0jfpzmk)
Is this something that fs-extra can help with or I'll have to use `read-file` package?

**Comment by RyanZim** [comment]
@pnkapadia64 Out of scope for fs-extra.
