### ISSUE TITLE
ensureDirSync() with chown

### ISSUE THREAD

**Issue by digitalnature** [jprichardson/node-fs-extra#641]
- **Operating System:** Ubuntu 18
- **Node.js version:**  8.10
- **`fs-extra` version:** 7.0

Can an option be added to `ensureDir/ensureDirSync` so that it also sets the owner of the directories it creates (not to existing dirs)?

if I `chown()`  the path, it only sets the owner of the last directory in the hierarchy.

**Comment by RyanZim** [comment]
Dealing with file ownership is not something that's commonly encountered in Node; I'm going to call this out of scope for fs-extra.
