### ISSUE TITLE
Flow cannot recognize default export

### ISSUE THREAD

**Issue by daryn-k** [jprichardson/node-fs-extra#649]
Before using Flow (a static type checker for javascript) everything was okay, but now Flow cannot recognize export default.

```
Cannot import a default export because there is no default export in `fs-extra`.

   4| import fs from 'fs-extra'
             ^^
```

**Comment by RyanZim** [comment]
Flow probably expects you to use `import * as fs from 'fs-extra'`; that's my guess.
