### ISSUE TITLE
exclude filter in fs.copy

### ISSUE THREAD

**Issue by jjude** [jprichardson/node-fs-extra#65]
Is it possible to exclude certain files in fs.copy? Say I want to exclude .css files?
Thanks

**Comment by martinheidegger** [comment]
@jprichardson Arn't the RegExp's _include_ filters? Difference being that the result needs to be `true` to be included and not `true` to be excluded?

**Comment by khurramraheel** [comment]
Should we use /.mp3/ regex in case of only copying the mp3s?

**Comment by grantholle** [comment]
Passing a function as the third argument (RegEx is deprecated) where the return value indicates whether to copy the file/directory or not.

True copies, false does not.
