### ISSUE TITLE
b/c of umask, the default mode for ensureDir is 0777 & (~process.umask())

### ISSUE THREAD

**Issue by qiulang** [jprichardson/node-fs-extra#651]
Because of umask, calling `ensureDir/ensureDirSync` without `fs.chmodSync`, the actual mode is not the same as the intended mode. I think it is better to mention this in https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir.md  especially for someone who is not familiar with umask. 

Besides, I feel it is unnecessary to call this in mkdirs.js because node will take care of that. 

```
  if (mode === undefined) {
    mode = o777 & (~process.umask())
  }
```

Refer to 

1. https://github.com/nodejs/node/issues/15092
2. https://stackoverflow.com/questions/30815154/fs-mkdir-is-creating-the-directory-with-different-permissions-than-those-speci

**Comment by RyanZim** [comment]
PR welcome to clarify the docs. Thanks for the tip about explicitly doing it in the code, need to look into that.

**Comment by zensabbah** [comment]
A simple explanation of mode = 0o2775? Should it be chmod 775?

**Comment by RyanZim** [comment]
Explicit code usage fixed in https://github.com/jprichardson/node-fs-extra/pull/791. Still needs documented; will try to get that done.

**Comment by RyanZim** [comment]
Actually, was under the impression Node has a note about this; since they don't, not a priority to do it here.
