### ISSUE TITLE
outputJson function adds unwarented single quote to file name

### ISSUE THREAD

**Issue by paragi** [jprichardson/node-fs-extra#654]
Offensive code:

    const fs = require('fs-extra');
    (async () => {
          await fs.outputJson("some file name", "some data");
    })();

On unix (debian) this creates a file named 'some file name' including the single quotes.
Other legal file name chars (control chars) has the same effect. 

This is a serious bug, that renders the function useless on a production environment.

- **Operating System:**
- **Node.js version:**
- **`fs-extra` version:**

**Comment by RyanZim** [comment]
You're sure you're not using two single quotes that look like a double quote in your code?

**Comment by paragi** [comment]
Yup! I using the exact code as above, and the result is with single quotes :)

**Comment by RyanZim** [comment]
How are you confirming the created file names? I wonder if whatever you’re using is adding the quotes to make it clear there’s not multiple files.
