### ISSUE TITLE
copy files from one directory and add to existing files on another directory with out deleting existing

### ISSUE THREAD

**Issue by reachdevelopers** [jprichardson/node-fs-extra#655]
I am trying to move some image from one directory and if destination directory has files just add the new images don't delete existing ones. Can anyone tell me if this can be done with fs-extra?

**Comment by RyanZim** [comment]
Yes, use `overwrite: false`. https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md

**Comment by reachdevelopers** [comment]
nice, will try that and thank you so much.

**Comment by kieronlanning** [comment]
Is there a version of `overwrite` that will not delete the content of a destination folder, but will overwrite any matching files?

... so it's additive.

**Comment by RyanZim** [comment]
@kieronlanning No.

**Comment by kieronlanning** [comment]
@RyanZim cheers for the speedy response.

Do you know of another way of additively copying/ moving the contents of a folder while maintaining any existing data, and overwriting matching files?

**Comment by RyanZim** [comment]
I don't offhand, other than shelling out to `rsync` on *nix. Might need to write your own implementation if you want to do it in native JS.

**Comment by vassudanagunta** [comment]
@kieronlanning [fs-jetpack's copy](https://github.com/szwacz/fs-jetpack#copyfrom-to-options) supports this.
