### ISSUE TITLE
Feature request: directory total size

### ISSUE THREAD

**Issue by sompylasar** [jprichardson/node-fs-extra#656]
Something like this would be nice to have out of the box.

https://stackoverflow.com/questions/7529228/how-to-get-totalsize-of-files-in-directory

------

- **Operating System:** macOS 
- **Node.js version:** v10.12.0
- **`fs-extra` version:** 7.0.1

**Comment by RyanZim** [comment]
The problem here is that there's two ways to get the size of a directory. Size, and size on disk.

**Comment by sompylasar** [comment]
That's fine, there can be two respective functions, or an option to one.

**Comment by MichaelFedora** [comment]
Here's a gist of something I made that seems to work quite well:

https://gist.github.com/MichaelFedora/9a3783c670127f6b61f7973f1604c788

preview for the lazy:
```javascript
function sizeSync(p) {
  const stat = fs.statSync(p);
  if(stat.isFile())
    return stat.size;
  else if(stat.isDirectory())
    return fs.readdirSync(p).reduce((a, e) => a + sizeSync(path.join(p, e)), 0);
  else return 0; // can't take size of a stream/symlink/socket/etc
}
```

I haven't found something that gets the difference between "size" and "size on disk" within native node whatnot, so I feel like this is the best solution.

**Comment by RyanZim** [comment]
Going to close as out of scope, since this is quite complicated. In addition to size differences mentioned above, you throw symlinks (or hardlinks) into the mix, and it gets really hairy. Should be its own module given the complexity. If there's a working module that fs-extra can depend on, I'd consider it.
