### ISSUE TITLE
Add transform option to .copy()

### ISSUE THREAD

**Issue by bushtarikgg** [jprichardson/node-fs-extra#658]
Is this within scope? I would love to be able to pass through2 to .copy() so I can transform files on the way. I can probably make a PR.

**Comment by RyanZim** [comment]
No, way out of scope. `copy` is for copying files, if you want to transform files, that's a job for another library.

**Comment by bushtarikgg** [comment]
Alright, thanks. It would be very convenient/efficient/easy to transform certain files while recursively going through the folders but I understand. ncp has the functionality so I figured I'd ask since it's referred to in the readme. https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js#L120 ncp also doesn't appear to be maintained so I want to avoid it. I think I should be able to write in a quick transform by using copy's filter function. I'll just return false and do my operation since it is compatible with promises. I understand not wanting to do things out of scope.

Thanks for everything.

**Comment by bushtarikgg** [comment]
```ts
import * as path from 'path';
import * as through2 from 'through2';
import * as Mustache from 'mustache';
import * as fs from 'fs-extra';

import { IEnvVars } from './interfaces';

function mustacheTransform(envs: IEnvVars) {
  return through2(
    {
      allowHalfOpen: false,
      objectMode: true,
    },
    (chunk, enc, cb) => {
      const rendered = Mustache.render(chunk.toString(enc), envs);
      cb(null, rendered);
    },
  );
}

function filterWithVars(vars: IEnvVars) {
  return async function filter(src: string, dest: string): Promise<boolean> {
    if (path.basename(src).includes('.bp')) {
      const newDest = dest.replace('.bp', '');

      await new Promise((resolve, reject) => {
        const readStream = fs.createReadStream(src);
        const writeStream = fs.createWriteStream(newDest);

        readStream.on('error', reject);
        writeStream.on('error', reject);

        writeStream.once('finish', () => {
          resolve();
        });

        writeStream.on('open', () => {
          readStream.pipe(mustacheTransform(vars)).pipe(writeStream);
        });
      });

      return false;
    }
    return true;
  };
}

async function recursiveCopy(
  src: string,
  dest: string,
  vars: IEnvVars,
): Promise<any> {
  const copyOptions: fs.CopyOptions = {
    filter: filterWithVars(vars),
  };
  await fs.copy(src, dest, copyOptions);
}

export default recursiveCopy;

```
I figure I'll show what I ended up doing just in case someone is after the same sort of thing and finds this on google.
