### ISSUE TITLE
Cant resolve 'fs'

### ISSUE THREAD

**Issue by lim-enhui** [jprichardson/node-fs-extra#663]
- **Operating System:**
- **Node.js version:**
- **`fs-extra` version:**
Windows 10 Enterprise
node@6.10.1
fs-extra@3.0.1

ERROR in ./~/fs-extra/lib/empty/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\fs-extra\lib\empty'
 @ ./~/fs-extra/lib/empty/index.js 4:11-24
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/graceful-fs/graceful-fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\graceful-fs'
 @ ./~/graceful-fs/graceful-fs.js 1:9-22
 @ ./~/fs-extra/lib/fs/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/graceful-fs/fs.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\graceful-fs'
 @ ./~/graceful-fs/fs.js 3:9-22
 @ ./~/graceful-fs/graceful-fs.js
 @ ./~/fs-extra/lib/fs/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

ERROR in ./~/jsonfile/index.js
Module not found: Error: Can't resolve 'fs' in 'C:\Users\el10004\developer-test\m63\node_modules\jsonfile'
 @ ./~/jsonfile/index.js 5:8-21
 @ ./~/fs-extra/lib/json/jsonfile.js
 @ ./~/fs-extra/lib/json/index.js
 @ ./~/fs-extra/lib/index.js
 @ ./src/theme.watcher.js
 @ multi (webpack)-dev-server/client?http://localhost:3002 webpack/hot/dev-server ./src/theme.watcher.js

**Comment by RyanZim** [comment]
`fs-extra` is not for use in the browser.
