### ISSUE TITLE
fs.stat() with options doesn't work on graceful-fs

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#664]
I was working on fixing the inode bug and noticed that apparently `graceful-fs` hasn't been updated yet to support `fs.stat()` with additional options object. I tried with the latest version `v4.1.15` also and still no success! I opened an issue there: https://github.com/isaacs/node-graceful-fs/issues/158.

**Comment by brodybits** [comment]
Is this related to #657?

**Comment by manidlou** [comment]
yes @brodybits
