### ISSUE TITLE
Garbled appeared when using the copySync method of fs-extra

### ISSUE THREAD

**Issue by wjz1209391890** [jprichardson/node-fs-extra#665]
Operating System: Windows 10
Node.js version: 10.14.0
fs-extra version:7.0.0

In a recent project, I used the copySync method of fs-extra to copy the contents of one directory to another directory. Some javaScript, css, and html files in the folder were garbled, file‘size equals with the file before copying.  But when I open with Windows’notepad is empty, it seems to be some space placeholders, open content with EditPlus is a continuous box. I don't know what caused it,please help me analyze it, thank you.

[files before and after Coping.zip](https://github.com/jprichardson/node-fs-extra/files/3011769/files.before.and.after.Coping.zip)

**Comment by RyanZim** [comment]
Please try with `fs-extra` v8. If this persists please, post your example as a GitHub Gist or repository. I cannot take the security risk of opening random .zip files off the internet.
