### ISSUE TITLE
set -x

### ISSUE THREAD

**Issue by ccorcos** [jprichardson/node-fs-extra#669]
It would be cool if there was some sort of `set -x` options for debug logging all fs operations.

**Comment by RyanZim** [comment]
There are two libraries for monitoring `fs-extra` calls, but neither have been updated recently:

- https://github.com/jdxcode/fs-extra-debug
- https://github.com/cadorn/mfs

Is this what you're looking for?

**Comment by RyanZim** [comment]
Closing for lack of response.
