### ISSUE TITLE
Could I use emptyDirSync but keep some child directory not being removed?

### ISSUE THREAD

**Issue by wufeng87** [jprichardson/node-fs-extra#672]
- Operating System: win10
- Node.js version:10.15.0
-"fs-extra": "3.0.1",

Say I want to keep .git child directory when I use emptyDirSync to empty the parent directory of .git. Thanks.

**Comment by RyanZim** [comment]
Just use `readdir` to get the items, iterate over them and call `remove` on the ones you want to remove.
