### ISSUE TITLE
Why readdir and not readDir?

### ISSUE THREAD

**Issue by rohan-deshpande** [jprichardson/node-fs-extra#673]
The README calls out `readdir` for annoying node naming conventions, but the API still exposes this name and not `readDir`

**Comment by RyanZim** [comment]
`fs-extra` is a drop-in replacement for `fs`, so we need to expose `readdir`, since that's what Node calls it, even though it's irritating.

**Comment by rohan-deshpande** [comment]
Just saying you **could** expose both

**Comment by RyanZim** [comment]
Yeah, not a fan of aliases.
