### ISSUE TITLE
about unicode escape code

### ISSUE THREAD

**Issue by yyman001** [jprichardson/node-fs-extra#677]
- **Operating System:** WIN10 x64
- **Node.js version:** v8.10.0
- **`fs-extra` version:** "fs-extra": "^5.0.0"

i need unicode `Chinese`  and wirte `json` file.

eg:
// test data => "name": "图层-1"
// this unicode is  right
layer.name: \u56fe\u5c42\u002d\u0031
![image](https://user-images.githubusercontent.com/5688485/57517482-87395880-7349-11e9-8fc2-cb5366edf46b.png)

// but write json it will... this is bug ?
\\u56fe\\u5c42\\u002d\\u0031
![image](https://user-images.githubusercontent.com/5688485/57517450-71c42e80-7349-11e9-8e6a-d5fbea1ea65a.png)

use to unicode function
```js
function encodeUnicode(str) {
  var res = [];
  for (var i = 0; i < str.length; i++) {
    res[i] = ("00" + str.charCodeAt(i).toString(16)).slice(-4)
  }
  return "\\u" + res.join("\\u")
}
```
can you help ?

**Comment by RyanZim** [comment]
First off, you're using a very outdated version of `fs-extra`.

Secondly, I'm not sure I fully understand your problem. Can you post a reduced test case?

**Comment by RyanZim** [comment]
Closing for lack of reply.
