### ISSUE TITLE
fd must be a file descriptor 

### ISSUE THREAD

**Issue by valoricDe** [jprichardson/node-fs-extra#697]
- **Operating System:** MacOSx 10.13.4
- **Node.js version:** 8.12.0
- **`fs-extra` version:** 8.0.1
- **`graceful-fs` version:** 4.1.15

When I'm executing:
```
await ensureDir(storageDir)
or
await read(storageFile)
```
I'm getting the folling error:

TypeError: fd must be a file descriptor
    at Object.fs.read (fs.js:664:11)
    at Object.read (node_modules/graceful-fs/polyfills.js:131:20)
    at Promise (node_modules/fs-extra/lib/fs/index.js:81:8)
    at new Promise (<anonymous>)
    at Object.exports.read node_modules/fs-extra/lib/fs/index.js:80:10)

Edit: I created a codepen showing a similar error: https://codesandbox.io/s/gallant-moon-4nlex

**Comment by RyanZim** [comment]
How are you getting this error?

**Comment by valoricDe** [comment]
:exploding_head: yes I should add that

**Comment by RyanZim** [comment]
When you're running `await read(storageFile)`, is `storageFile` a file descriptor or a string file name?

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by valoricDe** [comment]
Hi, storageFile and storageDir are both valid paths as string. Like in the codepen mentionend in the first comment: https://codesandbox.io/s/gallant-moon-4nlex

**Comment by RyanZim** [comment]
Yeah, `fs.read` requires a numrical file descriptor (`fd`) https://nodejs.org/api/fs.html#fs_fs_read_fd_buffer_offset_length_position_callback

**Comment by RyanZim** [comment]
Looking at your codepen, I believe you want `fs.readFile()` instead
