### ISSUE TITLE
outputJson does not preserve the object for asynchronous processing

### ISSUE THREAD

**Issue by paragi** [jprichardson/node-fs-extra#702]
- **Operating System: Linux 4.15.0-52 Debian**
- **Node.js version: 12.2.0**
- **`fs-extra` version:8.1.0**

When writing object asynchronously with outputJson, the object is not preserved, before the promise is returned.

Example:
```js
const fs = require('fs-extra');

( async () => {
  let i;
  let obj = {}
  let promises = [];

  for( i = 0; i<4; i++ ){
    obj.id = i;
    promises.push( fs.outputJson('./' + i, obj) );
  }

  await Promise.all(promises);

  for( i = 0; i<4; i++ )
    console.log( await fs.readJson('./' + i));

})();
```

**Comment by RyanZim** [comment]
Yes, this is normal. If you're mutating an object, behavior will not be predictable.

**Comment by paragi** [comment]
I most asynchronous use cases i can imagine, you would want to use the stringification, to preserve the object, instead of copying it first (closure), then stringify it and the dump it.

In my opinion, it seems contra intuitive, and sort of defeats the purpose, of having a function to replace fs.outputFile(fileName, JSON.stringify(object) )

I wish you would reconsider.

**Comment by RyanZim** [comment]
How does `writeJson` work here?

**Comment by paragi** [comment]
```writeJson``` seems to be asynchronous mutation safe
