### ISSUE TITLE
options for readdir

### ISSUE THREAD

**Issue by mt4c** [jprichardson/node-fs-extra#704]
- OS Centos7
- Node 10.16
- fs-extra 8.0.1
fs.readdir in node.js provides options like "encoding" and "withFileTypes". In fs-extra fs.readdir I don't see any of these options available.

**Comment by RyanZim** [comment]
`withFileTypes` is working fine for me with `fs-extra` 8.1.0.

**Comment by skatpgusskat** [comment]
even I pass `withFileTypes ` option to readdir method, they just return string.

[By documentation in Node.js](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback), It should return fs.Dirent which support several method and property `name`.

Could you check one more time? @RyanZim

**Comment by skatpgusskat** [comment]
OH Nevermind, It was the problem of my node version. My node version was 8, and after update to 12, readdir return fs.Dirent.
reference : https://stackoverflow.com/questions/52219308/cant-get-array-of-fs-dirent-from-fs-readdir
