### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined on import

### ISSUE THREAD

**Issue by echyam** [jprichardson/node-fs-extra#712]
I get this error just by importing `fs-extra` (using the library within within a Jupyter extension) and not actually using the library yet.
```
const fs = require('fs-extra');
```
full error:
```
TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (graceful-fs.js:63)
    at Object.DadK (graceful-fs.js:279)
    at __webpack_require__ (bootstrap:83)
    at Object.8B1V (index.js:5)
    at __webpack_require__ (bootstrap:83)
    at Object.mgea (index.js:6)
    at __webpack_require__ (bootstrap:83)
    at new JobCache (hysds.js:21)
    at Object.bvAu (index.js:29)
    at __webpack_require__ (bootstrap:83)
```

- **Operating System:** macOS High Sierra 10.13.6
- **Node.js version:** v8.11.3
- **`fs-extra` version:** 8.1.0
possibly a duplicate of #711

**Comment by RyanZim** [comment]
What's webpack doing in here?

**Comment by echyam** [comment]
Jupyter uses that to build extension code and create output files

**Comment by proteria** [comment]
My guess is that Jupyter’s webpack filled in an empty object for `require('fs')` and the bug is with Jupyter’s webpack config.

**Comment by echyam** [comment]
@proteria  Yes, that is exactly what happens, and I was (maybe naively) hoping fs-extra would have an independent installation.  Would there be a way to get around the empty webpack object?

**Comment by RyanZim** [comment]
I'm not familiar enough with Jupyter to know.

**Comment by proteria** [comment]
@echyam That’s a bug with Jupyter and you should take it with them.

**Comment by echyam** [comment]
Okay, thanks.  Just to make sure I understand the issue - is the fs package required and webpack fills it with an empty object, or is it actually unnecessary, and I only need fs-extra?

Asking because inside the empty fs package was this README:
```
This package name is not currently in use, but was formerly occupied
by another package. To avoid malicious use, npm is hanging on to the
package name, but loosely, and we'll probably give it to you if you
want it.
```

**Comment by proteria** [comment]
@echyam Yes, because `fs-extra` is a wrapper for `fs`.

The `fs` package on NPM is a placeholder and not the real package. The real one comes included by Node.js and always take precedence even if you have a package called `fs` under `node_modules`.

**Comment by echyam** [comment]
Thanks, closing the issue
