### ISSUE TITLE
ReadJSON

### ISSUE THREAD

**Issue by sam13591980** [jprichardson/node-fs-extra#715]
Hello,
I have a JSON file that has utf-8 characters such as ä.
When I read the JSON with utf8 encoding still fs-extra could not show the character.
Basically I use 

```
fsExtra.readJson('test.json',{encoding: 'utf8'}).then(json=>{

})
```

Is it a bug in Fs-extra?

**Comment by manidlou** [comment]
@sam13591980 I cannot reproduce it! I tested out and it shows the character correctly for me with and without the `encoding` option. I ran it on ubuntu. Maybe something else going on with your system or something like that! What is your OS?

**Comment by RyanZim** [comment]
Closing for lack of response.
