### ISSUE TITLE
[REQUEST] emptyDir return the number of files deleted

### ISSUE THREAD

**Issue by tabarra** [jprichardson/node-fs-extra#719]
One thing I'm missing from `del` was getting the count of files deleted, it helps a lot of various situations.  
  
Would it be possible (and consistent) to add a numeric return for this method?

**Comment by paragi** [comment]
This would come with a performance penalty. Especially for large directories.
If implemented, I would suggest that it's optional.

**Comment by RyanZim** [comment]
This is an edge-case, use `del` if you need this functionality.
