### ISSUE TITLE
rename from A.txt to a.txt fail 

### ISSUE THREAD

**Issue by Leaking** [jprichardson/node-fs-extra#721]
- **Operating System:** 
Darwin QUINNHZCHEN-MC0 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
- **Node.js version:**
v10.15.0
- **`fs-extra` version:**
v8.1.0

like

```javascript
const fs = require('fs-extra')
fs.move('a', 'A')
```
error

```html
Error: Source and destination must not be the same.
```

**Comment by RyanZim** [comment]
By default, Darwin is case-insensitive. So `a` & `A` are the same.
