### ISSUE TITLE
Documentation: readFile is not in the README on front page

### ISSUE THREAD

**Issue by njlr** [jprichardson/node-fs-extra#722]
This is such a common function I think it should be there. I had to look into the source code to find it. 

- **Operating System:** N/A
- **Node.js version:** N/A
- **`fs-extra` version:** `d1a01e735e81688e08688557d7a254fa8297d98e`

**Comment by RyanZim** [comment]
`readFile` is a native `fs` method; the README clearly states:

> `fs-extra` is a drop in replacement for native `fs`. All methods in `fs` are attached to `fs-extra`.

> You can still use the native Node.js methods. They are promisified and copied over to `fs-extra`.
