### ISSUE TITLE
Drop support for old Node

### ISSUE THREAD

**Issue by EsTharian** [jprichardson/node-fs-extra#725]
We may depreciate Node version >=6 <7 for using async functions more free.

**Comment by RyanZim** [comment]
Node 6 should be dropped in the next major release.

**Comment by JPeer264** [comment]
Please do not forget to also update this line:

https://github.com/jprichardson/node-fs-extra/blob/master/package.json#L6

**Comment by RyanZim** [comment]
Node 6 & 8 will be dropped in the next major. Milestoning so it's obvious
