### ISSUE TITLE
copySync Cannot Copy Documents Folder on Windows

### ISSUE THREAD

**Issue by danielehrhardt** [jprichardson/node-fs-extra#726]
- **Operating System:**
Windows 10 Pro 64 bit
- **Node.js version:**
v10.16.0
- **`fs-extra` version:**
v8.1.0

If i use copy or copySync to copy the Documents Folder on Windows i get the following Error:
```
RROR Error: Uncaught (in promise): Error: EPERM: operation not permitted, symlink 'C:\Users\daniel.ehrhardt\Pictures' -> 'C:\temp\Eigene Bilder'
Error: EPERM: operation not permitted, symlink 'C:\Users\daniel.ehrhardt\Pictures' -> 'C:\temp\Eigene Bilder'
```

My User is a AD User. 
My Command:
`copySync('C:\\Users\\daniel.ehrhardt\\Documents', 'C:\\temp');`

I do not Understand why, the folder Pictures is not in the Documents Folder.

**Comment by RyanZim** [comment]
That does seem weird. First off, you command is incorrect, if you're copying Documents to temp, you probably want it copied to `C:\temp\Documents`, you need to put that explicitly in the destination.

**Comment by danielehrhardt** [comment]
> That does seem weird. First off, you command is incorrect, if you're copying Documents to temp, you probably want it copied to `C:\temp\Documents`, you need to put that explicitly in the destination.

Same Problem with `C:\temp\Documents`
Could you reproduce it?

**Comment by Inve1951** [comment]
Those are not actual folders but Windows "Libraries". They are gruesome to deal with in many situations and as such should be avoided IMO.

Some reading material: https://docs.microsoft.com/en-us/windows/client-management/windows-libraries

@danielehrhardt While i haven't tested this I guess that your command tries to copy the symlink (if it even is one) to `/temp`. You can try to use `{dereference: true}` as a third argument or copy each contained file/folder separately.

In the event that you do want to copy/create symlinks you'll need the [SECreateSymbolicLinkPrivilege](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links) privilege. (The Administrators AD group has that by default already.)

**Comment by brodybits** [comment]
> In the event that you do want to copy/create symlinks you'll need the [SECreateSymbolicLinkPrivilege](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links) privilege.

I think it *should* be possible to create _junction_ symlinks on Windows without administrators priv, see discussion in #626 /cc @oliversalzburg

**Comment by Inve1951** [comment]
@brodybits I don’t know about junctions but you do need said privilege for _regular_ directory symlinks.

**Comment by danielehrhardt** [comment]
Yes, the Problem are the junctions 
![image](https://user-images.githubusercontent.com/19570043/71695367-3253c200-2db2-11ea-862b-8e81f1afbf3b.png)

**Comment by danielehrhardt** [comment]
> You can try to use `{dereference: true}`

Is also not working

**Comment by RyanZim** [comment]
You're best off using Windows native utilities for copying these core directories.

**Comment by danielehrhardt** [comment]
> You're best off using Windows native utilities for copying these core directories.

This is how you fix Problems?

**Comment by RyanZim** [comment]
Node.js itself has very poor support for the various kinds of symlinks on Windows. If you want to dig in, find the problem, and submit a PR, you're welcome to. I cannot dedicate time to this.

**Comment by oliversalzburg** [comment]
Just FYI, NodeJS is not able to distinguish a junction from other types of links on Windows. I implemented https://github.com/oliversalzburg/is-junction to work around this issue and solve this issue in our world.

My attempts to have this integrated into NodeJS was just met by grumpy developers/maintainers who did not see the point apparently.
