### ISSUE TITLE
Avoid using map and foreach when possible

### ISSUE THREAD

**Issue by exx8** [jprichardson/node-fs-extra#727]
I noticed that for some of the implementations, map and foreach are used.
Though they are very clean to write, they have some performance cost, while for... of doesn't
for example:
https://github.com/jprichardson/node-fs-extra/blob/d1a01e735e81688e08688557d7a254fa8297d98e/lib/empty/index.js#L37
this might be costly, especially with recursive functions.

see also:
https://codeburst.io/javascript-performance-test-for-vs-for-each-vs-map-reduce-filter-find-32c1113f19d7
May I send a PR?

**Comment by RyanZim** [comment]
I'm not a fan of sacrificing readability for performance. Furthermore, we are dealing with sub-milisecond differences in performance; unless you are running many, many iterations, there is no chance for this to be an appreciable performance difference. Keep in mind, the human brain perceives anything less than 200ms as instantaneous. IMO, this is premature optimization.
