### ISSUE TITLE
To add another case where it'd be nice to support this: I use a glob to find a bunch of files in different directories, and I'd like to copy them all to the same directory.  So I've got something like:

### ISSUE THREAD

**Issue by Tatsujinichi** [jprichardson/node-fs-extra#731]
This is my use case.  
And I do not expect the default behavior.

To add another case where it'd be nice to support this: I use a glob to find a bunch of files in different directories, and I'd like to copy them all to the same directory.  So I've got something like:

```js
// Not really hardcoded, but returned from a glob query
const input = [
    'absolute/path/to/some/file.img',
    'absolute/path/to/some/other/file.img',
    'absolute/path/to/somewhere/else.img'
];
```

What I'd like to do is:

```js
input.map(path => fs.copy(filePath, 'ouputDir'))
```

But instead I've got to do:

```js
input.map(path => fs.copy(filePath, path.join('outputDir', path.basename(filePath))
```

It's not a showstopper, but I find the first hypothetical snippet a lot more readable.

_Originally posted by @Retsam in https://github.com/jprichardson/node-fs-extra/issues/323#issuecomment-424500664_

**Comment by RyanZim** [comment]
We stand by the position in #323
