### ISSUE TITLE
Preserved timestamps include microseconds

### ISSUE THREAD

**Issue by ianbytchek** [jprichardson/node-fs-extra#732]
- **Operating System:** macOS
- **Node.js version:** v12.12.0
- **`fs-extra` version:** 8.1.0

```js
fs.copySync(newImagePath, oldImagePath, {preserveTimestamps: true});
console.log(fs.statSync(newImagePath).mtimeMs); // 1573110917678
console.log(fs.statSync(oldImagePath).mtimeMs); // 1573110917677.5437
```

Comparing `mtime` produces false results, which can be a problem.

**Comment by RyanZim** [comment]
Basically a dupe of https://github.com/jprichardson/node-fs-extra/issues/571; see discussion there.
