### ISSUE TITLE
moveSync error does not have code property

### ISSUE THREAD

**Issue by bmuenzenmeyer** [jprichardson/node-fs-extra#734]
- **Operating System:** Windows, and online REPLs
- **Node.js version:** `12.13.0`
- **`fs-extra` version:** `8.1.0`

First reported within https://github.com/facebook/create-react-app/issues/7892 - `moveSync` errors thrown when the destination already exist do not have `EEXISTS` as a `code` property, causing defensive try catches (in that thread) to fall through

I [isolated this behavior](https://github.com/facebook/create-react-app/issues/7892#issuecomment-557137738) outside of CRA, and I think it serves as a proper reduced test case to discuss further.

✔️  [fs-extra@7.0.1 `moveSync` behavior with error.code](https://repl.it/repls/DopeyMarvelousSynergy)
❌  [fs-extra@8.1.0 `moveSync` behavior without error.code](https://repl.it/repls/LimitedImmaterialDefinitions)

**Comment by RyanZim** [comment]
Yeah, for a time we tried to fake native Node errors, but gave up on it since they're impossible to completely properly replicate.

**Comment by bmuenzenmeyer** [comment]
so in your opinion, downstream code should be matching against `dest already exists`

**Comment by RyanZim** [comment]
Yeah, should have been clearer in the release notes; 8.0.0 did a lot of changes to `move` and `moveSync`, many of which were breaking
