### ISSUE TITLE
@types typescript typings for returned promises does not exist.

### ISSUE THREAD

**Issue by goldingdamien** [jprichardson/node-fs-extra#738]
@types does not seem to be handling returned promises.

In VS Code the following information is provided(fs.exists as an example):
```
function exists(path: PathLike, callback: (exists: boolean) => void): void
namespace exists
Expected 2 arguments, but got 1
```

- **Operating System: Windows 10**
- **Node.js version: 12.1.0**
- **`fs-extra` version: 8.1.0**

**Comment by JPeer264** [comment]
Yes in the Node typings a callback is required (as defined [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v10/fs.d.ts#L1499)). For making this work you could open either a PR or an issue in the repo [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) as they are responsible for typings.

You could add a function overload like it is made with the typings for "copy" or "move".

The `fs-extra` typings are [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/fs-extra/index.d.ts)

**Comment by RyanZim** [comment]
Yes, if someone wants to update the types, go for it. I can't maintain them.
