### ISSUE TITLE
yet a CLI for fs-extra

### ISSUE THREAD

**Issue by atao60** [jprichardson/node-fs-extra#739]
Since issue [CLI equivalent for fs-extra #184](https://github.com/jprichardson/node-fs-extra/issues/184), it doesn't seem the situation has changed...

So as my first attempt to create an actual project of CLI with npm: [@atao60/fse-cli](https://www.npmjs.com/package/@atao60/fse-cli).

I'll try in the next days to add more tests and more functionalities of fs-extra. Already existings: copy, ensureDir, remove, emptyDir, ensureFile, move.

I'd be pleased to receive any of yours comments.

**Comment by RyanZim** [comment]
Thanks for posting!
