### ISSUE TITLE
copy filter option logic

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#742]
Currently in `copy`, the filter option is checked for each path including the src directory itself. I feel like we shouldn't check the filter option for the src or root directory mainly because it makes the filter function looks a little weird when our users need to use it since they always have to skip the src directory in order to get their desired results. Also, most of the time users know what their src directory is and they write the filter function mostly for the children paths of the src directory.

So, what do you think about changing the code so that we always skip the src directory in the filter function by default, or if we want to be fancy we can make it optional so that our users choose what behavior they want.

@jprichardson @RyanZim @JPeer264 what do you guys think?

**Comment by RyanZim** [comment]
No more options; that I'm firm on. As for changing the default behavior, I totally see the logic for skipping the source directory. If we were building from scratch, I'd be in favor of doing it that way. The question is: given how much this module is used; is it worthwhile causing disruption for all existing users?

**Comment by manidlou** [comment]
I see your point @RyanZim! That makes sense. This change will probably break lots of user code! So, I am fine ignoring this.

**Comment by RyanZim** [comment]
Gonna leave this open for input from the other maintainers

**Comment by RyanZim** [comment]
Gonna close this out; enough time has passed. If you want to say something, feel free to reopen and say it.
