### ISSUE TITLE
Formatting is omitted when cb is not passed to outputJson()

### ISSUE THREAD

**Issue by sreuter** [jprichardson/node-fs-extra#752]
- **Operating System: OSX** 10.13.6
- **Node.js version:** 12.4.1
- **`fs-extra` version:** 8.1.0

Not sure if expected, but if you miss passing a callback to outputJson() the file is actually still being created, but without formatting.

**Comment by RyanZim** [comment]
If you don't pass a callback, `outputJson` works with promises, and returns a promise. However, I'm not sure I'm understanding your point about formatting?

**Comment by sreuter** [comment]
It's writing the file if callback is omitted, but not in a formatted fashion. It's missing spaces and new lines.

**Comment by RyanZim** [comment]
If you call `outputJson` with a callback, you don't get spaces or newlines either; the default is no formatting. You must pass `spaces` option for formatting.

**Comment by sreuter** [comment]
I swear I had that, and it just happened when I was missing passing a callback. I should have taken a screen recording, as I can't reproduce it anymore :) Anyway, thanks for your swift replies!
