### ISSUE TITLE
Unix commands vs. fs-extra functions

### ISSUE THREAD

**Issue by manidlou** [jprichardson/node-fs-extra#753]
Something that I keep seeing in users' comments is that users expect `fs-extra` functions to have the same behavior/implementation as unix commands `cp, mv, rm...`.

At least, I couldn't find anywhere in the docs that specifies we follow unix or posix or any other specs. 

I think it is a good idea to clarify this for our users. So my question is, what should we do here? Should we follow some specs or we should specify in the docs that we don't follow any specs?

**Comment by RyanZim** [comment]
I'm not interested in following specs for command-line *nix tools. The assumption probably comes from our function naming; also this could be improved:

https://github.com/jprichardson/node-fs-extra/blob/a6b1a441ef60f3b6357c1d9b00f479c45d61fb08/package.json#L4

**Comment by manidlou** [comment]
Yeah I'm not interested in following specs neither! I just wanna make sure it is clear for our users that we don't follow any specs and they shouldn't expect `fs-extra` functions to have the same behavior as unix commands.

**Comment by RyanZim** [comment]
Do you want to submit a docs PR for this? Feel free to improve the npm description while you're at it.

**Comment by RyanZim** [comment]
Looking closer, [`copy*`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/copy.md), [`ensureDir*`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/ensureDir.md), & [`remove*`](https://github.com/jprichardson/node-fs-extra/blob/master/docs/remove.md) all contain statements such as:

> Like `cp -r`.

Should we remove these statements, or clarify that they're similar, but not the same?

**Comment by RyanZim** [comment]
@manidlou bump

**Comment by manidlou** [comment]
I would say we remove them (I am still fine if you guys decide to edit them to be clear) but I don't understand how this would be helpful to users because they are ultimately different implementations and I think keeping them in the docs still leave some confusion around this!
