### ISSUE TITLE
Remove fs.copyFile fallback

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#754]
Now that https://github.com/jprichardson/node-fs-extra/pull/751 is merged, there's no reason to have a fallback for `fs.copyFile`/`fs.copyFileSync`. We should remove them from the `copy` implementation.

**Comment by RyanZim** [comment]
@manidlou are you up to this, or shall I do it?

**Comment by manidlou** [comment]
@RyanZim I will take care of it. I really appreciate all your work!
