### ISSUE TITLE
status of createSymlink and createSymlinkSync

### ISSUE THREAD

**Issue by davidjgoss** [jprichardson/node-fs-extra#758]
These methods are exposed on the main export of `fs-extra`:

- `createSymlink`
- `createSymlinkSync`

But they aren't documented (and, I assume consequently, they aren't in the community-published typings).

Should these be added to the documentation? Or is the intent for users to just use `ensureSymlink` - and if so should these be omitted from the main export?

**Comment by RyanZim** [comment]
Yeah, that's a mistake that they weren't documented. However, I'm considering removing the `create*` aliases in the next major release.
