### ISSUE TITLE
Cannot move file to change case on case insensitive fs

### ISSUE THREAD

**Issue by wmertens** [jprichardson/node-fs-extra#759]
When calling move() it checks if the destination exists, and if it does it refuses to call `rename`. This means you can't change the case on a case-insensitive file system.

Fs-extra should check that the destination has the same inode before refusing to move.

https://github.com/jprichardson/node-fs-extra/blob/40c3d68eb4fc4aa9a3c5624b4160610af296ec2e/lib/move/move.js#L41

**Comment by manidlou** [comment]
@wmertens can you provide us with repro test case please?

**Comment by wmertens** [comment]
The test itself is really simple: try to rename a file from lowercase to uppercase, it will fail when executed on a case-insensitive fs. The question is, can your test suite simulate that?

**Comment by manidlou** [comment]
@wmertens I finally found some time to dig into your case! So here is what I found:

1. I appreciate if you would respect our issue template and respond to 3 simple questions that would help us resolve YOUR issue faster!
2. If you are using the latest version of `fs-extra`, we actually check the inodes of src and dest (as well as other properties) to determine if src and dest are the same before moving! However I just realized that implementation doesn't support cases like yours (when you want to just change the case) and I am working on that!
3. We actually have a [test file](https://github.com/jprichardson/node-fs-extra/blob/master/lib/move/__tests__/move-case-insensitive-paths.test.js) for cases like this, however again I just realized that those tests are broken for case-insensitive systems! Currently for case-insensitive systems those tests expect an error thrown however the corect behavior should allow users change the case for case-insensitive systems! and I am working on that too!

**Comment by manidlou** [comment]
@wmertens I still don't understand how you get `dest already exists` error because with the latest version you get `Source and destination must not be the same` which is still not correct behavior for case-insensitive systems! That's why I asked you to give us an exact test case that would address your issue and you refused to do that too! So I am sorry from my perspective you don't have respect for this project and its maintainers' time!
