### ISSUE TITLE
Missing Error Stack on copy, move

### ISSUE THREAD

**Issue by CxRes** [jprichardson/node-fs-extra#769]
I do not see an error stack when copy or move fails (at least with ENOENT). In particular logging `error.stack` just prints the error message.

- **Operating System:** Windows 10 x64
- **Node.js version:** 12.16.1
- **`fs-extra` version:** 8.1.0

**Comment by CxRes** [comment]
It also prints the error in a weird Array and Object: 
```sh
[Error: ENOENT: no such file or directory, stat 'D:\Users\Rahul\dev\test-data\data5\aaag'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'D:\\Users\\Rahul\\dev\\test-data\\data5\\aaag'
}
```

**Comment by RyanZim** [comment]
This is how async errors work in Node. You'll get the same result using the native `fs.copyFile` function.
