### ISSUE TITLE
fs.move fails to move directory after a long delay

### ISSUE THREAD

**Issue by quinton-ashley** [jprichardson/node-fs-extra#770]
- Operating System: Windows 10
- Node.js version: 12.13.0
- electron version: 8.1.1
- `fs-extra` version: 8.1.0
```
Error: EPERM: operation not permitted, rename 'D:\emu\MAME' -> 'D:\emu\arcade'
```
After a long delay, await fs.move fails to move directory.

**Comment by RyanZim** [comment]
You have some kind of a permission issue, as indicated by the error. The reason it's so slow to error out is that in some cases, antivirus software can cause a temporary `EPERM` error, so we retry a bit for such errors before throwing.

**Comment by quinton-ashley** [comment]
But there shouldn't be a permissions issues. I have read/write/modify access on that directory.

**Comment by RyanZim** [comment]
Try using `fs.rename` directly, and see if you get the same error.

**Comment by quinton-ashley** [comment]
I just tried it and I get the same error.  Does it matter that this directory has a lot of files in it?

**Comment by RyanZim** [comment]
If you're getting an error with `fs.rename`, this is not an issue with fs-extra. The fact that it works with an empty directory indicates you probably have a file somewhere in `D:\emu\MAME` structure that you don't have proper file permissions to move.

**Comment by quinton-ashley** [comment]
If that is the problem then fs-extra should have a better error warning to show which file or folder inside `D:/emu/MAME` it is unable to move.

**Comment by RyanZim** [comment]
We can't give you better errors than what Node.js core's own `fs.rename` gives us.
