### ISSUE TITLE
Moving files from `/a/a` to `/a`

### ISSUE THREAD

**Issue by shuangwhywhy** [jprichardson/node-fs-extra#772]
- **Operating System:** MacOS Catalina 10.15.3 (19D76)
- **Node.js version:** 13.11.0
- **`fs-extra` version:** 9.0.0

move/moveSync and rename/renameSync don't support moving `/a/a` to `/a`.

**Comment by RyanZim** [comment]
Yes, this is expected. I'm not sure what you're exactly trying to do here; do you want to move the files in `/a` and have them reside in `/a/a`?

**Comment by resistdesign** [comment]
The bash equivalent of this might be something like:

```bash
# Move the target to a temporary location...
cp /a/a /b/a
# ... because a removal is required.
rm -rf /a
# Move the temporary target to the destination.
mv /b/a /a
```

Note that I've included the `-rf` to expose the fact that you *may* need to remove other files and/or directories which reside in the initial `/a` directory.

This *could* be done if you are intending to clear the other contents of directory `/a` AND there is a designated temporary directory to hold the file at `/a/a` while a removal takes place.

Additionally, `/a/a` itself could be a directory, which may or may not come with further considerations.

**Comment by resistdesign** [comment]
@shuangwhywhy Is this a "merge and remove" scenario or a "raise and replace" scenario?

**Comment by resistdesign** [comment]
@RyanZim How would you express either copying or moving files from a directory `/a/a` to its parent `/a` directly?

**Comment by RyanZim** [comment]
@resistdesign Yep, you'd have to copy each file directly

**Comment by resistdesign** [comment]
@RyanZim Sounds like a `job` for `glob`!
Any chance of adding `glob` support for things like this maybe?

**Comment by RyanZim** [comment]
That takes complexity to a whole new level.

Actually, for that task, you don't need glob:

```js
const files = await fs.readdir('/a/a')
await Promise.all(files.map(file => 
  fs.move(path.join('/a/a', file), path.join('/a', file))
))
await fs.remove('/a/a')
```

**Comment by resistdesign** [comment]
@RyanZim Does `readdir` get nested paths?

**Comment by dongliutony** [comment]
This is a smart approach.
