### ISSUE TITLE
fs.mkdirpSync Syntax error

### ISSUE THREAD

**Issue by elipeters** [jprichardson/node-fs-extra#780]
- **Operating System: Windows 10 Pro 17134.1246**

- **Node.js version: v8.9.4**
- **`fs-extra` version: 9.0.0**

I'm getting a syntax error with `fs.mkdirpSync(path)`.

Apologies for not sourcing the issue (if there is one) as `mkdirp.sync(path)` is working for me. Node version could be the issue **>=10**.

```
error:` Sending 500 ("Server Error") response:
 D:\Websites\poppyboogers\git\local\node_modules\fs-extra\lib\mkdirs\make-dir.js:86
      } catch {
              ^

SyntaxError: Unexpected token {`
```

**Comment by RyanZim** [comment]
Yes, you need to use Node 10

**Comment by debugly** [comment]
@RyanZim Please Help me，occurred error:

┏ Electron -------------------

  /Users/qianlongxu/Documents/GitWorkSpace/MRAssistant/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
        } catch {
                ^
  
  SyntaxError: Unexpected token {
      at createScript (vm.js:80:10)
      at Object.runInThisContext (vm.js:139:10)
      at Module._compile (module.js:606:28)
      at Object.Module._extensions..js (module.js:653:10)
      at Module.load (module.js:561:32)
      at tryModuleLoad (module.js:504:12)
      at Function.Module._load (module.js:496:3)
      at Module.require (module.js:586:17)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (/Users/qianlongxu/Documents/GitWorkSpace/MRAssistant/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
  
┗ ----------------------------

┏ Electron -------------------

  Failed to fetch extension, trying 4 more times
  
┗ ----------------------------

### My source code:

```
import fse from 'fs-extra'
const userData = path.join(app.getPath('userData'), 'data')
  console.log(userData)
  try {
    fse.mkdirpSync(userData)
  } catch (error) {
    console.error(error)
  }
```

### My environments:

```
➜  MRAssistant node -v                    
v12.16.2
➜  MRAssistant npm -v     
6.14.4
➜  MRAssistant npm list fs-extra
mrassistant@0.0.1 /Users/qianlongxu/Documents/GitWorkSpace/MRAssistant
├─┬ electron@2.0.18
│ └─┬ electron-download@3.3.0
│   └── fs-extra@0.30.0 
├─┬ electron-builder@20.44.4
│ ├─┬ app-builder-lib@20.44.4
│ │ └─┬ temp-file@3.3.7
│ │   └── fs-extra@8.1.0 
│ ├─┬ fs-extra-p@8.1.0
│ │ └── fs-extra@8.1.0 
│ └─┬ read-config-file@3.2.2
│   └─┬ fs-extra-p@7.0.1
│     └── fs-extra@7.0.1 
└── fs-extra@9.0.1 
```

**Comment by RyanZim** [comment]
@debugly your running this in electron? Your electron version is super outdated, upgrading electron should fix this issue.
