### ISSUE TITLE
ensureSymlink silently exits if the destination exists and is not a symlink 

### ISSUE THREAD

**Issue by CxRes** [jprichardson/node-fs-extra#786]
Looking into the code, I found that ensure* methods only verify if the destination path exist and not if the path is of the right * type. IMHO an error should be thrown if path is of the wrong type. Perhaps `fs.stat` instead of `fs.access` should suffice...

**Comment by RyanZim** [comment]
Yep, `ensureFile` has checks in place, but it looks like `Link`/`Symlink` don't. Milestoning for v10 since this would be a breaking change, technically.
