### ISSUE TITLE
Error: Source and destination must not be the same

### ISSUE THREAD

**Issue by ashubham** [jprichardson/node-fs-extra#792]
- **Operating System:** Mac OS

- **Node.js version:** 12.11.0
- **`fs-extra` version:** 8.1.0

When copying over symlinks to a destination, the above error occurs if the symlink already exists on the destination directory. The workaround is to clean the `destination` before copying.

**Comment by manidlou** [comment]
@ashubham can you please provide us a reproducible test case?

**Comment by RyanZim** [comment]
Closing for lack of response.
