### ISSUE TITLE
why is node-fs-extra not merged into nodejs source code?

### ISSUE THREAD

**Issue by anlexN** [jprichardson/node-fs-extra#793]
- **Node.js version: all
- **`fs-extra` version: all

**Comment by RyanZim** [comment]
Node.js core tries to mostly expose the low-level filesystem APIs, with minimal abstractions. This is changing, though; for example, Node now has recursive mkdir; fs-extra supports it for older versions of Node that don't have that feature, when those versions are no longer supported, fs-extra will either be an alias of the Node method, or we'll remove the method. So more and more of fs-extra is moving to Node core.

**Comment by brodybits** [comment]
> So more and more of fs-extra is moving to Node core.

Does this mean that fs-extra could go away, or would the maintainers consider adding some more new functionality in the future?

I was just curios. My thanks to the owners and maintainers for this nice package.

**Comment by RyanZim** [comment]
@brodybits I don't see it going away, the amount of functionality added may decrease, though.
