### ISSUE TITLE
Getting errors importing from invalid catch line.

### ISSUE THREAD

**Issue by bryanvpham** [jprichardson/node-fs-extra#796]
https://github.com/jprichardson/node-fs-extra/blob/a2738d390694ae8dc32a8c27e76db08c9963e570/lib/mkdirs/make-dir.js#L85

Version: 9.0.0

**Comment by JPeer264** [comment]
This is intended. Please install Node v10+ to make it work with fs-extra@9

**Comment by JPeer264** [comment]
dup of #794
