### ISSUE TITLE
When using jest there seems to be a problem when deleting a file or a folder on Windows

### ISSUE THREAD

**Issue by federicobozzini** [jprichardson/node-fs-extra#804]
- **Operating System:**Windows 10
- **Node.js version:**10.16
- **`fs-extra` version:**9.0.0

When using jest it seems there might be a problem when deleting a file or a folder on Windows . The error seems to stem from the rimraf-like code. See https://github.com/isaacs/rimraf/issues/208.

**Comment by RyanZim** [comment]
Fixed in https://github.com/jprichardson/node-fs-extra/pull/805.
