### ISSUE TITLE
Recursive fs.rmdir / fs.rm

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#806]
Node core has added an experimental `recursive` option to `fs.rmdir` in https://github.com/nodejs/node/pull/29168; first released in v12.10.0.

Docs: https://nodejs.org/api/fs.html#fs_fs_rmdir_path_options_callback

I'm hesitant to use this as long as it's experimental in Node core, but just opening an issue to track this.

**Comment by RyanZim** [comment]
This is no longer experimental in v14.13.1: https://github.com/nodejs/node/pull/35171 However, in response to https://github.com/nodejs/node/issues/34278, the loose `rimraf`-like behavior that swallows errors and deletes directories is deprecated.

Instead, an `fs.rm` method with `recursive` and `force` options has been added in v14.14.0: https://github.com/nodejs/node/pull/35494

Docs: https://nodejs.org/api/fs.html#fs_fs_rm_path_options_callback

I don't think it's wise to use `recursive` `fs.rmdir`, given that the behavior we want is deprecated. However, we should consider using `fs.rm`, with the goal of removing `fse.remove` when `fs.rm` is present on all supported Node versions.

**Comment by fregante** [comment]
> the behavior we want is deprecated

Is it? It's just no longer the default. From what I see it's still there with `force: true`

**Comment by RyanZim** [comment]
@fregante It's the behavior on `fs.rmdir` that's deprecated. `fs.rm` with `force: true` indeed is what we want, and that's not deprecated.
