### ISSUE TITLE
ensureSymlink doesn't accept Buffer type

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [jprichardson/node-fs-extra#810]
Hi,
The fs.ensureSymlink doesn't accept source or destination path as Buffer.
It will be quite handy as the native fs functions on symlink support it.

- Ubuntu 18.04
- Node v14.4.0
- fs-extra 9.0.0

**Comment by RyanZim** [comment]
Unfortunately, we can't support this, since we use the [`path`](https://nodejs.org/api/path.html) module internally, which does not work with Buffer paths, only strings.
