### ISSUE TITLE
Error: Cannot find module 'jsonfile/utils'

### ISSUE THREAD

**Issue by gvsrepins** [jprichardson/node-fs-extra#817]
Dependency error: 
Cannot find module 'jsonfile/utils'

- **Operating System:** Ubuntu 16.04 LTS
- **Node.js version:** v10.21.0
- **`fs-extra` version:** 9.0.1

**Comment by RyanZim** [comment]
Looks like your `jsonfile`, which is a sub-dependency of `fs-extra`, is out of date. Try running `npm install` (or `yarn` if you're using yarn). If that doesn't work, it's probably a problem with your lockfile. If that's the case, let me know if you're using npm or yarn, and we'll proceed from there.
