### ISSUE TITLE
try catch compatible Node.js8

### ISSUE THREAD

**Issue by luckykun** [jprichardson/node-fs-extra#821]
- **Operating System:** mac
- **Node.js version:** 8
- **`fs-extra` version:**  9.01
![image](https://user-images.githubusercontent.com/8158403/86591999-2f39c880-bfc5-11ea-9bdf-b0ff7952641d.png)

**Comment by RyanZim** [comment]
See https://github.com/jprichardson/node-fs-extra/pull/794
