### ISSUE TITLE
Why the same method returns different results

### ISSUE THREAD

**Issue by Cuixote** [jprichardson/node-fs-extra#827]
- **Operating System: Mac**
- **Node.js version: V10+**
- **`fs-extra` version: 9.0.1**
```javaScript
var fsExtra = require("fs-extra")

// dir1 not exist
var t1 = fsExtra.ensureDirSync('dir1')
// t1 is a string.
console.log(`t1 value: ${t1}`)
// dir1 exists
var t2 = fsExtra.ensureDirSync('dir1')
// t2 is undefined
console.log(`t2 value: ${t2}`)
```

![image](https://user-images.githubusercontent.com/10526614/89114161-fef22680-d4ab-11ea-9472-0e20dccc8fb2.png)

I hope whenever `ensureDirSync` is invoke, the return is a 'ensure' type.  `String` or other , whatever.

**Comment by RyanZim** [comment]
On modern versions of Node, `ensureDir` uses Node core's recursive `mkdir` under the hood, and mirrors its behaviour:

```js
const fs = require('fs')
const t1 = fs.mkdirSync('dir1', { recursive: true })
const t2 = fs.mkdirSync('dir1', { recursive: true })
console.log(t1, t2)
```

This is documented in the Node docs: https://nodejs.org/api/fs.html#fs_fs_mkdirsync_path_options

> Returns undefined, or if recursive is true, the first directory path created.

Not that on Node versions older than v10.12.0, a different implementation is used, and `fs-extra` does not have a documented return value. Therefore, the return value for `fse.ensureDir*` should not be relied on.
