### ISSUE TITLE
Add docs to explain whether `move` supports directories as destination

### ISSUE THREAD

**Issue by Pomax** [jprichardson/node-fs-extra#830]
Given that `mv somefile.txt textfiles` will happily move a file `somefile.txt` into a dir `textfiles`, one might expect `move('somefile.txt', 'textfiles')` to work, but the docs currently do not explain what a valid `dest` is. Could the docs be amended to make it explicit whether `dest` must be a file path, or whether any path is valid?

**Comment by RyanZim** [comment]
Sure, PR welcome.
