### ISSUE TITLE
Overwriting rename is not atomic

### ISSUE THREAD

**Issue by wmertens** [jprichardson/node-fs-extra#835]
- **Operating System:** Linux 5
- **Node.js version:** 12
- **`fs-extra` version:** latest

As you can see in https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/move/move.js#L34-L37, when overwriting, the target is first removed. This is not an atomic operation and can leave the target removed but the source in place.

However, the [rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback) call already removes the target, and this is an atomic operation.

So IMHO, `move` should only check if the target exists when not overwriting, it should not delete the file itself. (and if the source and target have the same inode, it should not count as already existing, #801)

**Comment by RyanZim** [comment]
Ah, good point; PR welcome to fix this.

**Comment by RyanZim** [comment]
Set out to fix this today; I didn't read the docs close enough:

> In the case that `newPath` already exists, it will be overwritten. If there is a directory at `newPath`, an error will be raised instead.

We support moving dirs, and at this stage in the code, we know nothing about the state of the destination. We're gonna have to be non-atomic for dirs anyhow; so I'm going to elect to leave this as-is. If you're working with files only, and you need perfect atomic behavior, use `fs.rename` directly.
