### ISSUE TITLE
Error while moving a directory

### ISSUE THREAD

**Issue by Ladvace** [jprichardson/node-fs-extra#836]
I'm trying to move a file instead of file but it doesn't work. I get the following error:
```
[Error: EPERM: operation not permitted, rename 'SRC' -> 'DIST'] {
[1]   errno: -4048,
[1]   code: 'EPERM',
[1]   syscall: 'rename',
[1]   path: 'SRC',
[1]   dest: 'DIST'
[1] }
```
Can you move a directory instead of a file?

I then tryied copying it (with the `Copy ` method) and it worked.
- **os: win10**
- **node-version: 14.12.0**
- **`fs-extra` version: ^8.1.0**

**Comment by RyanZim** [comment]
Your `fs-extra` version is out of date. Also ensure you have proper file permissions to modify the source, copying only requires read permissions.
