### ISSUE TITLE
Concurrency for writing

### ISSUE THREAD

**Issue by MartinMuzatko** [jprichardson/node-fs-extra#845]
- **Operating System:** Windows 10, Ubuntu 18.04 (WSL)
- **Node.js version:** 12.14.0
- **`fs-extra` version:** 9.0.1

Hi!

I am having one process that writes to the same file. We use a config file to store network interface configs written via rest api.
Given the dynamic nature of our software, it is not guaranteed  that writing the file is done before writing again. Especially in a microservice oriented structure.

**Example:**
``` js
[...Array(1000)].map((a, i) => fs.writeJSON('./a', { i }))
```

It is not able to tell, that the content of the file will be `{ "i": 999 }` at the end of all writes.
Instead I get results ranging from ~300 to ~900.

It would be nice if the underlying write would use an implementation such as [steno](https://www.npmjs.com/package/steno).
If you don't want to lock in yourself on some dependencies, it would be great to at least export a factory function where I can feed in the dependency for `fs` myself. This way, I only need to exchange writeFile, instead of wrapping the entire fs module overwriting all functions that make use of fs.writeFile (including writeJSON, writeFile, ...).

**Comment by RyanZim** [comment]
First off, in describing you're use-case, this seems like a place where you should probably consider using a database instead of writing to the filesystem.

This is a rare enough use-case, I don't think we can do anything here by default.

We've considered making the filesystem customizable, but decided against it due to complexity.

**Comment by MartinMuzatko** [comment]
* We decided against a database, because it holds some configuration that is needed before establishing a connection with the database. (DB access configuration is held inside ENV var though, appropriate for a twelve-factor-app)
* We decided against environment variables for some of the configuration, as it is dynamic (in length and changed during the process, we wouldn't want to restart the process after every change)

We use this config file in places where a message queue, in-memory db or a second db is just not appropriate.
I have to admit, this is a bit of an edge case. Maybe I can look into proposing a PR to make the fs customizable. If that is fine for you.

**Comment by RyanZim** [comment]
Making fs customizable is not an option on the table; it's extremely complex to do it right, and would greatly increase the maintenance burden here. Honestly, you're probably going to need to write your own `writeJSON` function, using something like `steno` under the hood.
