### ISSUE TITLE
Timeline for 10.0 release

### ISSUE THREAD

**Issue by abettadapur** [jprichardson/node-fs-extra#846]
Hi!
I love this library, but we are currently stuck on the 4.3 version because of #765 

Any word on when 10.0 is supposed to be released?

**Comment by RyanZim** [comment]
Sorry, I wish I could give you a timeline here, but I honestly can't. I haven't gotten time to work on this as much as I'd like; I'll see about putting more into this in the next couple weeks.

**Comment by abettadapur** [comment]
Thanks @RyanZim 
Do you think it would be possible to hotfix #765 to v9 branch?

**Comment by RyanZim** [comment]
@abettadapur No, https://github.com/jprichardson/node-fs-extra/pull/779 is a breaking change.

**Comment by RyanZim** [comment]
OK, this has been way longer than I anticipated, but I am actively working on v10 ATM, so should be soon. Closing this out for good housekeeping.
