### ISSUE TITLE
File not saving on github

### ISSUE THREAD

**Issue by CyberVictoryMan** [jprichardson/node-fs-extra#850]
Actually, when I save my file using the code in my system it works good. But when I try to save on github, It says success but when I  open the file, its blank
If I am wrong, I am so sorry to open in issue
I have already code upto 700 lines but now its like a trash

**Comment by RyanZim** [comment]
What do you mean "save on github"?

**Comment by CyberVictoryMan** [comment]
Sorry I mean If I try to update a JSON file, Its blank
This is my code
`const fs = require('fs-extra')
const customer = require('./filetest.json')
let curcus = customer.coins
customer.coins = curcus + 10
console.log(customer.coins)

fs.writeFile('./newCustomer.json', JSON.stringify(customer, null, 2), err => {
    if (err) {
        console.log('Error writing file', err)
    } else {
        console.log('Successfully wrote file')
    }
})`

**Comment by RyanZim** [comment]
Your code looks fine; I don't know what's causing this. `writeFile` is a normal `fs` function; what happens if you change `require('fs-extra')` to `require('fs')`?

**Comment by CyberVictoryMan** [comment]
Even I tried that and it did not save. It only works on system, not on github

**Comment by CyberVictoryMan** [comment]
Is there any Another option?

**Comment by CyberVictoryMan** [comment]
And can you try by creating a repository and commiting that file

**Comment by RyanZim** [comment]
If it doesn't work with plain `fs`, then this is not an issue with fs-extra; sorry, can't help further here.
