### ISSUE TITLE
File not pasting 

### ISSUE THREAD

**Issue by CyberVictoryMan** [jprichardson/node-fs-extra#851]
I tried to paste a file but it did not work only on github
why the copy and paste command is not working in github
Don't try to close this issue because this is an fs-extra

**Comment by RyanZim** [comment]
`fs-extra` does not even support anything related to copy/pasting; why are you opening issues here?

**Comment by CyberVictoryMan** [comment]
```fs.copy('./hehe.json', './hoho.json', err => {
  if (err) return console.error(err)
  console.log('success!')
})```
This is my code
