### ISSUE TITLE
copySync recursive is enabled or disabled by default?

### ISSUE THREAD

**Issue by kuworking** [jprichardson/node-fs-extra#855]
I am trying to copy a folder __NOT recursively__ (i.e. not including nested folders)

Looking at the docs, I'm not sure if nested folders will be copied or not

```
// copy directory, even if it has subdirectories or files
fs.copySync('/tmp/mydir', '/tmp/mynewdir')
```

It's not clear to me whether it includes or not the subdirectories

Also, I can see there is a `recursive` option there, but maybe deprecated? https://github.com/jprichardson/node-fs-extra/issues/205

Is this option enabled by default? Or disabled?

If enabled, can I disable it? Or should I use the filter to discard folders?

**Comment by RyanZim** [comment]
There is no `recursive` option in modern versions of `fs-extra`. `copySync` is recursive.
