### ISSUE TITLE
catch error  

### ISSUE THREAD

**Issue by wutw** [jprichardson/node-fs-extra#856]
- **Operating System:**
- **Node.js version:**
- **`fs-extra` version:*9.0.1*

![image](https://user-images.githubusercontent.com/30827002/103258026-8c3f9580-49ce-11eb-83bb-b2dba9f75bc7.png)

catch error

**Comment by RyanZim** [comment]
What's the problem?

**Comment by jerryOnlyZRJ** [comment]
> What's the problem?

It will throw a `SyntaxError: Unexpected token {` Error when the node‘s version is < 10.3

Cause [Optional Catch Binding](https://stackoverflow.com/questions/21624456/can-i-use-a-try-catch-in-javascript-without-specifying-the-catch-argument-identi)

**Comment by RyanZim** [comment]
If that's your problem, update your Node version. Not sure if that's what the OP is pointing to, though.

**Comment by Kennytian** [comment]
@jerryOnlyZRJ @RyanZim , My Node runtime version is v14.15.1, got same issue

```
export PATH="$PATH:/***/.nvm/versions/node/v14.15.1/bin"

...

nest build
out: 
err: /var/www/backend/yios-task-development/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
err:       } catch {
err:               ^
err: 
err: SyntaxError: Unexpected token {
err:     at createScript (vm.js:80:10)
err:     at Object.runInThisContext (vm.js:139:10)
err:     at Module._compile (module.js:616:28)
err:     at Object.Module._extensions..js (module.js:663:10)
err:     at Module.load (module.js:565:32)
err:     at tryModuleLoad (module.js:505:12)
err:     at Function.Module._load (module.js:497:3)
err:     at Module.require (module.js:596:17)
err:     at require (internal/module.js:11:18)

```

**Comment by RyanZim** [comment]
@Kennytian What is `nest build`?

**Comment by RyanZim** [comment]
@Kennytian Let's move your issue to https://github.com/jprichardson/node-fs-extra/issues/857; closing this one for lack of response from the OP.
