### ISSUE TITLE
no moveSync?

### ISSUE THREAD

**Issue by stevenvachon** [jprichardson/node-fs-extra#86]
Everything else seems to have a synchronous version.

**Comment by jprichardson** [comment]
Closing for now. This is something that I'm still very interested in and would accept a PR for. But at the moment, there are higher priorities (bugs) that I must address before I start adding new capabilities.

**Comment by cjroth** [comment]
+1

**Comment by VoidVolker** [comment]
+1

**Comment by ldong** [comment]
Use [fs.rename](https://nodejs.org/api/fs.html#fs_fs_rename_oldpath_newpath_callback)

**Comment by jwilcurt-salesforce-com** [comment]
+1

**Comment by sant123** [comment]
+1
