### ISSUE TITLE
EMFILE when using fse.readFile

### ISSUE THREAD

**Issue by chscott** [jprichardson/node-fs-extra#862]
- **Operating System:** Windows
- **Node.js version:** 12.8.1
- **`fs-extra` version:** 9.0.1

I'm seeing the following with this code snippet and a large number of files being read:

```javascript
const contents = await FSE.readFile(path, {
        encoding: 'utf8',
        flag: 'r',
      })
```

```
2021-01-19 16:25:47:147 - error: [main] Error: EMFILE: too many open files, open 'C:\ProgramData\foo.dat'
```

The readme indicates fs-extra uses graceful-fs to prevent EMFILE errors, but I also see some issues where it was reported that fs-extra wasn't using EMFILE in all cases. For example, https://github.com/jprichardson/node-fs-extra/issues/275 and https://github.com/jprichardson/node-fs-extra/issues/103. Is this another case where fs-extra doesn't use graceful-fs?

**Comment by RyanZim** [comment]
Nope, graceful-fs is used everywhere; have you verified the full stack trace of your error to ensure it's coming from this `fs-extra` call?

**Comment by chscott** [comment]
> Nope, graceful-fs is used everywhere; have you verified the full stack trace of your error to ensure it's coming from this `fs-extra` call?

Thanks for verifying. I suspect you are correct and that it's not coming from where I thought it was.
