### ISSUE TITLE
Awaiting copy is not possible.

### ISSUE THREAD

**Issue by fivethreeo** [jprichardson/node-fs-extra#867]
- **Operating System:** Debian 10
- **Node.js version:** Node 14
- **`fs-extra` version:** 9.1.0

If you try to await copy you cannot know that the files are actually copied since callback is called immediately after first file is copied successfully. If you use a callback you can only use it to get the errors not to do more work after copy is done.

So maybe use the glob module and use that to filter and find all the files that will be copied, count them and count down on each file copied. When you reach 0, call the callback. Maybe add a timeout aswell so if 0 is not reached in time, stop the copying and callback a timeout error.

I wanted to run yarn in the copied dir but it kept failing randomly.

**Comment by fivethreeo** [comment]
https://www.npmjs.com/package/recursive-copy

**Comment by RyanZim** [comment]
I'm not seeing how this could be happening, do you have a reduced test case demonstrating this bug?

**Comment by fivethreeo** [comment]
You call cb here https://github.com/jprichardson/node-fs-extra/blob/1625838cdfc65a1bbf28ab5fa962a75805629b9c/lib/copy/copy.js#L91 , so called for each copied file.

**Comment by RyanZim** [comment]
Closing for lack of response.
