### ISSUE TITLE
`ensureLink` does not ensure the destination is hard linked to the source

### ISSUE THREAD

**Issue by pyrocat101** [jprichardson/node-fs-extra#870]
- **Operating System:** macOS 10.15.7
- **Node.js version:** v12.20.1
- **`fs-extra` version:** 5.0.0 (checked source code in `master` and the issue is still there)

`ensureLink` shortcuts if the destination path exists, without verifying if the destination file's inode is the same as the source file. This is misleading because it is not really an "ensurance".

Relevant code: https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/ensure/link.js#L19

**Comment by RyanZim** [comment]
I _think_ this should be fixed by https://github.com/jprichardson/node-fs-extra/pull/826; would appreciate review/testing there.
