### ISSUE TITLE
please use babel transform code to es3

### ISSUE THREAD

**Issue by txiaocao** [jprichardson/node-fs-extra#871]
many project is use node@10.0.0 early。because update the fs-extra, can not run code...

```

  const make = async pth => {
    try {
      await fs.mkdir(pth, options.mode)
    } catch (error) {
      if (error.code === 'EPERM') {
        throw error
      }

      if (error.code === 'ENOENT') {
        if (path.dirname(pth) === pth) {
          throw permissionError(pth)
        }

        if (error.message.includes('null bytes')) {
          throw error
        }

        await make(path.dirname(pth))
        return make(pth)
      }

      try {
        const stats = await fs.stat(pth)
        if (!stats.isDirectory()) {
          // This error is never exposed to the user
          // it is caught below, and the original error is thrown
          throw new Error('The path is not a directory')
        }
      } catch {
        throw error
      }
    }
  }

  return make(path.resolve(input))
}
```
/Users/maoke/home/project/jdd/lark/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/maoke/home/project/jdd/lark/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @jdd/lark@1.4.0 docs: `typedoc --out dist ./

- **Operating System:mac
- **Node.js version:8.9.4
- **`fs-extra` version:latest

**Comment by RyanZim** [comment]
`fs-extra` v9 does not support Node versions earlier than 10; you must use `fs-extra` v8 for these platforms. However, I would advise you to upgrade, since Node versions older than v10 are no longer receiving security updates.
