### ISSUE TITLE
Typescript compile error "Namespace '"fs"' has no exported member 'BaseEncodingOptions'"

### ISSUE THREAD

**Issue by christian-judt** [jprichardson/node-fs-extra#872]
- **Operating System:** Windows 10 (64 bit)
- **Node.js version:** 13.7.0
- **`fs-extra` version:** 9.0.8
- **`typescript` version:** 4.0.5

**Original issue:**:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51521

Since fs-extra version 9.0.8 I get the following three errors when compiling using typescript:
```
../../@types/fs-extra/index.d.ts:232:38 - error TS2694: Namespace '"fs"' has no exported member 'BaseEncodingOptions'.

232         (path: PathLike, options: fs.BaseEncodingOptions | BufferEncoding | undefined | null): Promise<string>;
                                         ~~~~~~~~~~~~~~~~~~~

../../@types/fs-extra/index.d.ts:233:38 - error TS2694: Namespace '"fs"' has no exported member 'BufferEncodingOption'.

233         (path: PathLike, options: fs.BufferEncodingOption): Promise<Buffer>;
                                         ~~~~~~~~~~~~~~~~~~~~

../../@types/fs-extra/index.d.ts:234:38 - error TS2694: Namespace '"fs"' has no exported member 'BaseEncodingOptions'.

234         (path: PathLike, options: fs.BaseEncodingOptions | string | undefined | null): Promise<string | Buffer>;
                                         ~~~~~~~~~~~~~~~~~~~


Found 3 errors.
```
These errors do not appear when using fs-extra version 9.0.7, so pinning the used version of fs-extra to 9.0.7 provided a decent temporary workaround for me.

**Comment by RyanZim** [comment]
This is a problem with `@types/fs-extra` which is not officially maintained by `fs-extra`, it's just a community project. https://github.com/DefinitelyTyped/DefinitelyTyped/issues/51521 is where the issue should be tracked, and any fix would have to be filed with the DefinitelyTyped project.
