### ISSUE TITLE
Syntax Error with Node >= 10

### ISSUE THREAD

**Issue by marcin-b** [jprichardson/node-fs-extra#877]
- Ubuntu 20.04
- Node 10.19.0
- fs-extra 9.1

Hi,
There are some instances of `catch {}` being used in some methods instead of `catch (error) {}`, causing a Syntax error.

Example:
https://github.com/jprichardson/node-fs-extra/blob/7498c9c9ebe5e83e535092aedb9aad3e23f601bf/lib/empty/index.js#L33

**Comment by RyanZim** [comment]
Node 10 itself should support this modern syntax; perhaps there's something else in your toolchain that doesn't; please post the full error, including stack trace.

**Comment by mb-jaduda** [comment]
Sure:
```
nodejs       | /application/node_modules/fork-ts-checker-webpack-plugin/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
nodejs       |       } catch {
nodejs       |               ^
nodejs       | 
nodejs       | SyntaxError: Unexpected token {
nodejs       |     at createScript (vm.js:80:10)
nodejs       |     at Object.runInThisContext (vm.js:139:10)
nodejs       |     at Module._compile (module.js:617:28)
nodejs       |     at Object.Module._extensions..js (module.js:664:10)
nodejs       |     at Module.load (module.js:566:32)
nodejs       |     at tryModuleLoad (module.js:506:12)
nodejs       |     at Function.Module._load (module.js:498:3)
nodejs       |     at Module.require (module.js:597:17)
nodejs       |     at require (internal/module.js:11:18)
nodejs       |     at Object.<anonymous> (/application/node_modules/fork-ts-checker-webpack-plugin/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```
My version of fork-ts-checker-webpack-plugin is "^6.2.0" and it has fs-extra as a dependency `"fs-extra": "^9.0.0"`.
Am I missing something here

**Comment by RyanZim** [comment]
Are you running in docker or something (guessing based on your file paths)?

**Comment by marcin-b** [comment]
Indeed. And that's the issue. The node version inside the container is 8.12.0.
Fixed it by downgrading the fork-ts-checker-webpack-plugin to 4.1.4 which uses a version of fs-extra that support that node version.
Thanks for the help!
