### ISSUE TITLE
outputJSON and writeJSON doesn't work with relative path

### ISSUE THREAD

**Issue by bayraak** [jprichardson/node-fs-extra#879]
- **Operating System:**
  - MacOS Mojave 10.14.6
- **Node.js version:**
  -  14.13.1
- **`fs-extra` version:**
  - 9.1.0

When I'm trying to write a `JSON` file with both of `outputJSON` or `writeJSON` it is silently failing (files are not written as json as a result) if the given path is a relative path.

**Comment by bayraak** [comment]
> What is being written in this case?

A JavaScript object. Simply this: 

```
{
    "hello": "world",
    "an": "example"
}
```

**Comment by RyanZim** [comment]
Ah, misread your post; thought you were saying something other than JSON was being written to the file. Rereading, it seems that you're saying the file isn't being written at all.

If you manually `JSON.stringify` your data and use `writeFile`, does it work?

**Comment by RyanZim** [comment]
Closing for lack of reply
