### ISSUE TITLE
get all files recursive solution

### ISSUE THREAD

**Issue by sitbubu** [jprichardson/node-fs-extra#889]
Something like this solution:
https://coderrocketfuel.com/article/recursively-list-all-the-files-in-a-directory-using-node-js

**Comment by AlonMiz** [comment]
sounds like a good feature to add
would you consider contributing it yourself? :)

**Comment by sitbubu** [comment]
yes :)

**Comment by RyanZim** [comment]
We actually used to have something like this, but it was so complex, it was moved to an external library.

https://github.com/jprichardson/node-klaw
Sync version: https://github.com/manidlou/node-klaw-sync
