### ISSUE TITLE
Unexpected token | make-dir

### ISSUE THREAD

**Issue by abelardolg** [jprichardson/node-fs-extra#892]
- **Operating System:** Ubuntu 
- **Node.js version:** 16
- **`fs-extra` version:** "^9.1.0",

I created a project by using the latest version of NestJS. When I run start:dev 

![image](https://user-images.githubusercontent.com/22522883/116516619-1856c080-a8ce-11eb-8e28-b2c85346e536.png)

it showed this error:
![image](https://user-images.githubusercontent.com/22522883/116516670-29073680-a8ce-11eb-9520-804ef830a5af.png)

Best regards.

**Comment by RyanZim** [comment]
Something in your toolchain is either running an old version of Node, or otherwise doesn't support optional catch bindings. Either way, not a bug with `fs-extra`.
