### ISSUE TITLE
appendFileSync() is missing

### ISSUE THREAD

**Issue by princensit** [jprichardson/node-fs-extra#900]
- **Operating System: Mac OS Big Sur**
- **Node.js version: 14.16.0**
- **`fs-extra` version: 10.0.0**

Although mentioned in README that ```fs-extra``` is replacement for native ```fs```, but I didn't find appendFileSync() method with this. I tried below,
```
const fse = require('fs-extra')
fse.appendFileSync(file, content); // this is not working
```

Can you please check and reply? Thanks

**Comment by RyanZim** [comment]
It should work; what do you mean by "not working"? Is it giving an error? (If so, please post it) Silently failing? Does your code work if you replace `require('fs-extra')` with `require('fs')`?

**Comment by princensit** [comment]
Sorry, IntelliJ IDE is complaining that fse.appendFileSync() it is not able to resolve. On running it is working fine. Thanks
