### ISSUE TITLE
Question: Mocking fs-extra (and graceful-fs)

### ISSUE THREAD

**Issue by thernstig** [jprichardson/node-fs-extra#905]
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz
  Binaries:
    Node: 14.16.0 - ~/.local/share/nvm/v14.16.0/bin/node
    npm: 6.14.11 - ~/.local/share/nvm/v14.16.0/bin/npm
  fs-extra: 8.1.0
```

`fs-extra` contains this code:

```js
const fs = require('graceful-fs')
...
...
...
if (typeof fs.realpath.native === 'function') {
  exports.realpath.native = u(fs.realpath.native)
}
```

I am using Jest to to mock the `fs` module, which worked fine before I recently upgrade to use ECMAScript modules. But I transpile the code with babel to change `import` statements into `require` with the babel config (which is recommended till Jest supports full ESM):

```json
{
  "plugins": [
    "@babel/plugin-transform-modules-commonjs"
  ]
}
```

I mock the `fs` module like:

```js
const fs = jest.createMockFromModule('fs');

fs.existsSync = jest.fn(() => true);

export default fs;
```

When running a test case I get:

```sh
TypeError: Cannot read property 'native' of undefined

      at Object.<anonymous> (node_modules/fs-extra/lib/fs/index.js:108:24)
      at Object.<anonymous> (node_modules/fs-extra/lib/index.js:6:3)
```

If I do a `console.log` of the `fs` object inside `server/node_modules/fs-extra/lib/fs/index.js` I can see it is an object like (note that I run this code without babel transpilation:

```js
{
  ...
  realpath: [Function: realpath] { native: [Function (anonymous)] }
  ...
}
```

But if I log it while running with Jest where it is transpiled with babel, I get:

```js
{
  default: {
    ...
    realpath: [Function: realpath] {
      _isMockFunction: true,
      ...
    }
    ...
  }
}
```

The problem here is then that `fs` contains a `default` property in the object, the module `fs-extra` fails since it cannot find `fs.realpath`.

I have no idea on how to solve this. I realize this is NOT a problem in this repo, but I posted it here to possibly find and answer and possibly avoid future similar questions for other users. I am fine with closing this if you feel it is out of scope or you cannot help since you are not aware of the inner workings of babel.

note: I am aware the latest version does not contain this, but the lib I am using will take a long time to update their dependencies

**Comment by RyanZim** [comment]
Yeah, babel's handling here sometimes leaves a bit to be desired. It works fine if you're only `import`ing ECMAScript modules in other ESM files, but that's not the case here, since you're constructing an ESM mock for `fs-extra`, which is still commonjs. AFAIK, the only way around this is to change your mock to do `module.exports = fs`, instead of `export default fs`. I think you can still use `import` in your mock, but you'll have to export commonjs style, so that babel doesn't break it.

**Comment by thernstig** [comment]
@RyanZim that solved it! I just had to add:

```js
// eslint-disable-next-line no-undef
module.exports = fs;
```

I have no idea why really, and I am still hoping for an answer over at the babel repo why this even happens, see https://github.com/babel/babel/discussions/13358

Note: I am not constructing a mock for `fs-extra`, just for `fs`.

**Comment by RyanZim** [comment]
Right, and when babel transpiles ESM to CJS, you have to do `require('some-module').default` to use it in CJS. Glad that worked!

**Comment by thernstig** [comment]
For reference for future readers, I am also discussing this with babel here to see if there is a better solution: https://github.com/babel/babel/discussions/13358
