### ISSUE TITLE
Some methods do not have a mode option

### ISSUE THREAD

**Issue by dittyroma** [jprichardson/node-fs-extra#907]
- **Operating System:** Any
- **Node.js version:** Any
- **`fs-extra` version:** Any

Some methods offer no way to specify mode so they always create files or directories world writable. If a user wants to ensure secure files and directories they have to avoid these methods. Accepting a mode would make it possible to use them securely.

World writable resources such as config files can allow other users to control program behavior. In some cases there's code injection through the config file, which can lead to privilege elevation. World writable directories have the same weakness since they allow adding files within them. A world writable config directory `/etc/froznator/conf.d` offers a route to controlling program behavior through a new config file. On Linux the umask should usually prevent this but it's not guaranteed. [Secure coding standards](https://wiki.sei.cmu.edu/confluence/display/c/FIO06-C.+Create+files+with+appropriate+access+permissions) recommend always specifying a restricted mode so files and directories are secure in any environment. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

These methods create world writable files:

- ensureFile
- ensureFileSync

These methods create world writable directories:

- emptyDir
- emptyDirSync
- ensureFile
- ensureFileSync
- ensureLink
- ensureLinkSync
- ensureSymlink
- ensureSymlinkSync
- outputJSON
- outputJSONSync

This came out of research with CodeQL.

**Comment by RyanZim** [comment]
This is all true theoretically. But is anyone actually using these `fs-extra` methods to write config files or do something else where you want a non-standard mode? I'm not interested in adding hypothetically useful features; that leads to bloat. If somebody actually needs this, we can consider it.

 `outputJSON*` methods already support passing a mode; and you cannot set a mode on link or symlink creation; so that leaves these methods:

- emptyDir
- emptyDirSync
- ensureFile
- ensureFileSync

**Comment by dittyroma** [comment]
Thanks for reviewing.

The other functions implicitly create directories with no way to specify mode.

Permissions seems like a core function to me, but I'm closing since you're not interested.

**Comment by RyanZim** [comment]
> The other functions implicitly create directories with no way to specify mode.

If you need specific modes, you shouldn't be using implicit directory creation. You'd expect a `mode` option to apply to the path being created; it's not at all obvious that it'd also be applied to the directories implicitly created. Matter of fact, `mkdir -p -m <mode>` only applies `<mode>` to the final directory, and creates the implicit parents with the default umask settings, so there's a strong Unix precedent to not worry about implicit parents.

**Comment by dittyroma** [comment]
> Matter of fact, `mkdir -p -m <mode>` only applies `<mode>` to the final directory, and creates the implicit parents with the default umask settings, so there's a strong Unix precedent to not worry about implicit parents.

Indeed it does! Didn't know about that.

**Comment by dittyroma** [comment]
Just published [`secure-fs-extra`](https://www.npmjs.com/package/secure-fs-extra), in case anyone lands here looking for a way to secure things. It offers mode arguments everywhere and uses secure modes by default.

```js
import fs from 'secure-fs-extra'

// Full path created securely
await fs.ensureDir('/var/froznator/queue')

// File and full path created securely
await fs.outputFile('/etc/froznator/conf.d/main.conf', 'AdminPassword=123')

// File and full path created with carefully loosened permissions
await fs.outputJSON('/srv/froznator/feed.json', feed, {
  mode: 0o640, // owner RW, group R
  dirMode: 0o750 // owner RWX, group RX
})

// Read sensitive data with confidence
const config = await readConfig('/etc/froznator/conf.d/main.conf')
if (password === config.AdminPassword) showAdminInterface()
```
