### ISSUE TITLE
copyFiles does not support the new file name of "."

### ISSUE THREAD

**Issue by zhanxiaoge** [jprichardson/node-fs-extra#908]
fs.copySync('c:\\1.txt', 'c:\\.1.txt');

Use the official "fs.copyFileSync" normal.

**Comment by RyanZim** [comment]
What happens when you run `fs.copySync('c:\1.txt', 'c:\.1.txt');`?

**Comment by zhanxiaoge** [comment]
Sorry, the logic of my code is wrong, copySync is working fine.
