### ISSUE TITLE
fs.copySync('/test', '/haha') is different with 'cp -r /test /haha'

### ISSUE THREAD

**Issue by weekeight** [jprichardson/node-fs-extra#91]
As the title described, we all know the command `cp -r /test /haha` is different with `cp -r /test/ /haha`,  the first copy *test* directory itself into *haha* directory when the second command copy the content of  *test* directory inoto *haha*.
why `fs.copySync('/test', '/haha')` is different with `cp -r /test /haha` ? Are you on purpose?

**Comment by jprichardson** [comment]
This will happen eventually, but it's not a priority at the moment. The priorities for this module at the moment are to squash all bugs and make sure that it works really well on all platforms with explicit conventions. i.e. `fs.copy('/dir1', '/dir2/')` would have the same behavior as `fs.copy('/dir1/', '/dir2')`. In the future, I will add wildcards to copy content. Closing for now.
