### ISSUE TITLE
emptyDir throwing an error because folder is not empty

### ISSUE THREAD

**Issue by robin-garnham** [jprichardson/node-fs-extra#910]
- **Operating System:**
Windows Server 2016 (1607)

- **Node.js version:**
v16.3.0

- **`fs-extra` version:**
10.0.0

Command:
`await fsExtra.emptyDir(workspacePath);`

Errors:

    Error: ENOTEMPTY: directory not empty, rmdir 'D:\Users\robin\Desktop\render-service-master\src\workspace\DUOnOAHW6J4KSRTBE8qcg'

**Comment by RyanZim** [comment]
What is the value of `workspacePath`?

Windows is famous for throwing completely incorrect error codes; it's a pain do decipher what's actually wrong.

**Comment by robin-garnham** [comment]
`D:\Users\robin\Desktop\cloud-render-service-master\src\workspace\`

Error: ENOTEMPTY: directory not empty, rmdir 'D:\Users\robin\Desktop\cloud-render-service-master\src\workspace\DUOnOAHW6J4KSRTBE8qcg'

**Comment by RyanZim** [comment]
Is `D:\Users\robin\Desktop\cloud-render-service-master\src\workspace\DUOnOAHW6J4KSRTBE8qcg` a file or a directory? Is there any program that might be using the file when you're running this? What happens if you try to delete it with `fs.rm()`?

**Comment by RyanZim** [comment]
Closing for lack of response.
