### ISSUE TITLE
EnsureDir throws err.

### ISSUE THREAD

**Issue by ashish-tru** [jprichardson/node-fs-extra#914]
- **Operating System: MacOS (10.15.5)**
- **Node.js version: (14.3)**
- **`fs-extra` version: (9,0,1)**

EnsureDIr throws error if there is a file present with the same name of the directory that you want to ensure is present.

**Comment by RyanZim** [comment]
Yes, this is expected behavior. We don't want to just silently delete the file. If you want this behavior, simply call `remove` on the path before using `ensureDir`.
