### ISSUE TITLE
Universalify 2.0.0 breaks `fs.realpath`

### ISSUE THREAD

**Issue by behos** [jprichardson/node-fs-extra#915]
- **Operating System:**
- **Node.js version:**
- 16.0.0
- **`fs-extra` version:**
- 9.1.0

Hi,

`fs-extra` uses `universalify` version `2.0.0` for creating `Promises` for callback methods including the built-in `fs.*` ones. In https://github.com/RyanZim/universalify/pull/13, the signature of the wrapper changed such that any non-null value for `err` would be considered a failure. Unfortunately, `fs.realpath` uses `false` as the error value when the call is successful, and this propagates as an exception in the promise.

I have raised this issue here: https://github.com/RyanZim/universalify/issues/16 but while it's being fixed, should the `universalify` dependency be rolled back?

**Comment by RyanZim** [comment]
I am unable to reproduce `fs.realpath` passing `false` as the error value on Node.js 16.0.0; what's your OS?

**Comment by behos** [comment]
You are right, I was running node through `bazel` which had its own version of node configured which really old. It returns null now so this issue does not apply :)
