### ISSUE TITLE
Problem to set permission with ensureDirSync(dest,options) 

### ISSUE THREAD

**Issue by jaiminpatel008** [jprichardson/node-fs-extra#917]
- **Operating System:** Ubuntu 20.04
- **Node.js version:** 14.17.0
- **`fs-extra` version:**^10.0.0

const options = {
mode : 0o7777
}
let isDirectory = fs.ensureDirSync(dest, options);

const desiredMode = 0o7777;
let isDirectory = fs.ensureDirSync(dest, desiredMode);

Above both options is not working.

**Comment by RyanZim** [comment]
You have an extra `7` there; I presume you meant `0o777`?
