### ISSUE TITLE
Port copy fix from Node.js core

### ISSUE THREAD

**Issue by RyanZim** [jprichardson/node-fs-extra#918]
Just opening an issue for https://github.com/nodejs/node/pull/39372#discussion_r670744165 so this doesn't get forgotten.

**Comment by RyanZim** [comment]
@manidlou FYI, will be working on pushing a new major release in the coming days with ESM support (refs https://github.com/jprichardson/node-fs-extra/issues/746#issuecomment-923250293); any chance you could tackle this soon?

**Comment by rxliuli** [comment]
It seems not difficult to support esm/cjs at the same time through the build tool, why not do this?

**Comment by RyanZim** [comment]
@rxliuli We are planning to support both CJS and ESM; due to some special considerations, we can't just use an out of the box solution. See the issue for more details.

**Comment by RyanZim** [comment]
There's a real bug here, but I'm not sure if @bcoe fixed it correctly; see https://github.com/nodejs/node/pull/39372#discussion_r1001179295
