### ISSUE TITLE
statSync not support throwIfNoEntry = false

### ISSUE THREAD

**Issue by bluelovers** [jprichardson/node-fs-extra#919]
- **Operating System:**
- **Node.js version:**
- **`fs-extra` version:**

**Comment by RyanZim** [comment]
Will this be fixed by https://github.com/isaacs/node-graceful-fs/pull/220?

**Comment by rrthomas** [comment]
I believe the change to node-graceful-fs will fix fs-extra, as when I come across this problem the error actually occurs inside graceful-fs.

**Comment by RyanZim** [comment]
https://github.com/isaacs/node-graceful-fs/pull/220 is merged; this should be fixed.
