### ISSUE TITLE
Is there a way to get the file currently being copied with fs.copy()?

### ISSUE THREAD

**Issue by cfpwastaken** [jprichardson/node-fs-extra#920]
- **Operating System:** Windows 10
- **Node.js version:** 16.6.1
- **`fs-extra` version:** ^10.0.0

It would be cool to be able to show the user what file you are currently copying but i can't seem to find any way to do this.

Btw. it would be amazing if i could get the percentage and ETA too.

**Comment by RyanZim** [comment]
`fs-extra` provides general-purpose copying; this kind of granular status reporting is out of scope; and would be better served by creating a dedicated module for it.
