### ISSUE TITLE
Renaming case-only on smb-mounted fs doesn't work

### ISSUE THREAD

**Issue by wmertens** [jprichardson/node-fs-extra#921]
- **Operating System:** Linux 5.4.114
- **Node.js version:** 14.17
- **`fs-extra` version:** 10.0.0

When case-only renaming a file that is on an SMB mount there's a good chance that the src and dst stats will return different inode numbers even though they are the same file.

This causes the pre-move check to fail to notice it's a case-only change.

I realize this is an edge case, and that there's no way to check if a rename would overwrite a file short of creating a file to see if the fs is case-sensitive in that directory. Maybe there's no solution and this is just behavior to document.

**Comment by RyanZim** [comment]
I'd agree this is just documentation; no reason to handle this edge case. I'm personally inclined to say leaving this issue for posterity is sufficient documentation given the super edge-case nature of this, so closing. Feel free to open a docs PR if you disagree.
