### ISSUE TITLE
When copying a directory, filter should fire on each of the contents of it, not on the directory itself.

### ISSUE THREAD

**Issue by mig82** [jprichardson/node-fs-extra#927]
- Mac OS 10.14.6 (Mojave)
- node -v
v14.15.5
- "fs-extra": "10.0.0"

I'm trying to copy the contents of a folder whose structure is this:

```
Foo
├── Endpoints
│   └── default.xml
├── Meta.json
└── Operations
    ├── create.xml
    └── getAccounts.xml
```
I want both the `Endpoints` and `Operations` directories (and any other that might be there in the future) copied over to the target location. I want to filter out `Meta.json` though. Like so.

```
targetLocation
├── Endpoints
│   └── default.xml
└── Operations
    ├── create.xml
    └── getAccounts.xml
```

Now, if I use 

```
fs.copy('path/to/Foo', targetLocation, {
    filter: (src, dest) => { src !== 'Meta.json' }
})
```
What happens is that the filter **only fires for the directory itself**. **_Not_** for each of the entries in it. So the filtering doesn't work as expected.

P.S: Note that if instead I try to use `fs.readdir` to get the entries in the directory, filter `Meta.json` and then `copy` on each entry in the `Foo` directory, I end up with:
```
targetLocation
├── create.xml
├── default.xml
└── getAccounts.xml
```
Which does not preserve the folder structure. So this is not a suitable workaround.

**Comment by nikhilnayyar002** [comment]
Tried on windows.

I have file structure: 

```
public/
   favicon.ico
   index.html

build/
```

When calling

```js
// temp.js

const fs = require('fs-extra')

fs.emptyDirSync("build")
fs.copySync("public", "build", { dereference: true, filter: (src, dest) => { console.log(src); return false } })
```

it prints in console:

```
D:\work\react-min-src>node temp.js
public
```

As you can see it only prints the directory. Not path for each file.

I am using:
- node v14.18.1, npm v6.14.15
- Windows 10 Home
- fs-extra v10.0.0

**Comment by nikhilnayyar002** [comment]
Tried on windows.

I have file structure: 

```
public/
   favicon.ico
   index.html

build/
```

When calling

```js
// temp.js

const fs = require('fs-extra')

fs.emptyDirSync("build")
fs.copySync("public", "build", { dereference: true, filter: (src, dest) => { console.log(src); return false } })
```

it prints in console:

```
> node temp.js
public
```

As you can see it only prints the directory. Not path for each file.

I am using:
- node v14.18.1, npm v6.14.15
- Windows 10 Home
- fs-extra v10.0.0

**Comment by nikhilnayyar002** [comment]
Got that its working!
