### ISSUE TITLE
[Suggestion] Support JSONL

### ISSUE THREAD

**Issue by ZephD** [jprichardson/node-fs-extra#929]
I was wondering if it's been considered for fs-extra to support JSON Lines file formats (.jsonl) as a built in feature.

e.g. files that look like:
```
{ "test": 1 }
{ "test": 2 }
{ "test": 3 }
```
Which is valid JSON per line.

**Comment by RyanZim** [comment]
Out of scope, as per https://github.com/jprichardson/node-jsonfile/issues/121.
