### ISSUE TITLE
fs-extra path arguments should use `fs.PathLike`

### ISSUE THREAD

**Issue by pjalsGit** [jprichardson/node-fs-extra#930]
- **Operating System: `Linux fedora 5.14.16-302.fsync.fc35.x86_64 #1 SMP Sat Nov 6 19:37:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`**
- **Node.js version: `v16.11.0`**
- **`fs-extra` version: `fs-extra@npm:10.0.0`**

**Comment by RyanZim** [comment]
The reason we don't is that we use Node `path` internally, which only supports strings.
