### ISSUE TITLE
Some options for emptyDir() (and not only)

### ISSUE THREAD

**Issue by 1aerostorm** [jprichardson/node-fs-extra#935]
At current moment, `emptyDir()` removes all files. We cannot filter out some file names or extensions. We cannot even filter out hidden files. E.g. it will remove `.gitkeep` file, and it makes this function useless for me.

We even cannot adjust the recursion depth...

**Comment by RyanZim** [comment]
For more complex use-case, you would be better off deleting the files in the directory individually.

**Comment by 1aerostorm** [comment]
@RyanZim so that library is too limited and useless.
