### ISSUE TITLE
Error: EEXIST, file already exists '../mkdirp/bin/cmd.js' on fs.copySync()

### ISSUE THREAD

**Issue by falmp** [jprichardson/node-fs-extra#94]
When copying files with fs.copySync(), I'm getting this error:

```
fs.js:741
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: EEXIST, file already exists '../mkdirp/bin/cmd.js'
    at Object.fs.symlinkSync (fs.js:741:18)
    at copySync (/private/tmp/test/node_modules/fs-extra/lib/copy.js:83:8)
    at /private/tmp/test/node_modules/fs-extra/lib/copy.js:79:7
```

Here's a little script to reproduce:

**package.json:** 
```javascript
{
    "name": "test",
    "dependencies": {
        "glob": "4.2.1",
        "fs-extra": "0.12.0"
    }
}
```

**test.js:**
```javascript
var glob = require('glob'),
    fs = require('fs-extra');

glob('node_modules/**/*', function(err, files) {
    files.forEach(function(file) {
        var dest = 'copy/' + file;
        console.log('copying ' + file + ' to ' + dest);
        fs.copySync(file, dest);
    });
});
```

I'm using node v0.10.33 on Mac OS X 10.10.1.

**Comment by Globegitter** [comment]
@jprichardson Hmmm, for me `fs.copySync(sourcePath, destPath)` just seems to overwrite the file now. I actually want it to throw an error so I can ask the user to overwrite/diff, etc.

**Comment by Globegitter** [comment]
Hmm, even if I use `fs.copy()` I don't manage to get an error at all, no matter what I set clobber to. And if I do 
```
console.log('destPath exists', fs.existsSync(destPath));
console.log('sourcePath exists', fs.existsSync(sourcePath));
```

I get true for both. So how can I get this to throw an error, intervene, etc when a file already exists?

**Comment by falmp** [comment]
Still getting an error here with latest versions:

The error is a little bit different though:

```
evalmachine.<anonymous>:741
  return binding.symlink(preprocessSymlinkDestination(destination, type),
                 ^
Error: EEXIST, file already exists '../rimraf/bin.js'
    at Object.fs.symlinkSync (evalmachine.<anonymous>:741:18)
    at copySync (/private/tmp/test/node_modules/fs-extra/lib/copy.js:91:8)
    at /private/tmp/test/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
    at copySync (/private/tmp/test/node_modules/fs-extra/lib/copy.js:85:14)
    at /private/tmp/test/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
    at copySync (/private/tmp/test/node_modules/fs-extra/lib/copy.js:85:14)
    at /private/tmp/test/node_modules/fs-extra/lib/copy.js:86:7
    at Array.forEach (native)
```

Here are the versions used:

**package.json:**
```js
{
  "name": "test",
  "dependencies": {
    "fs-extra": "^0.16.3",
    "glob": "^4.4.0"
  }
}
```

**Comment by jprichardson** [comment]
By default, do you think the sensible approach is to throw an error if the destination exists? But a flag like `clobber` should exist to allow the user to force it if need be?

**Comment by Globegitter** [comment]
Yep, I think that would be the most sensible approach - that would be a breaking change though right?

**Comment by jprichardson** [comment]
Working on this... added `clobber` to `copySync()` for files. Will slowly make my way through all of it :) https://github.com/jprichardson/node-fs-extra/commit/0bed228be27249b04caa5f07e05f85f669d2b842 and https://github.com/jprichardson/node-fs-extra/commit/a592001b63a6c5ee9b7a928ad312b077c2e76b00

**Comment by RyanZim** [comment]
@jprichardson What needs done here yet?

**Comment by jprichardson** [comment]
I believe two things:

1. `copySync()` should throw an error if dest exists.
2. `copySync()` should have `clobber`.

And now looking at my most previous commits tagged here... IDK. Weird.

@falmp or @Globegitter do you know what's still missing?

**Comment by RyanZim** [comment]
@jprichardson Both these issues have been fixed.

See https://github.com/jprichardson/node-fs-extra/pull/296

Closing, please reopen if I missed something.
