### ISSUE TITLE
Regression in 10.0.1: `copySync` is nolonger accessible in ESM mode

### ISSUE THREAD

**Issue by akphi** [jprichardson/node-fs-extra#943]
I think the change in https://github.com/jprichardson/node-fs-extra/pull/922 broke the importing of `copySync` in ESM mode a bit. The error is below

```
import { mkdirs, copySync } from 'fs-extra';
                 ^^^^^^^^
SyntaxError: Named export 'copySync' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fs-extra';
const { mkdirs, copySync } = pkg;
```

This did not happen in `10.0.0`.

- **Operating System: macOS 11.6.4**
- **Node.js version: 16.8.0**
- **`fs-extra` version: 10.0.1**

**Comment by akphi** [comment]
Reading https://github.com/jprichardson/node-fs-extra/issues/746 and it seems like I was lucky to be able to use `fs-extra` in this `ESM-like` fashion so far... Let me know what you think, I'm happy to close this if you confirm this is totally by accident and we should avoid using this `ESM-like` approach till #746 is resolved. Thanks!

**Comment by RyanZim** [comment]
Yeah, we've never supported ESM; I surprised that ever worked.
