### ISSUE TITLE
Error: Cannot copy 'Source Directory' to a subdirectory of itself, 'Destination directory' when run with nexe.

### ISSUE THREAD

**Issue by hnviradiya** [jprichardson/node-fs-extra#944]
if we use "[fs-extra](https://www.npmjs.com/package/fs-extra)"'s [copySync method](https://github.com/jprichardson/node-fs-extra/blob/HEAD/docs/copy-sync.md). It gives source and destincation stat same in fs-extra.

`Error: Cannot copy 'Source Directory' to a subdirectory of itself, 'Destination directory'`

Following is the line where "areIdentical" is getting to true when run inside nexe. But gives different without nexe.

https://github.com/jprichardson/node-fs-extra/blob/69eb8964626871000de3a95548cd36035b5c4b27/lib/util/stat.js#L120

This issue only occurs when built with nexe. if we run without nexe it works fine.

OS: windows 11
NodeJs Version: v16.14.0
fs-extra: 10.0.0

I have also [logged issue on nexe](https://github.com/nexe/nexe/issues/963) and found that they are faking the device id. so stats are getting same. 

But as I have also passed `{ overwrite: true }`, it should still replace the file right to destination?

**Comment by RyanZim** [comment]
No, `overwrite` won't help here. You fundamentally can't copy to a subdirectory without an infinite loop. Of course, it's not actually a subdirectory; it's just nexe's bad data here. Unfortunately, I don't know of anything to do other than waiting for nexe to fix the issue.
