### ISSUE TITLE
Image copy is broken

### ISSUE THREAD

**Issue by vladtopchu** [jprichardson/node-fs-extra#946]
Tried to copy directory with all it's files (code + various types of images (png, jpg, jpeg, webp)), but when I'm trying to open an image - it appears to be broken.

I used this function: fse.copySync(from, destination)

Code files copying just fine, without any loses

- Windows 10
- Node.js v17.4.0
- fs-extra 10.0.1

**Comment by RyanZim** [comment]
> it appears to be broken.

How is it broken?

**Comment by vladtopchu** [comment]
> How is it broken?
It's not opening in any way. Few examples:
1) Windows Image Viewer and Photoshop showing "unsupported type" error even tho file extension are the same
2) Browser showing a tiny little white square
