### ISSUE TITLE
Allow passing undefined options to move()

### ISSUE THREAD

**Issue by Nokel81** [jprichardson/node-fs-extra#947]
- **Operating System:**macos
- **Node.js version:**14.18.3
- **`fs-extra` version:**10.0.1

The follow code:

```
const { move } = require("fs-extra");

move("/some/path/that/exists", "some/path/that/doesnt/exist", undefined)
  .then(() => console.log("success")
  .catch(console.error);
```

produces the following type error: `TypeError: Cannot read property 'overwrite' of undefined`

The error seems to be from the handling of `optional callback` and `optional options` on line 12-15 of `lib/move/move.js`

**Comment by RyanZim** [comment]
Right, both callback and options are optional; you're passing `undefined`, which it doesn't know how to deal with. If you don't want to specify options or a callback, omit the argument altogether.

**Comment by Nokel81** [comment]
Yes but in JS passing undefined as a parameter should mean the same as not passing it. And if I am making a wrapper around your method then I shouldn't have to check if the optional field is not passed in.

For instance with default params, passing undefined means "use default".

**Comment by RyanZim** [comment]
Ah, true; this does make wrappers inconvenient. PR welcome to fix.
