### ISSUE TITLE
TypeError: Cannot read property 'withFileTypes' on null

### ISSUE THREAD

**Issue by AwesomeSam9523** [jprichardson/node-fs-extra#951]
- **Operating System:** Windows 11
- **Node.js version:** v16.13.1
- **`fs-extra` version:** 10.0.1

![image](https://user-images.githubusercontent.com/76945339/160292057-cf8c4d06-0452-4150-9a79-616fac71f75c.png)
Code:
```js
await new Promise(resolve => {
    fse.copy('path/to/a', 'path/to/b', { overwrite: true, recursive: true }, err => {
        if (err)
            throw err;
        resolve();
    });
});
```
or
```js
await fse.copy('path/to/a', 'path/to/b', { overwrite: true, recursive: true })
```
or
```js
fse.copy('path/to/a', 'path/to/b', { overwrite: true, recursive: true }).then()
```

Basically async copy dir fails.

**Comment by AwesomeSam9523** [comment]
@RyanZim `v9.4.4`

**Comment by RyanZim** [comment]
I'm not sure what's causing this. Electron v9 is out of date and unsupported, so that may be a factor.

**Comment by jstlroot** [comment]
Same problem using Electron 13. Not compatible with asar.

**Comment by RyanZim** [comment]
@jstlroot This is something we'd like to fix; what function are you encountering this with?

**Comment by RyanZim** [comment]
Closing since information is not forthcoming. If you're experiencing this problem, please open a new issue with a MCVE.
