### ISSUE TITLE
File is not getting copy when @import statement is there in css file

### ISSUE THREAD

**Issue by AvinashDalvi89** [jprichardson/node-fs-extra#956]
- **Operating System:** Mac OS Monterey
- **Node.js version:**  v14.19.1
- **`fs-extra` version:** 9.0.1

Trying this command `fs.copySync('sourcefile.css', '/dummy/sourcefile.css');` where 

source file is having @import statement as content like 
sourcefile.css
```
@import 'framework-classic-all_01.css';@import 'framework-classic-all_02.css';

```

If I remove @Import statement it work well. Only creating problem for @import statement.

**Comment by RyanZim** [comment]
The contents of the file should have no bearing on this. What kind of problem are you having?

**Comment by aviboy2006** [comment]
This files are not getting copy using copySync.

**Comment by RyanZim** [comment]
Is there an error? Is it failing silently?

**Comment by aviboy2006** [comment]
Yeah there is not error only that file is not copied due to that further copy command is getting stuck.

**Comment by RyanZim** [comment]
> copy command is getting stuck

What do you mean by "stuck"? Is the copy command hanging?

**Comment by RyanZim** [comment]
Also, what happens if you use [`fs.copyFile`](https://nodejs.org/api/fs.html#fscopyfilesrc-dest-mode-callback)?

**Comment by RyanZim** [comment]
Closing for lack of response.
