### ISSUE TITLE
copy errors with EEXIST

### ISSUE THREAD

**Issue by joelanman** [jprichardson/node-fs-extra#957]
- **Operating System:** Mac OS 11.6.5

- **Node.js version:** v16.13.0

- **`fs-extra` version:** 10.0.1

Apologies if I've got any usage or expectations wrong here, first time using the library.

I'm using this code:

```
    fs.copy('app/assets', 'public', { filter: filterFunc }, err => {
        if (err) return console.error(err)
    })
```
While this asynchronous code runs, I'm also running another function that makes and puts things in the `public` folder.

I get this error:
```
[Error: EEXIST: file already exists, mkdir 'public'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: 'public'
}
```
and none of the copy happens.

If I mkdir `public` before running copy, everything is fine, but I wouldn't think I'd need to do that

**Comment by RyanZim** [comment]
The confusion here is the way the destination path works. You're copying a directory, `app/assets`, and you specified the destination as `public`. fs-extra assumes you want to put the _contents_ of `app/assets` in `public`. I'm guessing you actually want to copy `assets` to `public`, so you end up with `public/assets`. For that, you need to do `fs.copy('app/assets', 'public/assets', ..)`

**Comment by joelanman** [comment]
no, I want to put the contents of app/assets in public

**Comment by RyanZim** [comment]
In that case, you either have to ensure this copy is running first, before other things output to public, or else you have to do `fs.readdir` on `src/assets`, and copy each item to `public`.

**Comment by joelanman** [comment]
that's a bit confusing given the documentation says it will overwrite by default, but it isn't, its throwing an EEXIST error

**Comment by RyanZim** [comment]
OK, I must admit I don't fully understand why that particular error is being thrown. However, my point about usage still stands. If it did overwrite, it would overwrite the other things you're putting in public at the same time.

**Comment by joelanman** [comment]
In my case it wouldn't as I'm putting different things there. This function is copying assets like images, the other is rendering sass to css, both into the `public` folder

**Comment by RyanZim** [comment]
`fs-extra` as you're using it is not copying items into the public folder, it is copying the `assets` folder to `public`, attempting to overwrite any existing `public` folder.
