### ISSUE TITLE
@types_fs-extra@9.0.13@@types/fs-extra/index"' has no default export

### ISSUE THREAD

**Issue by Abbyzhoum** [jprichardson/node-fs-extra#959]
![1655281309770](https://user-images.githubusercontent.com/38661489/173779362-e59c27b1-bd6b-4c98-9e38-a540808396a3.png)
![1655281349497](https://user-images.githubusercontent.com/38661489/173779479-5b047a36-50a4-4416-841f-cd9cda2cc1a0.png)

```The fs-extra module is used in the typescript project, resulting in a startup error```

fs-extra version： 
    "fs-extra": "^10.1.0",
    "@types/fs-extra": "^9.0.13",

**Comment by RyanZim** [comment]
This is an issue with `@types/fs-extra`, not `fs-extra` itself; please file an issue/PR there.

**Comment by Abbyzhoum** [comment]
OK！
