### ISSUE TITLE
emptyDir returns undefined

### ISSUE THREAD

**Issue by ayala6521** [jprichardson/node-fs-extra#960]
- **Operating System:** Windows 10
- **Node.js version:** Node v16.15.1
- **`fs-extra` version:** 2.1.2
emptyDir returns undefined instead of returning a promise:
![image](https://user-images.githubusercontent.com/73247597/174053596-e0306123-aaf7-4435-b28b-8d656325ec0d.png)

## How to Recreate:

```js
import fse from 'fs-extra';

fse.emptyDir('path/to/dir').then(() => console.log('hello'));
```

**Comment by RyanZim** [comment]
You are using a super old version of `fs-extra`, that predates promise support. Current version is 10.1.0.
