### ISSUE TITLE
Module not found issue 

### ISSUE THREAD

**Issue by shashika18923** [jprichardson/node-fs-extra#987]
Hi when i useing the plugin it's showing this error Module not found: Error: Can't resolve 'fs'

**Comment by RyanZim** [comment]
What environment are you working in? You're clearly not using standard Node.js

**Comment by FreePhoenix888** [comment]
@shashika18923 Can you give more context on your problem?

**Comment by RyanZim** [comment]
Closing for lack of response.

**Comment by shashika18923** [comment]
im using react

**Comment by RyanZim** [comment]
Are you building an electron app? Are you trying to use `fs-extra` in a browser?

**Comment by shashika18923** [comment]
nope im creating a react applicatin

**Comment by RyanZim** [comment]
React is a UI library; what runtime/environment are you using? Is this a web app, an electron app, a react-native mobile app, or something else?

**Comment by shashika18923** [comment]
web app

**Comment by RyanZim** [comment]
`fs-extra` is intended for use in Node or Electron. Web apps do not have access to the filesystem, so `fs-extra` does not work there.
