### ISSUE TITLE
filter property in options object is not called for every copied file when recursive option is true

### ISSUE THREAD

**Issue by FreePhoenix888** [jprichardson/node-fs-extra#988]
- **Operating System: Linux. Ubuntu 22.04**
- **Node.js version: 14.15.0**
- **`fs-extra` version: 11.1.0**

# Expected
`copySync` with `recursive: true` in options object calls `filter` with every file which is being copied

# Actual
`copySync` with `recursive: true` in options object calls `filter` with only src and dest directory paths

**Comment by RyanZim** [comment]
Huh, I wonder when this broke. We should definitely have a unit test for this; if you've got a chance, a PR with a failing unit test would be greatly appreciated. Otherwise, I'll try to get to this soon.

**Comment by FreePhoenix888** [comment]
@RyanZim , https://github.com/jprichardson/node-fs-extra/pull/989

**Comment by RyanZim** [comment]
Closing as per https://github.com/jprichardson/node-fs-extra/pull/989#issuecomment-1365399194.
