### ISSUE TITLE
Counldn't find 'fs' module in both graceful-fs and jsonfile

### ISSUE THREAD

**Issue by Mimiokish** [jprichardson/node-fs-extra#993]
Version - Operating System: Windows 11
Version - Node.js: 14.19.1
Version - fs-extra: 11.1.1
Version - @types/fs-extra: 11.0.1
Version - Webpack: 5.75.0 
Version - Webpack-cli: 5.0.1
Version - Typescript: 4.9.5
Version - eslint: 8.33.0

This package seems not working with webpack 5. Here is the error I got: 
![Screenshot_20230201100313](https://user-images.githubusercontent.com/63572172/215927116-deeeb001-ad41-482a-8a99-bd89d99e8e61.png)

This is a brand new project. Here is what I put down in my index.ts file:
`import fs from 'fs-extra'`
`console.log(333, fs)`

And, that is all the code I have for the project.

Webpack 5 removed support for node code modules. So I was trying to use fs-extra to get around it.

**Comment by RyanZim** [comment]
Why are you using webpack? Are you compiling for Electron, a browser, or what?

**Comment by Mimiokish** [comment]
> 

It's for my web project.

**Comment by RyanZim** [comment]
`fs-extra` is for Node; it doesn't work on the web.
