### ISSUE TITLE
Feature request: dedupe option for fs.move

### ISSUE THREAD

**Issue by davidmerfield** [jprichardson/node-fs-extra#996]
Any interest in an additional option for `fs.move` which appends a suffix to destination file or folder names if the destination already exists, e.g.

```js
fs.move('a.txt', 'foo.txt', {suffix: true}) // 'a.txt' is now 'foo.txt'
fs.move('b.txt', 'foo.txt', {suffix: true}) // 'b.txt' is now 'foo copy.txt'
fs.move('c.txt', 'foo.txt', {suffix: true}) // 'c.txt' is now 'foo copy 2.txt'
```

The return value of `fs.move` would be the final, suffixed path.

I'm not sure if 'suffix' is the appropriate term, perhaps 'dupe', 'rename', 'dedupe'?  If there's interest, I'm happy to put together a PR. I've written the code already for my own project

**Comment by RyanZim** [comment]
I'm going to rule this as out of scope. It's a nice feature for more user-facing applications, but fs-extra tends to focus on developer-facing features (for example, we have `remove()` but not `trash()`). Good idea for a standalone npm package, perhaps, though.

**Comment by davidmerfield** [comment]
Fair enough – thanks for your work on fs-extra
